<?php 
     $showAddToProgram = false;
     $me = $this->identity();
     if ($me) {
         if ($proposal->getPropLevel()==$this->configItem('demodyne.level.city') && 
             ( $proposal->getCity()===$me->getCity() || $proposal->getCity()===$me->getCity()->getFullCity() ||
                 ($proposal->getCity()->getDistrictCode()==$me->getCity()->getDistrictCode() && 
                     $proposal->getCity()->getFullCity()===$me->getCity()->getFullCity()) ||
                 ($proposal->getPropFullCity() && $proposal->getCity()->getFullCity()===$me->getCity()->getFullCity()))) {
	         $showAddToProgram = true;
	     }
	     if ($proposal->getPropLevel()==$this->configItem('demodyne.level.region') && $me->getCity()->getRegion()===$proposal->getCity()->getRegion()) {
	         $showAddToProgram = true;
	     }
	     if ($proposal->getPropLevel()==$this->configItem('demodyne.level.country') && $me->getCountry()===$proposal->getCity()->getCountry()) {
	         $showAddToProgram = true;
	     }
     }
?>
<?php if ($showAddToProgram && $me && !$me->isAdministration()):?>			
	
    <?php $program = $me->getProgramForLevel($proposal->getPropLevel())?>
    
    <?php if (!$program || !$program->hasProposal($proposal)):?>
    	<a
    				href="<?= $this->url('program', array( 'action'=>'add-proposal', 'id'=>$proposal->getPropUUID()));?>"
    				data-id="<?= $proposal->getPropUUID()?>" id="add-to-program" title="<?= $this->translate('Add to my Program')?>">
    				<img class="bot5" src="/img/icon-programme-violet.svg" width="18"></a> 
    <?php else:?>
    	<a
    				href="<?= $this->url('program', array( 'action'=>'add-remove-proposal', 'id'=>$proposal->getPropUUID()));?>"
    				data-id="<?= $proposal->getPropUUID()?>"
    				id="remove-from-program" title="<?= $this->translate('Remove from my Program')?>"><img class="bot5" src="/img/icon-programme-remove-violet.svg" width="18"></a> 
    <?php endif;?>

<?php endif;?>