
<!-- LEVEL MENU -->
		<div style="padding-left: 0px!important; padding-right: 0px!important; ">
			<ul class="nav nav-pills dunga" id="myTab">
				<li <?=$this->tab=='news'?'class="active"':''?>> <a href="<?=$this->url('news', ['action'=> 'news'])?>"><img src="/img/icon-news.svg" width="20" title="News"></a></li>
				<li <?=$this->tab=='proposals'?'class="active"':''?>><a href="<?=$this->url('proposal', ['action'=> 'all-proposals'])?>"><i class="fa fa-bullhorn" title="Citizen Proposals"></i></a>
				</li>
				<li><a href="#"><img src="/img/icon-programme-33.svg" width="20" title="Citizen Programs"></a>
				</li>
				<li><a href="#"><img src="/img/icon-official-measures-33.svg" width="20" alt="Official Measures"></a>
				</li>
				<li><a href="#"><img src="/img/icon-events-33.svg" width="20" alt="Events & Live Sessions"></a>
				</li>
			</ul>
		</div>
<!-- /LEVEL MENU -->

    </div>

