<div class="jumbotron" style="border-top-left-radius: 0px; border-top-right-radius: 0px;">

    <div class="title-mobile"><?= $this->translate('About us')?></div>




<div class="row">

<div class="col-md-12">




<h3>Qu'est-ce que DEMODYNE ?</h3><hr>
    
    <p>Demodyne est une plateforme en ligne à but <strong>non-lucratif</strong>, dont le but est d'optimiser la prise de décision collaborative
et la coordination des actions dans une communauté. Elle est pensée pour devenir à terme un outil complet de <strong>démocratie participative</strong>,
efficace dans chaque ville, région et pays.</p>
     
     <p>Puisqu'elle n'est pilotée ni par une entreprise privée, ni par une entité politique, Demodyne est véritablement indépendante et se focalise sur la méthodologie et non l'idéologie. C'est un bien commun numérique, comme par exemple Wikipedia.</p>
<p>L'équipe qui développe et fait vivre Demodyne est basée dans l'est de la France.</p>
     
     <p><strong>DEMODYNE est-il Open Source ?</strong><br>
Oui, DEMODYNE tourne sous licence libre <a href="http://www.gnu.org/licenses/agpl-3.0.fr.html" target="_blank"></a>AGPLv3 (http://www.gnu.org/licenses/agpl-3.0.fr.html)</p>
      
      
<h3>&nbsp;</h3>
<h3>En quoi DEMODYNE est-elle une étape importante vers une démocratie "réelle" ?</h3><hr>

	<p><strong>Pour l'instant, ce que nous appelons notre "démocratie" est en fait une forme primitive</strong>. Elle n'est pas tellement plus évoluée que celle qui se pratiquait déjà dans les sociétés antiques de Rome ou Athènes. Tous les 4 ou 5 ans, les citoyens délèguent à une personne ou un petit groupe toute autorité pour prendre les décisions concernant la gestion de leur ville, région ou pays. La plupart du temps cela se réduit à un choix binaire entre deux programmes politiques pré-construits, sans possibilité de voter sur chaque mesure. Les représentants élus rendent compte de façon irrégulière, la transparence budgétaire est incomplète. Il n'y a pas du vue d'ensemble des besoins, des compétences disponibles et des opportunités.</p>
	<p>Ce fonctionnement pouvait se justifier tant que la technologie ne permettait pas de recueillir en temps réel l'opinion des citoyens sur chaque sujet.<br>
Ce n'est plus le cas aujourd'hui.</p>

<h3>&nbsp;</h3>
<h3>DEMODYNE remet les Citoyens au centre de toutes les décisions et stratégies, c'est à dire à leur vraie place.</h3><hr>

<p>Cela représente également une <strong>opportunité unique pour la classe politique</strong> et les professionnels de l'administration publique.</p>
<p>Plus besoin de se lancer dans l'interprétation hasardeuse des résultats d'une élection: maintenant chaque vote est porteur d'une information précise sur un sujet donné.</p>
<p>Plus de communication générique dispersée aux quatre vents: maintenant ils peuvent s\'adresser directement à des groupes de citoyens et partenaires en fonction de leur centres d'intérêts et compétences.</p>
<p>L'opinion publique est une force constructive avec laquelle un dialogue structuré et continu est possible, pas une masse indistincte qui "sanctionne dans
les urnes". Mieux encore, les administrations publiques peuvent coordonner le volontariat dans leur communauté grâce à la fonctionnalité Demodyne Community Service
(DCS).</p>



<h3>&nbsp;</h3>
<h3>Qui peut utiliser DEMODYNE ? Est-ce gratuit ?</h3><hr>

<p>Tout le monde peut utiliser DEMODYNE. Il y a trois types de comptes utilisateur sur DEMODYNE:</p>

<ul>
	<li><strong>Compte Citoyen:</strong> compte individuel, personnel et gratuit pour les citoyens. Créez le votre dès maintenant !</li>
	<li><strong>Compte Partenaire (à venir):</strong> compte pour les entrepreneurs, sociétés, associations... en somme, toute entité fournissant des services à la communauté. Gratuit pour les structures à but non-lucratif, et soumis à abonnement pour les structures à but lucratif. Le montant de l'abonnement annuel est basé sur la fourchette de revenu annuel de l'entité concernée. Il reste toujours négligeable par rapport à ce revenu.</li>
	<li><strong>Compte Administration:</strong> compte pour les administrations publiques qui ont la responsabilité principale dans la gestion des villes, regions, états ou pays. Il est gratuit.</li>
</ul>

<p>Tous les abonnements et dons collectés sont utilisés pour financer le développement et la maintenance technique de la plateforme.
Nous pourrons ainsi la maintenir vierge de toute publicité et indépendante des gouvernements et des intérêts privés.</p>


<h3>&nbsp;</h3>
<h3>DEMODYNE est-elle disponible dans tous les pays ?</h3><hr>

<p>C'est l'objectif Smile Nous prévoyons de lancer dans de multiples pays chaque année en fonction de nos ressources disponibles. Nous commençons avec une Beta ouverte France,  aux Etats Unis (Etat de New York), et la Roumanie.</p>

<p>Pour permettre à DEMODYNE d'exister dans votre pays, trois principales choses sont nécessaires:</p>

<ol>
	<li>une traduction de la plateforme dans la langue du pays</li>
	<li>une structure à but non-lucratif (association, fondation...) pour piloter la plateforme dans le pays. Notre philosophie est de mettre en place à chaque fois que possible des partenariats avec des équipes et structures existantes qui se battent déjà pour le développement de la démocratie directe/participative dans leur pays. Les modalités de la collaboration sont décrites dans la Charte DEMODYNE</li>
	<li>une adaptation de la base de donnée et de l'interface aux spécificités du pays (structure administrative, domaine de compétence des administrations locales etc.)</li>
</ol>

<p>Si vous souhaitez nous aider dans ces étapes et accélérer l'arrivée de DEMODYNE dans votre pays, n'hésitez pas à poster sur nos Forums Nationaux ou
contacter l'équipe de développement de DEMODYNE directement - <a href="mailto:contact@demodyne.org">contact@demodyne.org</a></p>
  

<h3>&nbsp;</h3>
<h3>Qui est derrière DEMODYNE ?</h3><hr>

<p>Le pilotage global de DEMODYNE est assuré par une association a but non-lucratif, l'Initiative pour une Gouvernance Direct (DirGovIn), basée en France près Strasbourg.La DirGovIn reçoit les financements globaux et paie une petite équipe pour travailler sur la stratégie, trouver les partenariats locaux et globaux et développer le code, l'interface et la base de donnée de la plateforme.</p>
<p><img src="/img/photo_de_groupe.jpg" title="Fondateurs DirGovIn et équipe Demodyne - oct 2015" width="100%"><br>
<strong>Fondateurs DirGovIn et équipe Demodyne - oct 2015</strong></p>
	
<p>L'équipe projet Demodyne actuelle:

<ul>
	<li>Quentin DESVIGNE: créateur de DEMODYNE, chargé de la stratégie, Communication & Partenariats</li>
	<li>Dragos DOBRE: développeur principal, creation et gestion base de données, gestion du serveur</li>
	<li>Alex NICULITA: webdesigner principal, graphiste, responsable interface et expérience utilisateur</li>
	<li>Violeta TOMOȘOIU: Networking Manager Europe et directeur de lancement Roumanie </li>
</ul>

<p>Dans chaque pays, un ou plusieurs Opérateurs Nationaux sont identifiés pour piloter la plateforme sur le territoire national. Ils sont listés dans les Forums Nationaux.Ils reçoivent les financements nationaux et locaux et ont leurs propres équipes chargées de faire connaître la plateforme et dynamiser la communauté dans leur zone géographique. Chaque Opérateur National est indépendant et autonome, il doit cependant êtr signataire de la Charte DEMODYNE,
dont la communauté es gardienne.</p>

<p><strong>Notre philosophie est que DEMODYNE appartient avant tout à sa communauté d'utilisateurs. En d'autres termes, l'évolution de la plateforme, sa stratégie, sa croissance, ses fonctionnalités sont déterminés par une consultation permanente et des votes de la communauté.</strong></p>


  </div>



</div><!-- end row -->







</div><!-- end jumbotron -->





  