<?= $this->partial('partial/page-header.phtml', ['title' => $this->translate('About us')])?>


<div class="jumbotron" style="border-top-left-radius: 0px; border-top-right-radius: 0px;">





<div class="row">

<div class="col-md-12">




<h3>What is DEMODYNE ?</h3><hr>
<img src="/img/elipse-1-en.png " class="pull-right img-responsive" title="outil complet de démocratie participative">
    
    <p>DEMODYNE is a non-profit, online platform designed to transform the way we decide and act together as a community.
      It is intended to be an "all-in-one" tool to implement participative democracy in every city, region, state and country.</p>
      
      <p><strong>Is DEMODYNE Open Source ?</strong><br>
Yes, DEMODYNE operates under <a href="http://www.gnu.org/licenses/agpl-3.0.en.html" target="_blank">Open Source licence AGPLv3</a> (http://www.gnu.org/licenses/agpl-3.0.en.html)</p>
      
      
<h3>&nbsp;</h3>
<h3>Why is DEMODYNE an important step towards true democracy ?</h3><hr>

	<p>Currently, what we call democracy still works in a quite primitive way, not so different from what it was already in ancient Greece or Rome. Once every 4 or 5 year, people delegate full authority to a person or a group to make all decisions regarding the management of their city, state or country. Most of the times, this boils down to a binary choice between two pre-constructed political programs, without any possibility to vote on each measure. The elected representatives report back infrequently, budgetary transparency is incomplete, there is no overview of needs, skills available, opportunities.</p>
     <p>This could be somehow justified as long as technology did not allow to collect and aggregate efficiently the citizen's input on each topic. 
      Today this is no longer the case.</p>
     <p> With DEMODYNE, citizens can finally express themselves everyday, on all aspects of the political program to be implemented.<br>
       They can act at various scales from local to national, make their own proposals, express agreement or disagreement with official measures and other citizens' proposals alike.<br>
       They can get in touch directly with Partners able to implement the proposals: entrepreneurs, businesses, nonprofit associations.<br>
       They can track how their tax money is spent and send a clear message on where to spend more and where to spend less.<br>
       ... and much more.</p>


<h3>&nbsp;</h3>
<h3>In short, DEMODYNE puts the Citizens back at the center of all decisions and strategies, where they belong.</h3><hr>
<img src="/img/elipse-2-en.png " class="pull-right img-responsive" title="tremendous opportunity for the politicians in charge">

<p>This will also be a tremendous opportunity for the politicians in charge:<br>
      No more guessing to interpret voting results - now each voting action provides a clear signal on a specific topic.<br>
      No more blanket hit or miss communication - now they can send targeted newsletters to groups of citizens based on their interests or skills.<br>
      Public opinion is more than ever a constructive force with which a structured and continuous dialogue is possible.<br>
    Furthermore, public administrations can now coordinate voluntary work in their community through the Demodyne Community Service (DCS) feature.</p>
    
    
<h3>&nbsp;</h3>
	<h3>Who can use DEMODYNE ? Is it free ?</h3><hr>

<p>Everybody can use DEMODYNE. A nickname for the users is "Demonauts", as they are the explorers of this expanded democratic space Smile .
There are three types of DEMODYNE accounts:</p>

<ul>
	<li><strong>Citizen accounts:</strong> these are for individuals, they're personal and free.</li>
	<li><strong>Partners accounts:</strong> these are for entrepreneurs, businesses, associations... basically any entity providing services to the community.
They're free for non-profits, and subscription-based for for-profit entities. The annual fee is based on the entity's self-reported revenue bracket upon registration or renewal. It is always negligible in context of that revenue.</li>
	<li><strong>Administration accounts:</strong> these are for the public administrations running the cities, regions/states, and countries. They're free.
All fees and donations collected are used to pay for the development and maintenance costs of the platform and keep it ad-free and independent from corporations and governments.</li>
</ul>

<p>During Beta testing (roughly first half of 2016), registration will be free for all Partners, including for-profits - <strong>seize the opportunity !</strong></p>


<h3>&nbsp;</h3>
	<h3>Is DEMODYNE available in all countries ?</h3><hr>

<p>Ultimately, we want it to be. We plan to roll out in multiple countries each year, starting with USA, UK, France, Germany, Canada, Italy, Ireland and Romania.
Check the National Forums for updates.</p>
<p>To make it happen in your country, three things are required:</p>

<p>
<ol>
	<li>translation in local language</li>
	<li>a non-profit structure within the country to operate the platform. Our preferred approach is to work with existing teams and structures already supporting direct/participative democracy in their respective country. The modalities of the collaboration are described in the DEMODYNE Charter</li>
	<li>adaptation of the database and interface to some specificities of the country (administrative structure, area of competency for the various administrations etc.)</li>
</ol>
</p>

<p>If you're willing to help with any of the above and help us bring DEMODYNE to your country, don't hesitate to post in the National Forums or reach out to the DEMODYNE Dev team directly - <a href="mailto:contact@demodyne.org">contact@demodyne.org</a></p>


<h3>&nbsp;</h3>
<h3>Who is behind DEMODYNE ?</h3><hr>

<p>DEMODYNE is operated globally by a non-profit association, the Direct Governance Initiative (DirGovIn)</span> based in France near Strasbourg.  The DirGovIn receives the global funding and pays a small team to work on the general strategy, find national/local partnerships and develop the code and database of the platform.</p>
<p><img src="/img/photo_de_groupe.jpg" title="Fondateurs DirGovIn et équipe Demodyne - oct 2015" width="600"><br>
<strong>DirGovIn Founders and Demodyne Team - oct 2015</strong></p>

<p>The core team currently consists of:</p>

<p>
<ul>
	<li>Quentin DESVIGNE: creator of DEMODYNE, strategic director</li>
	<li>Dragos DOBRE: lead developer PHP &amp; Database</li>
	<li>Alex NICULITA: lead Designer, Interface and User Experienc</li>
	<li>Violeta TOMOȘOIU: Networking Manager Europe & Start-up Director for Romania</li>
</ul>
  </p>

<p>In each country, one or several National Operators are identified to operate the platform on the national territory.They're listed in the National Forums.  They receive national/local funding and have their own teams to promote the platform on their geographic territory. Although each National Operator is basically independent and autonomous, it must be a signatory of the DEMODYNE Charter, owned by the community.</p>
<p><strong>Our philosophy is that DEMODYNE belongs primarily to its community of users. In other words, the evolution of the platform, its strategy, its growth, its features, will be determined through consultation and community votes. Besides, you will be given a transparent overview of the resources we have and how they are utilized.</strong>
  </p>

  </div>



</div><!-- end row -->







</div><!-- end jumbotron -->





