<?= $this->partial('partial/page-header.phtml', ['title' => $this->translate('About us')])?>

<div class="jumbotron" style="border-top-left-radius: 0px; border-top-right-radius: 0px;">





<div class="row">

<div class="col-md-12">




<h3>Ce este DEMODYNE?</h3><hr>
<img src="/img/elipse-1-ro.png " class="pull-right img-responsive" title="unealtă completă a democraţiei participative">
    
    <p>DEMODYNE este o platformă on-line non-profit al cărei scop este de a optimiza procesul decizional de colaborare şi coordonare a acţiunilor într-o comunitate.
Este considerată a fi în cele din urmă un instrument complet pentru punerea în practică a unei democraţii participative eficiente în fiecare oraş, judeţ (regiune) şi ţară din lume.</p>
           <p><strong>Este DEMODYNE Open Source ?</strong><br>
Desigur, DEMODYNE operază sub licenţa <a href="http://www.gnu.org/licenses/agpl-3.0.en.html" target="_blank">Open Source licence AGPLv3</a> (http://www.gnu.org/licenses/agpl-3.0.en.html)</p>
      
      
<h3>&nbsp;</h3>
<h3>Cum este DEMODYNE un pas important spre o democraţie "reală"?</h3><hr>

	<p><strong>Deocamdată, ceea ce noi numim democraţia este de fapt o formă primitivă,</strong> nu cu mult mai avansată decât ceea ce a fost deja practicată în societăţile antice Romane sau Ateniene. La fiecare 4 sau 5 ani, cetăţenii deleagă unei persoane sau unui grup (partid politic) autoritatea de a lua decizii în ceea ce priveşte gestionarea oraşului lor, a judeţului (regiunii) sau a ţării. În cea mai mare parte a timpului este redus la o alegere binară între două programe politice preconstruite, fără posibilitatea de a vota fiecare măsură în parte. Oficialii aleşi predau raportul neregulat, transparența bugetară este incompletă, nu există o imagine de ansamblu a nevoilor, competenţelor disponibile şi a oportunităţilor.</p>
     <p><strong>Aceast tip de funcționare se putea justifica când tehnologia nu permitea colectarea opiniilor cetăţenilor în timp real pe fiecare subiect. Astăzi, acest lucru nu mai este cazul.</strong></p>
     <p>Cu ajutorul platformei online DEMODYNE cetăţenii se pot exprima în fiecare zi, cu privire la toate aspectele politice care urmează să fie puse în aplicare. Ei pot acţiona la diferite nivele, locale sau naţionale, pot face propriile propuneri, pot să-şi exprime acordul sau dezacordul cu măsurile oficiale ale administraţiei şi / sau propunerilor altor cetăţeni.</p>
      <p>Cetăţenii pot lua contact direct cu partenerii capabili să pună în aplicare propunerile: antreprenori, companii, asociaţii, etc. Pot urmări utilizarea banilor proveniți din impozite și trimite un semnal clar unde să se cheltuiască mai mult sau mai puțin.
Şi acesta este doar începutul.</p>


<h3>&nbsp;</h3>
<h3>Platforma online DEMODYNE plasează cetăţenii în centrul tuturor deciziilor şi strategiilor, adică la locul lor adevărat.</h3><hr>


<p>Aceasta reprezintă, de asemenea, <strong>o oportunitate unică pentru clasa politică şi administraţia publică.</strong> Nu mai este nevoie de a comanda sondaje de opinie costisitoare pentru a obţine interpretări riscante şi prea puţin precise a rezultatelor, acum fiecare vot din platforma online DEMODYNE poartă informaţii exacte cu privire la un anumit subiect. Cu ajutorul DEMODYNE nu mai există o comunicare generalizată și pierdută în vânt: acum comunicarea precisă se poate face direct cu grupurile de cetăţeni şi partenerii în funcţie de interesele şi abilităţile lor.</p>
<p>Opinia publică este o forţă constructivă cu care este posibil un dialog structurat şi continuu, nu o masă confuză care "sancţionează la urne."
Mai mult de atât, administrațiile publice pot coordona activitatea de voluntariat în comunitatea lor prin intermediul funcţiei Demodyne « servicii comunitare » (DCS / Demodyne Community Service).</p>


<h3>&nbsp;</h3>
<h3>Cine poate utiliza platforma online DEMODYNE? Este gratuită?</h3><hr>

<p>Oricine poate folosi DEMODYNE. Utilizatorii sunt denumiți "Demonauți" ca şi exploratori ai acestui spaţiu democratic.</p>
	<p>Există trei tipuri de conturi de utilizator pe DEMODYNE:</p>

<ul>
	<li><strong>Contul «Cetăţean»:</strong> cont individual, personal şi gratuit.</li>
	<li><strong>Contul «Partener»:</strong> cont pentru antreprenori, companii, asociaţii ... pe scurt, orice entitate care furnizează servicii de orice fel pentru comunitate. Gratuit pentru structurile non-profit (care fac obiectul înregistrării unei structuri non-profit) și pe baza unui abonament pentru structurile comerciale. Valoarea abonamentului anual se bazează pe intervalul de venit anual al entităţii în cauză. Rămâne însă o sumă infimă în raport cu veniturile.</li>
	<li><strong>Contul «Administraţie»:</strong> contul pentru administraţiile publice care au responsabilitatea principală în gestionarea oraşelor, judeţelor (regiunilor) sau ţării. Este gratuit.</li>
</ul>

 <p>Toate abonamentele şi donaţiile colectate sunt utilizate pentru a finanţa dezvoltarea şi întreţinerea tehnică a platformei şi pentru a o păstra liberă de orice formă de publicitate şi independenţă faţă de interesele administraţiilor, guvernelor sau a entităţilor private.</p>
 <p>În timpul testării versiunii Beta (al treilea trimestru 2016) înscrierile în contul Partener sunt gratuite.<br>
<strong>Profită de ocazie!</strong></p>
 
 
 <h3>&nbsp;</h3>
<h3>Este platforma DEMODYNE disponibilă în toate ţările?</h3><hr>
 
 <p>Acesta este obiectivul :) Avem de gând să lansăm în mai multe ţări în fiecare an, în funcţie de resursele disponibile. Am început cu o versiune Beta în Franţa şi în România şi ne propunem să lansăm de curând în SUA și în Marea Britanie, continuând mai apoi cu alte țări din UE. Accesaţi Forumul Național  pentru a monitoriza progresul şi pentru a ne sprijini în acest demers.</p>
 <p>Pentru a permite DEMODYNE să existe în ţara dumneavoastră, este nevoie de trei lucruri:</p>

<ol>
	<li>traducerea platformei în limba ţării</li>
	<li>o organizaţie non-profit (asociaţie, fundaţie ...) pentru a conduce platforma din ţară.
Filozofia noastră este de a pune în aplicare acolo unde este posibil parteneriate cu echipe şi structurile existente, care sunt deja în lupta pentru dezvoltarea democraţiei directe / participative în ţara lor. Termenii de colaborare sunt descrise în Carta DEMODYNE</li>
	<li>o adaptare a bazei de date şi a interfaţei utilizator la specificul ţării (structura administrativă, domeniile de competenţă ale autorităţilor locale, etc.)</li>
</ol>

<p>Dacă doriţi să ne sprijiniți în aceşti paşi şi să accelerăm împreună sosirea DEMODYNE în ţara voastră, nu ezitați să postați pe Forumul Național  sau să contactaţi direct echipa de dezvoltare DEMODYNE - <a href="mailto:contact@demodyne.org">contact@demodyne.org</a></p>
  

<h3>&nbsp;</h3>
<h3>Cine se află în spatele DEMODYNE?</h3><hr>

<p>Administrarea globală DEMODYNE este asigurată de o asociaţie non-profit, Direct Governance Initiative (DirGovIn) cu sediul în Franţa, aproape de Strasbourg. 
DirGovIn primeşte finanţare globală şi plăteşte o echipa mică pentru a lucra la strategia, la identificarea parteneriatelor locale sau globale şi la dezvoltarea platformei de cod, a interfaţei utilizator şi a bazei de date.</p>

<p><img src="/img/photo_de_groupe.jpg" title="Fondateurs DirGovIn et équipe Demodyne - oct 2015" width="600"><br>
<strong>Fondatorii DirGovIn şi echipa Demodyne - oct 2015</strong></p>
	
<p>Echipa Demodyne actuală:

<ul>
	<li>Quentin DESVIGNE: creator DEMODYNE, Strategy Director, Communications & Parteneriate</li>
	<li>Dragos DOBRE: Senior Developer (programare backend şi frontend), dezvoltator baza de date şi gestiune server</li>
	<li>Alex NICULITA: Senior Designer, responsabil pentru interfaţă şi experienţa utilizatorului</li>
	<li>Violeta TOMOȘOIU: Networking Manager Europa și director de lansare România</li>
</ul>

<p>În fiecare ţară, unul sau mai mulţi operatori naţionali sunt identificaţi pentru a conduce platforma din ţară. Ei sunt listaţi în forumurile naţionale. Aceștia primesc fonduri naţionale şi locale şi au propriile lor echipe responsabile de a face cunoscută platforma şi a energiza comunitatea din zona lor geografică.
Fiecare operator naţional este independent şi autonom ; el trebuie să fie totuşi un semnatar al Cartei DEMODYNE.</p>
<p><strong>Filozofia noastră este că DEMODYNE aparţine în primul rând comunității utilizatorilor. Cu alte cuvinte, evoluţia platformei, strategia sa, creşterea acesteia, funcţionalitatea sa este determinată de consultarea permanentă şi de voturile comunităţii. În plus, o transparenţă totală cu privire la resursele disponibile şi utilizarea acestora este regula de baza, pentru DirGovIn cât şi pentru operatorii naţionali.</strong></p>
  
  

  </div>



</div><!-- end row -->







</div><!-- end jumbotron -->





