<?= $this->partial('partial/page-header.phtml', ['title' => $this->translate('Legal')])?>

<div class="jumbotron" style="border-top-left-radius: 0px; border-top-right-radius: 0px;">

<div class="row">
<div class="col-md-12">


    <p>Platforma de web DEMODYNE este gestionată și editată de Asociația non-profit "Direct Governance Initiative" (1908, Codul de drept civil local Alsacia-Moselle) cu sediul în 1, rue de la Fontaine 68300 Saint-Louis.</p>
    
    <h3>Contact</h3><hr>

    <p>Email&nbsp;:  <a href="mailto:contact@demodyne.org">contact (at) demodyne.org</a><br>

    Telefon&nbsp;:  03 69 01 09 43 (intre orele 10h si 17h, inafara de weekend-uri si zile de srabatoare)<br>

    Director de publicare&nbsp;: Quentin Desvigne  </p>
    
        <h3>Hosting</h3><hr>

    <p>Site-ul este găzduit (hosting) de OVH :<br>

    SAS  cu un capital de 10 069 020 € <br>

    RCS  Lille Métropole 424 761 419 00045<br>

    Code  APE 2620Z<br>

    N°  TVA : FR 22 424 761 419<br>

Sediu social : 2 rue Kellermann - 59100 Roubaix - France.  </p>
    
    <p>&nbsp;</p>

    <p>Acest site în integralitatea lui se supune legilor franceze și internaționale privind drepturile de autor și a proprietății intelectuale. Toate drepturile de reproducere sunt rezervate, inclusiv pentru documentele iconografice și fotografice, cu excepția materialelor create sau prezentate de către utilizatori.</p>

    <p>Site-ul folosește cookie-uri pentru identificare (conectare) și funcționarea corespunzătoare a sesiunilor de utilizator. Nu sunt informații prelucrate de cookie-ul pentru a extrage date cu caracter personal sau în scopuri comerciale.</p>

    <p>Folosind platforma DEMODYNE, utilizatorul acceptă implicit cookie-uri și utilizarea acestora de către site.</p>







</div><!-- end column -->



</div><!-- end row -->







</div><!-- end jumbotron -->
