<?= $this->partial('partial/page-header.phtml', ['title' => $this->translate('Legal')])?>

<div class="jumbotron" style="border-top-left-radius: 0px; border-top-right-radius: 0px;">



<div class="row">
<div class="col-md-12">




    <p>The web platform DEMODYNE is managed and published by the non-profit association Direct Governance Initiative (law 1908, local civil code Alsace-Moselle) whose registered office is at 1, rue de la Fontaine 68300 Saint-Louis.</p>
    
    <h3>Contact</h3><hr>

    <p>Email&nbsp;:  <a href="mailto:contact@demodyne.org">contact (at) demodyne.org</a><br>

    Phone&nbsp;:  03 69 01 09 43 (10h - 17h, except weekends and legal holidays)<br>

    Publishing Director: Quentin Desvigne  </p>
    
    <h3>Hosting</h3><hr>

    <p>Hosting for the site is provided by OVH :<br>

    SAS capital of 10 069 020 € <br>

    RCS  Lille Métropole 424 761 419 00045<br>

    Code  APE 2620Z<br>

    VAT# : FR 22 424 761 419<br>

Head Office : 2 rue Kellermann - 59100 Roubaix - France.  </p>
    
    <p>&nbsp;</p>

    <p>The whole of this site falls under the French and international laws on the copyright and the intellectual property. All rights of reproduction are reserved, including for iconographic and photographic documents, with the exception of content created or deposited by users.</p>

    <p>The site uses cookies for login and user sessions. No information processed by cookies is used to extract personal data or for commercial purposes.</p>

    <p>By using the DEMODYNE platform, the user implicitly accepts cookies used by the site.</p>

</div><!-- end column -->



</div><!-- end row -->







</div><!-- end jumbotron -->
