
<div class="jumbotron" style="border-top-left-radius: 0px; border-top-right-radius: 0px;">

    <div class="title-mobile"><?= $this->translate('Legal')?></div>


<div class="row">
<div class="col-md-12">




    <p>

    La plateforme web DEMODYNE est pilotée et éditée par l'association à but non-lucratif Direct Governance Initiative (loi 1908, code civil local Alsace-Moselle) dont le siège est au 1, rue de la Fontaine 68300 Saint-Louis.</p>
    
    <h3>Contact</h3><hr>

    <p>Email&nbsp;:  <a href="mailto:contact@demodyne.org">contact (at) demodyne.org</a><br>

    Téléphone&nbsp;:  03 69 01 09 43 (entre 10h et 17h, hors weekend et fériés)<br>

    Directeur  de publication&nbsp;: Quentin Desvigne  </p>
    
    <h3>Hosting</h3><hr>

    <p>Le  site est hébergé par la société OVH :<br>

    SAS  au capital de 10 069 020 € <br>

    RCS  Lille Métropole 424 761 419 00045<br>

    Code  APE 2620Z<br>

    N°  TVA : FR 22 424 761 419<br>

Siège  social : 2 rue Kellermann - 59100 Roubaix - France.  </p>
    
    <p>&nbsp;</p>

    <p>L'ensemble de ce site relève des législations françaises et internationales sur le droit d'auteur et la propriété intellectuelle. Tous les droits de reproduction sont réservés, y compris pour les documents iconographiques et photographiques, à l'exception du contenu créé ou déposé par les utilisateurs.</p>

    <p>Le site utilise des cookies pour l'identification (login) et le bon fonctionnement des sessions utilisateurs. Aucune information traitée par les cookies n'est utilisée pour extraire des données personnelles ou dans un but commercial.</p>

    <p>En utilisant la plateforme DEMODYNE, l'utilisateur accepte implicitement les cookies et l'utilisation qui en est faite par le site.</p>

</div><!-- end column -->



</div><!-- end row -->







</div><!-- end jumbotron -->
