
<div class="jumbotron" style="border-top-left-radius: 0px; border-top-right-radius: 0px;">



    <div class="title-mobile"><?= $this->translate('Support us')?></div>
















	<div class="row">

		<div class="col-md-12">
		
		
<h3>Support Demodyne!</h3>
<hr>

<p>If you clicked on this link, it is probably that for you the improvement of our democratic processes and tools deserves at least the price of some coffees ... and even more if you have the capacity :)</p>

<p>Demodyne is run by a non-profit association and its development requires multiple and varied funding to preserve its independence - for us, there is no question of being dependent on a particular grant or sponsor.</p>

<p>The Partners accounts will ultimately provide, we hope, a steady income to cover the fixed costs of the platform (server and domain fees, small global development team, maintenance and communication with the community). But in the immediate future we do not monetize the platform which is open beta.</p>

<p>We have decided to launch regular small crowdfundings to finance the successive waves of new features under development. Pending the formalization of this process and a more detailed financial plan for the second half of 2016, we estimate our needs at about 5,000 euros for the quarter following the launch of the beta - by mid-July.</p>

<p>The association is young and has not yet asked for recognition of public utility (planned this year), so you can not benefit from the partial tax exemption of your direct donations. No worries, they just give less, we will be equally grateful :)</p>

<p>Send your donations by check with your contact information and message to:<br>
Association "Direct Governance Initiative"<br>
1, rue de la Fontaine<br>
68300 Saint-Louis</p>

<p>Brick by brick, with your help, we will be able to build a solid structure for the real democracy of tomorrow.</p>

<p>Thank you in advance for your support,
The DEMODYNE Team</p>


			

		</div>

	</div>























</div><!-- end jumbotron -->











