<?= $this->partial('partial/page-header.phtml', ['title' => $this->translate('Support us')])?>

<div class="jumbotron" style="border-top-left-radius: 0px; border-top-right-radius: 0px;">



















	<div class="row">

		<div class="col-md-12">

<h3>Susţine Demodyne !</h3>
<hr>
   
<p>Dacă aţi făcut clic pe acest link, este probabil pentru a îmbunătăţi procesele şi instrumentele propuse de noi.
Toţi merităm mai mult de la conducatorii noștri !</p>

<p>Demodyne este creată de către o asociaţie non-profit şi dezvoltarea acesteia este asigurată prin multiple şi variate forme de finanţare pentru a ne păstra independenţa - pentru noi nu se pune problema de a fi dependenţi de un patron sau de un anumit sponsor.</p>

<p>Partenerii (firmele comerciale) care se înregistrează în platforma DEMODYNE vor oferi în cele din urmă, să sperăm, un venit constant pentru a acoperi costurile fixe ale platformei (taxele de găzduire pe server, domeniu la nivel mondial şi echipa mică de specialişti IT pentru dezvoltarea, întreţinerea şi comunicarea cu comunitatea). Dar pentru versiunea de față deschisă în beta nu generăm nici un venit.</p>

<p>Ne-am decis să lansăm «crowdfundings» în mod regulat, de mici dimeniuni, pentru a finanţa valurile succesive de noi funcționalități IT în dezvoltare. 
În aşteptarea formalizării acestui proces şi a unui plan financiar detaliat pentru a două jumătate a anului 2016 și primul trimestru din 2017, am evaluat nevoile noastre în jurul valorii de 5.000 de euro pentru trimestrul urmat de lansarea versiunii beta.</p>

<p>Pentru a trimite donaţii va rugăm să ne contactați pe adresele:</p>

<p><a href="mailto:contact@demodyne.org">contact@demodyne.org</a><br>
<a href="mailto:quentin.desvigne@demodyne.org">quentin.desvigne@demodyne.org</a>
</p>

<p>Pas cu pas, cu ajutorul vostru, vom fi capabili să construim o structura solidă pentru democraţia reală de mâine.</p>

<p>Va mulţumim anticipat pentru sprijinul dumneavoastră,<br>
Echipa DEMODYNE</p>

			

		</div>

	</div>























</div><!-- end jumbotron -->











