
<div class="jumbotron" style="border-top-left-radius: 0px; border-top-right-radius: 0px;">


    <div class="title-mobile"><?= $this->translate('Terms & Conditions')?></div>









	<div class="row">

	  <div class="col-md-12">



<h3>1. Introducere</h3><hr>

<p><span class="label">1.1</span><strong> Acești termeni de utilizare se aplică oricărei utilizări a platformei online DEMODYNE (demodyne.org) și a serviciilor conexe.</strong></p>

<p>Prin utilizarea site-ului și a serviciilor, vă exprimați acceptarea completă a acestor termeni de utilizare. Când vă înregistrați ca utilizator pe DEMODYNE, vă vom cere să acceptați în mod explicit aceste condiții.</p>

<p><span class="label">1.2</span> <strong>Site-ul demodyne.org utilizează cookie-uri pentru identificarea și funcționarea corespunzătoare a sesiunilor de utilizator. </strong></p>
			
<p>Aceste cookie-uri NU vor fi folosite pentru a extragerea de date cu caracter personal sau în scopuri comerciale. Prin folosirea acestui site, acceptați utilizarea de cookie-uri, în conformitate cu această politică de confidențialitate.</p>

<h3>&nbsp;</h3>
<h3>2. Drepturi de autor și licență</h3><hr>

<p><span class="label">1.2</span> <strong>Site-ul demodyne.org (și toate sub-domeniile lui), interfața vizuală și funcțională, design-ul, precum și orice conținut sau grafic sunt supuse legislației franceze și internaționale privind drepturile de autor. </strong></p>
			
<p>Toate drepturile sunt rezervate asociației « Direct Governance Initiative », editor al site-ului, cu excepția conținutului creat sau postat pe site de către utilizatorii săi..</p>

<p><span class="label">2.2</span> <strong>Codul informatic demodyne.org este Open Source sub AGPLv3 (http://www.gnu.org/licenses/agpl-3.0.en.html).</strong></p>

<p><span class="label">2.3</span> <strong>Utilizatorii sunt de acord să respecte drepturile de proprietate intelectuală ale autorilor textelor originale și ale imaginilor pe care le publică pe platforma sub responsabilitatea lor.</strong> </p>
		<p>Prin postarea de conținut creat de ei înșiși pe platforma demodyne.org, utilizatorii acordă redactorilor de facto a site-ului și a altor utilizatori ai platformei online demodyne.org drepturile de reproducere a acestui conținut în cadrul site-ului în sine sau subdomeniilor sale (*.demodyne.org, * fiind variabilă).
		</p>


<h3>&nbsp;</h3>
<h3>3. Crearea contului și utilizarea corectă</h3><hr>


			<p><span class="label">3.1</span> <strong>Conturile « Cetățean »</strong></p>

<p>Pentru a crea un cont « Cetățean », utilizatorii trebuie să introducă în formularul online numele lor reale și adevărata lor localitate de reședința actual. Un individ poate deține doar un singur cont DEMODYNE « Cetățean ». Unei societăți comerciale (oricare ar fi forma ei de organizare) nu îi este permis să creeze un cont cetățean.</p>
<p>Adevăratul nume de utilizator este păstrat confidențial, cu excepția cazului în care proprietarul contului decide să îl facă public în profilul său.</p>

<p>Platforma DEMODYNE a fost concepută pentru a permite exprimarea deplină a drepturilor și privilegiilor cetățeanului care sunt atașate la identitatea, cetățenia și locul de reședință.</p>
<p>Folosirea de identități false, furtul de identitate, crearea de conturi multiple sau dezinformarea privind cetățenia sunt considerate încălcări grave ale condițiilor de utilizare.</p>
<p>Vom desfășura verificări periodice pentru a compara (în mod confidențial) datele înscrise în platforma DEMODYNE cu date publice ale cetățenilor. Aceasta este singura modalitate de a garanta credibilitatea și realitatea propunerilor și nivelul de sprijin din partea comunității.</p>

			<p><span class="label">3.2</span> <strong>Conturile « Administrație »</strong></p>
<p>Conturile de tip Administrație sunt strict rezervate pentru administrațiile publice responsabile de un oraș, o regiune sau o țară. Orice solicitare de a activa un cont Administrație cât și informațiile de contact furnizate vor fi verificate de către echipa DEMODYNE.
</p>

			<p><span class="label">3.3</span> <strong>Utilizarea corectă</strong></p>
<p>Toți utilizatorii platformei DEMODYNE sunt de acord să facă dovada unei atitudini civice în orice situație și să evite orice formă de agresiune, amenințare sau insultă. <br>
Atitudinile de ură, discriminatorii sau calomnioase duc automat la închiderea contului și în funcție de gravitate, pot face obiectul urmăririi penale.<br>
Subliniem că platforma online DEMODYNE este o agora virtuală a dezbaterii publice, un spațiu de discuții și cooperare serioasă. Prin urmare, se solicită contributorilor să acorde o atenție specială aortografiei și clarității publicațiilor lor.
</p>




<h3>&nbsp;</h3>
<h3>4. Datele conturilor</h3><hr>

<p>Ceea ce postați pe platforma DEMODYNE sunt considerate informații publice. O parte din profilul dvs. este întotdeauna public: alias-ul (nume de utilizator), orașul, prezentarea, avatarul sau imaginea de profil.<br>
Unele dintre datele dvs. sunt private și confidențiale în mod implicit, și puteți decide să le faceți publice pe profilul dvs.: numele real, anul nașterii și sexul.
În cele din urmă o parte din datele dvs. sunt întotdeauna private și confidențiale: e-mail, parola și telefonul.
</p>

<p>DEMODYNE și asociația « Direct Governance Initiative » sau operatorii naționali ai platformei (Demodyne FR, Demodyne RO, Demodyne US, etc...) nu vor divulga niciodată informațiile dvs. personale unor terțe părți (cu excepția cazului în care sunt constrânse prin lege sau printr-o hotărâre judecătorească). Vom pune la dispoziția terților prin intermediul site-ului sau a serviciilor conexe, statistici sau date agregate fără a divulga nici un fel de informații individuale.
</p>


		<p>&nbsp;</p>

		</div>

	</div>























</div><!-- end jumbotron -->
