
<div class="jumbotron" style="border-top-left-radius: 0px; border-top-right-radius: 0px;">




    <div class="title-mobile"><?= $this->translate('Terms & Conditions')?></div>








	<div class="row">

		<div class="col-md-12">



<h3>1. Introduction</h3><hr>

<p><span class="label">1.1</span> <strong>These terms and conditions govern the use of the DEMODYNE online platform (demodyne.org) and associated services.</strong></p>
<p> By using the website and services, you accept these conditions in full.<br>
  Upon registering and creating a DEMODYNE user account, we will ask you to expressly agree with these terms and conditions.
</p>
<p><span class="label">1.2</span> <strong>The demodyne.org website uses cookies. </strong></p>
<p>By using the website (hence agreeing with these terms and conditions), you consent to our use of cookies in accordance with our privacy and cookies policy. </p>

<h3>&nbsp;</h3>
<h3>2. Copyright and Licence</h3><hr>

<p><span class="label">1.2</span> <strong>The demodyne.org website (and all its subdomains), its visual and functional interface, its design, as well as any content or graphics are subject to French and international copyright laws.</strong></p>
			
<p>All rights are reserved to the association Direct Governance Initiative, editor of the site, with the exception of the contents created or deposited on the site by its users.</p>

<p><span class="label">2.2</span> <strong>The computer code of the demodyne.org site is Open Source, licensed AGPLv3 (http://www.gnu.org/licenses/agpl-3.0.fr.html).</strong></p>

<p><span class="label">2.3</span> <strong>Users undertake to respect the intellectual property rights of the original authors of the texts and images that they publish on the platform under their responsibility.</strong> </p>
<p>By publishing content created by themselves on the demodyne.org platform, users actually grant the publisher of demodyne.org and its other users the rights of reproduction for that content within the site itself and any of its subdomains (* .demodyne.org, * being variable).</p>



<h3>&nbsp;</h3>
<h3>3. Account Creation & fair use</h3><hr>

<p><span class="label">3.1</span> <strong>Citizen Accounts</strong></p>
<p> For Citizen accounts, users are required to create the account using their real name and their real, current home city.<br>
  We keep the real name confidential unless decided otherwise by the user in her/his profile settings.<br>
  Keep in mind that DEMODYNE is meant to be a way to express your privileges of citizen, which are strictly linked to your real identity and your place of residence.<br>
  Citizens should only registered if they are registered voters in their country.<br>
  Democracy is about rights but also responsibilities. We don't want people to invent false identities or worse, use other people's identity (which is also illegal).<br>
  We don't want DEMODYNE to be disconnected from the real world. We will conduct regular audits in cooperation with public administrations to ensure that names on our lists of users for a given city do match names on the list of registered citizens for that city.
</p>
			
<p><span class="label">3.2</span> <strong>Partner accounts</strong>
<p> For Partners account, users are required to use their entity name as registered according to locally applicable regulation (registered business or nonprofit name).<br>
  Entities should provide a relevant unique ID number delivered by national/local administrations, for example:<ul>
	<li>USA - Corporation ID number from State Registry or EIN/FEIN for businesses; 501©(3) number for non-profits</li>
	<li>France - SIREN/SIRET number</li>
</ul>
</p>

<h3>&nbsp;</h3>
<h3>4. Account Data</h3><hr>

<p>What you publish on the DEMODYNE platform is considered publicly available information.<br>
Some of your profile information is always public: your username, your home city, your user presentation ("About Me"/"About Us"), your avatar picture.<br>
Some of your profile information is private and confidential by default, but you may decide to make it public to other users: your real name, gender, age.<br>
Some of your profile information is always private and confidential: your email, phone number, password, payment information.
</p>

<p>DEMODYNE, DirGovIn or the National Operators of the platform (see Charter) will never share or sell your individual account information with any third party (unless required by locally applicable regulations or forced by a court of justice). We will share or sell statistics and aggregate data on the platform or derived services, without providing any individual account information.
</p>

<p><span class="label">4.1</span> <strong>Account Deletion</strong></p>

<p>If you delete your account:
<ul>
	<li>Your user profile will be immediately removed from the platform and cannot be seen anymore by other users.</li>
	<li>Your draft proposals, proposals in debate phase and your scenarios will be removed and cannot be seen anymore by other users.</li>
	<li>Your proposals in voting phase or implementation phase as well as your comments will not be deleted. They will remain visible, as "orphan", with no linked account, no username information and a note that the account of the original author has been deleted.</li>
	<li>Your count of hours in the Demodyne Community Service will be reduced to zero, all committed hours will be cancelled.</li>
	<li>Your money pledges for proposals or measures not yet in implementation phase will be cancelled.</li>
	<li>Payments due to you for your active micro-credits will be made using your last known address and financial information (bank account number) at the planned settlement date.</li>
</ul>
		</p>

			<p>&nbsp;</p>

		</div>

	</div>























</div><!-- end jumbotron -->
