<div class="jumbotron">

      <div class="row">

        <div class="col-md-2 tabbable tabs-left">

          <ul class="nav nav-tabs">

            <div class="text-center bot20"> 

              <script type="text/javascript">



                                        <!--



                                        var currentDate = new Date()



                                        var day = currentDate.getDate()



                                        var month = currentDate.getMonth() + 1



                                        var year = currentDate.getFullYear()



                                        document.write("<strong>" + day + "/" + month + "/" + year + "</strong>")



                                            //-->



                                    </script> 

              <br />

              <script type="text/javascript">



                                        <!--



                                        var currentTime = new Date()



                                        var hours = currentTime.getHours()



                                        var minutes = currentTime.getMinutes()







                                        if (minutes < 10)



                                            minutes = "0" + minutes







                                        document.write("<span style=\"font-size:28px;\">" + hours + ":" + minutes + " " + "</span>")



                                            //-->



                                    </script> 

            </div>

            <li class="active"><a href="#inbox" data-toggle="tab"><i class="fa fa-envelope-o"></i>

              <?= $this->translate('Inbox')?>

              </a></li>

            <li><a href="#mycontacts" data-toggle="tab"><i class="fa fa-book"></i>

              <?= $this->translate('Contacts')?>

              </a></li>

            <li><a href="#favorites" data-toggle="tab"><i class="fa fa-heart-o"></i>

              <?= $this->translate('Favorites')?>

              </a></li>

            <li><a href="#draftmeasures" data-toggle="tab"><i class="fa fa-university"></i>

              <?= $this->translate('Draft Measures')?>

              </a></li>

            <li>

              <hr>

            </li>

            <li class="active big"><strong>

              <?= $this->translate('Public Relations')?>

              </strong></span></li>

            <li><a href="#banner" data-toggle="tab"><i class="fa fa-picture-o"></i>

              <?= $this->translate('Banners')?>

              </a></li>

            <li><a href="#newsletter" data-toggle="tab"><i class="fa fa-newspaper-o"></i>

              <?= $this->translate('Newsletters')?>

              </a></li>

            <li><a href="#events" data-toggle="tab"><i class="fa fa-calendar"></i>

              <?= $this->translate('Events')?>

              </a></li>
              <li><a href="#my-sessions" data-toggle="tab"><i class="fa fa-users size15em"></i></a></li>

            <li class="bot20"></li>

          </ul>

        </div>

        

        <!--/2-->

        

        <div class="col-md-10 tab-content"> 

          

          <!-- INBOX -->

          

          <div class="tab-pane active" id="inbox">

            <?= $this->inboxSection ?>

          </div>

          

          <!-- end INBOX --> 

          

          <!-- CONTACTS -->

          

          <div class="tab-pane" id="mycontacts">

            <?= $this->contactsSection?>

          </div>

          

          <!-- end CONTACTS --> 

          

          <!-- FAVORITES -->

          

          <div class="tab-pane" id="favorites">

            <?= $this->favoritesSection ?>

          </div>

          

          <!-- end FAVORITES --> 

          

          <!-- DRAFTMEASURES -->

          

          <div class="tab-pane" id="draftmeasures">

            <?= $this->draftMesuresSection ?>

          </div>

          

          <!-- end DRAFTMEASURES --> 

          

          <!-- BANNERS -->

          <div class="tab-pane" id="banner">

            <?=$this->myBannersSection?>

          </div>

          <!-- end BANNERS --> 

          

          <!-- NEWSLETTER -->

          <div class="tab-pane" id="newsletter">

            <?=$this->myNewslettersSection?>

          </div>

          <!-- end NEWSLETTER --> 

          

          <!-- EVENTS -->

          <div class="tab-pane" id="events">

            <?=$this->myEventsSection?>

          </div>

          <!-- end EVENTS -->

            <!-- SESSIONS-->
            <div class="tab-pane" id="my-sessions">
                <?= $this->mySessionsSection ?>
            </div>
            <!-- end SESSIONS -->

        </div>

        

        <!-- /10 --> 

        

      </div>

      <!-- end date time row --> 

      

    </div>

    <!--/j--> 
