<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Demodyne</title>
<style type="text/css">
body,td,th {
	font-family: "Lucida Grande", "Lucida Sans Unicode", "Lucida Sans", "DejaVu Sans", Verdana, sans-serif;
	font-style: normal;
	font-weight: 400;
	font-size: 14px;
	color: #FFFFFF;
}
body {
	background-color: #544c42;
	margin-left: 100px;
	margin-top: 100px;
	margin-right: 100px;
	margin-bottom: 100px;
}
a:link {
	color: #FFD600;
	text-decoration: none;
}
a:visited {
	text-decoration: none;
}
a:hover {
	text-decoration: underline;
	color: #FFAE00;
}
a:active {
	text-decoration: none;
}
</style>
</head>

<body>
<br>
<p align="center"><a href="https://www.demodyne.org"><img src="https://www.demodyne.org/img/logo-vertical.png" title="DEMODYNE - Shape your Society"/></a></p>
<p align="center"><br>
  An error occurred. We will do our best to solve it quickly. </p>
<p align="center"><a href="javascript:history.back()">Go Back</a></p>
</body>
</html>
