<?php if ($list):?>
<div class="col-md-6 col-xs-6">
        <?= $this->translate('Commitment Score')?>: 
        
        <div >
<?php for ($i=0;$i<5;$i++):?>
	<?php $commitment--?>
   <?php if ($commitment>=0):?>
        <i class="fa fa-star orange size2em"></i>
	<?php elseif ($commitment==-0.5):?>
        <i class="fa fa-star-half-o orange size2em"></i>
	<?php else:?>
        <i class="fa fa-star-o gri size2em"></i>
	<?php endif;?>
<?php endfor;?>
</div>
        </div>
		<div class="col-md-6 col-xs-6">
        <?= $this->translate('Relevance Score')?>: 
        <div class="stars">
<?php for ($i=0;$i<5;$i++):?>
<?php $relevance--?>
   <?php if ($relevance>=0):?>
        <i class="fa fa-star orange size2em"></i>
	<?php elseif ($relevance==-0.5):?>
        <i class="fa fa-star-half-o orange size2em"></i>
	<?php else:?>
        <i class="fa fa-star-o gri size2em"></i>
	<?php endif;?>
<?php endfor;?>
</div>
        </div>
<?php else:?>

<strong><?= $this->translate('Commitment')?>:</strong>
<div >
<?php for ($i=0;$i<5;$i++):?>
	<?php $commitment--?>
   <?php if ($commitment>=0):?>
        <i class="fa fa-star orange size2em"></i>
	<?php elseif ($commitment==-0.5):?>
        <i class="fa fa-star-half-o orange size2em"></i>
	<?php else:?>
        <i class="fa fa-star-o gri size2em"></i>
	<?php endif;?>
<?php endfor;?>
</div>
<strong><?= $this->translate('Relevance')?>:</strong>
<div class="stars">
<?php for ($i=0;$i<5;$i++):?>
<?php $relevance--?>
   <?php if ($relevance>=0):?>
        <i class="fa fa-star orange size2em"></i>
	<?php elseif ($relevance==-0.5):?>
        <i class="fa fa-star-half-o orange size2em"></i>
	<?php else:?>
        <i class="fa fa-star-o gri size2em"></i>
	<?php endif;?>
<?php endfor;?>
</div>
<?php endif;?>

