<!-- user-profile/view -->

<div class="modal-header-soft round5top ui-draggable-handle">
<button type="button" class="close">
        <?php if ($_SESSION['level']['level']=='city'):?>
        <a href="<?= $this->url('city');?>"><i class="fa fa-home w"></i></a>
        <?php elseif ($_SESSION['level']['level']=='country'):?>
        <a href="<?= $this->url('country');?>"><i class="fa fa-home w"></i></a>
        <?php endif;?>
    </button>
  <button type="button" class="close" id="history-back"><i class="fa fa-arrow-circle-left w right10"></i></button>
  &nbsp; <span class="big" id="modal-dialog-title"><strong>
  <?= $this->translate('Citizen Profile Details')?>
  </strong></span>
</div>
<div class="jumbotron" style="border-top-left-radius: 0px; border-top-right-radius: 0px;" id="user-profile-view">
	<div class="row">
		<div class="col-md-2 col-xs-4 tabbable tabs-left">
			<ul class="nav nav-tabs">
				<div class="text-center bot10">
					<img src="<?=$this->basePath($user->getUsrPicture()) ?>"
						valign="middle" width="100%" alt="<?= $user->getUsrName() ?>"
						title="<?= $user->getUsrName() ?>" class="img-thumbnail"
						style="max-width: 200px !important;" />
				</div>
				<li class="active"><a href="#user-profile-info" data-toggle="tab"><i
						class="fa fa-info-circle"></i> <?= $this->translate('General Info')?></a></li>
				<li><a href="#user-profile-proplist" data-toggle="tab"><i
						class="fa fa-bullhorn"></i> <?= $this->translate('Proposals List')?></a></li>
				<li><a href="#user-profile-scenlist" data-toggle="tab"><i
						class="fa fa-object-group"></i> <?= $this->translate('Program List')?></a></li>
				<li><a href="#user-profile-ratings" data-toggle="tab"><i
						class="fa fa-star-half-o"></i> <?= $this->translate('Ratings')?></a></li>
				<li><br /></li>
			</ul>
		</div>
		<!--/2-->
		<div class="col-md-10 col-xs-8 tab-content">
			<!-- GENERAL INFO -->
			<div class="tab-pane active" id="user-profile-info">
				<?= $this->userInfo?>
			</div>
			<!-- /INFO -->
			<!-- PROPOSAL LIST -->
			<div class="tab-pane" id="user-profile-proplist">
<?= $this->userProposals?>
</div>
			<!-- /PROPOSAL LIST -->
			<!-- PROGRAM LIST -->
			<div class="tab-pane" id="user-profile-scenlist">
				<?=$this->userProgramsSection?>
			</div>
			<!-- /PROGRAM LIST -->
			
			<!-- RATINGS -->
			<div class="tab-pane" id="user-profile-ratings">
				<?=$this->userNotesSection?>
			</div>
			<!-- /ratings -->
			
		</div>
		<!--/10-->
	</div>
	<!-- /row -->
</div>
<!-- /j -->


<!-- /user-profile/view -->
