
<div class="container" style="padding: 0px!important;">



        <ul class="nav nav-tabs-mobile dunga">
            <li><img src="<?=$this->basePath($user->getUsrPicture()) ?>"
                     valign="middle" height="40"> </li>
            <li class="active"><a href="#user-profile-info" data-toggle="tab">
                    <i class="fa fa-info-circle"></i>
                </a></li>
            <li><a href="#user-profile-proplist" data-toggle="tab">
                    <i class="fa fa-bullhorn gri33"></i>
                </a></li>
            <li><a href="#user-profile-scenlist" data-toggle="tab">
                    <img src="/img/icon-programme-33.svg" width="20">
                </a></li>
            <li><a href="#user-profile-ratings" data-toggle="tab">
                    <i class="fa fa-star-half-o"></i>
                </a></li>

        </ul>
    </div>



		<!--/2-->
		<div class="tab-content">
			<!-- GENERAL INFO -->
			<div class="tab-pane active" id="user-profile-info">
				<?= $this->userInfo?>
			</div>
			<!-- /INFO -->
			<!-- PROPOSAL LIST -->
			<div class="tab-pane" id="user-profile-proplist">
<?= $this->userProposals?>
</div>
			<!-- /PROPOSAL LIST -->
			<!-- PROGRAM LIST -->
			<div class="tab-pane" id="user-profile-scenlist">
				<?=$this->userProgramsSection?>
			</div>
			<!-- /PROGRAM LIST -->
			<!-- CHAMPION ACTIVITY -->
			<div class="tab-pane" id="user-profile-champ">
				<h2 class="text-center">
					<i class="fa fa-trophy"></i> <?= $user->getUsrName() ?>'s <?= $this->translate('Champion Activity')?></h2>
				<hr class="bot20" />
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
						<span class="big"><strong><?= $this->translate('Currently Champion')?></strong></span> <?= $this->translate('for proposals')?>:
<ul>
							<li><span class="big"><a href="go-to-proposal">Proposal name from
										database</a></span></li>
							<li><span class="big"><a href="go-to-proposal">Proposal name from
										database</a></span></li>
							<li><span class="big"><a href="go-to-proposal">Proposal name from
										database</a></span></li>
						</ul>
						<hr>
						<p>
							<span class="big"><strong><?= $this->translate('Previously Champion')?></strong></span> <?= $this->translate('for')?> <span
								class="badge">x</span> <?= $this->translate('Proposals')?></p>
						<hr>
						<p>
							<span class="badge">x</span> <?= $this->translate('Steps currently assigned')?></p>
						<p>
							<span class="badge">x</span> <?= $this->translate('Steps completed')?></p>
					</div>
					<!--/6-->
				</div>
				<!--/r-->
			</div>
			<!-- /CHAMPION ACTIVITY -->
			<!-- RATINGS -->
			<div class="tab-pane" id="user-profile-ratings">
				<?=$this->userNotesSection?>
			</div>
			<!-- /ratings -->
			<!-- DCS ACTIVITY -->
			<div class="tab-pane" id="user-profile-dcs">
				<h2 class="text-center">
					<i class="fa fa-clock-o"></i> <?= $user->getUsrName() ?>'s <?= $this->translate('DCS Activity')?></h2>
				<hr class="bot20" />
				<div class="row">
					<div class="col-md-4 col-md-offset-2">
						<p>
							<span class="badge">x</span> <?= $this->translate('Current hours available')?></p>
						<p>
							<span class="badge">x</span> <?= $this->translate('Total pledged hours')?></p>
						<p>
							<span class="badge">x</span> <?= $this->translate('Total completed hours')?></p>
					</div>
					<!--/6-->
					<div class="col-md-4">
<?= $this->translate('Top 3 Preferred Categories')?>: 
<img src="<?php echo $this->basePath('img/environnement100x100.png') ?>"
							valign="middle" width="24" height="24"
							title="category title from database" / class="round5"> <img
							src="<?php echo $this->basePath('img/famille100x100.png') ?>"
							valign="middle" width="24" height="24"
							title="category title from databasee" / class="round5"> <img
							src="<?php echo $this->basePath('files/catImage1426170306.jpg') ?>"
							valign="middle" width="24" height="24"
							title="category title from database" / class="round5">
						<hr>
						<p>
							<span class="big"><strong><?= $this->translate('Preferred activities')?>:</strong></span>
						</p>
						Pellentesque nibh. Aenean quam. In scelerisque sem at dolor.
						Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel
						nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit
						quis, luctus non, massa. Fusce ac turpis quis ligula lacinia
						aliquet. Mauris ipsum.
					</div>
					<!--/6-->
				</div>
				<!--/r-->
				<hr />
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
						<button type="submit" class="btn btn-orange">
							<i class="fa fa-bar-chart"></i> <?= $this->translate('Submit DCS request')?></button>
					</div>
				</div>
			</div>
			<!-- /DCS ACTIVITY -->
		</div>
