<div class="modal-header-soft round5top ui-draggable-handle topm20">
<button type="button" class="close" id="history-back"><i class="fa fa-arrow-circle-left w right10"></i></button>
  <span class="big" id="modal-dialog-title"><a href="/"><img src="<?= $this->basePath('img/logo30.png') ?>" valign="middle" width="140" height="30" alt="DEMODYNE - Shape your Society"/></a> - <strong><?= $this->translate('Request an account as Public Administration')?></strong></span>
</div>



<div class="jumbotron" style="border-top-left-radius: 0;border-top-right-radius: 0;" id="">
        
        
<?=$this->translate('Thank you for registering with Demodyne. We will check your account information and we will send an email to notify you when your account will be validated.')?>
        
        

</div><!--/j-->  

