<div class="modal-header-soft round5top ui-draggable-handle topm20">

  <span class="big" id="modal-dialog-title"><a href="/"><img src="<?= $this->basePath('img/logo30.png') ?>" valign="middle" width="140" height="30" alt="DEMODYNE - Shape your Society"/></a> - <strong><?= $this->translate('Citizen Registration')?></strong></span>
</div>



<div class="jumbotron text-center" style="border-top-left-radius: 0px;border-top-right-radius: 0px;" id="">
        
<?= $this->translate('Your registration has already been confirmed. ')?><br><br>
    <span ><a href="/" class="btn btn-orange"><?= $this->translate('Login')?></a></span>


</div><!--/j-->  

