<div class="modal-header-soft round5top ui-draggable-handle topm20">
  <button type="button" class="close" id="history-back"><i class="fa fa-arrow-circle-left w right10"></i></button>
  <span class="big" id="modal-dialog-title"><a href="/"><img src="<?= $this->basePath('img/logo30.png') ?>" valign="middle" width="140" height="30" alt="DEMODYNE - Shape your Society"/></a> - <strong><?= $this->translate('Password Reset')?></strong></span>
</div>

<div class="jumbotron" style="border-top-left-radius: 0px; border-top-right-radius: 0px;" id="">





<div class="row">
<div class="col-md-6 col-md-offset-3 col-xs-12 col-xs-offset-0">

<p>&nbsp;</p>
<p><?= $this->translate('Forgotten your password? Enter your e-mail address below, and we\'ll send you an e-mail allowing you to reset it')?>.</p>


<?php
$form = $this->form;
$form->setAttribute('action', $this->url('home/user-register', array('action' => 'forgotten-password')));
$form->prepare();?>   

<?=  $this->form()->openTag($form);?>

<fieldset>
<div class="input-group bot10" style="width:55%">
  <span class="input-group-addon"><i class="fa fa-envelope-o fa-fw"></i></span>
  <?= $this->formElement($form->get('usrEmail'));?> 
</div>
 <span class="text-danger"><?= $this->formElementErrors($form->get('usrEmail'));?></span>
<div class="input-group bot10">
        <!-- <button type="reset" class="btn btn-default">Cancel</button> -->
        <button type="submit" class="btn btn-orange"><?= $this->translate('Generate new password')?></button>
</div>
</fieldset>

<?=  $this->form()->closeTag();?>

<p><?= $this->translate('Please')?> <a href="mailto:support@demodyne.net"><?= $this->translate('contact us')?></a> <?= $this->translate('if you have any trouble resetting your password')?>.</p>


</div>
</div><!--/r-->


</div><!--/j-->







