<div class="modal-header-soft round5top ui-draggable-handle topm20">
<a type="button" class="close" id="history-back"><i class="fa fa-arrow-circle-left w right10"></i></a>
<a class="close" href="page/help#partner-registration" id="partner-registration"><i class="fa fa-question-circle w right10"></i></a>&nbsp;
  <span class="big" id="modal-dialog-title"><a href="../"><img src="<?= $this->basePath('img/logo30.png') ?>" valign="middle" width="140" height="30" alt="DEMODYNE - Shape your Society"/></a> - <strong><?= $this->translate('Partner Registration')?></strong></span>
</div>

      
<div class="jumbotron" style="border-top-left-radius: 0px;border-top-right-radius: 0px;">









	<div class="row">
		<div class="col-md-12 text-center">
			<img src="<?= $this->basePath('img/uc.png') ?>">
			<p><span class="orange big">DEMODYNE / <?= $this->translate('Partner Registration')?></span> <?= $this->translate('is under construction')?>.<br />

<?= $this->translate('Please come back later. Thank you')?>!</p>
			<p>&nbsp;</p>
		</div>
	</div>











</div><!-- end jumbotron -->





