<div class="modal-header-soft round5top ui-draggable-handle topm20">
    <a href="/" class="close"><i class="fa fa-home w right10"></i></a>
    <span class="big" id="modal-dialog-title"><a href="/">
            <img src="<?= $this->basePath('img/logo30.png') ?>" valign="middle" width="140" height="30" alt="DEMODYNE - Shape your Society"/></a> -
        <strong><?= $this->translate('Password Reset')?></strong></span>
</div>



<div class="jumbotron text-center" style="border-top-left-radius: 0px;border-top-right-radius: 0px;" id="">
<div class="row top20">
  <div class="col-md-4"></div>
    <div class="col-md-4 text-justify">
<p><?=sprintf($this->translate('You have requested a new randomized secured password to be sent to: %s'), $usr_email)?><br>
</p>
<p><?=$this->translate('If this address is registered in our system, you will receive an email with the password.')?>&nbsp;
<?=$this->translate('Remember to also check your spam/junk folder if nothing is coming to your inbox.')?>
</p>
<p><?=$this->translate('Once logged in, you can change your password manually in your account settings.')?></p>

<p class="text-center"><a href="/" class="btn btn-orange"><?=$this->translate('Login')?></a></p>
<p><hr></p>
<p><?=$this->translate('Need help with your Demodyne account?')?><br>
<?=$this->translate('Email us at')?> <a href="mailto:support@demodyne.org">support@demodyne.org</a>
</p>


    </div>
      <div class="col-md-4"></div>
</div>






</div><!--/j-->