

<br><br>
<div class="row">
	<div class="col-md-12 text-center big">
<?= $this->translate('Registration closed.')?>
</div>
</div>
<br><br>
<div class="row">
	<div class="col-xs-12">
		<hr />
	</div>
</div>
<div class="row">
	
	<div class="col-md-12 text-right">
		<button type="button" class="btn btn-default" data-dismiss="modal">
			<i class="fa fa-ban"></i>
              <?= $this->translate('Close')?>
              
            </button>
		
	</div>
</div>
<!-- /r -->
        
