<div class="modal-header-soft round5top ui-draggable-handle topm20">
<button type="button" class="close" id="history-back"><i class="fa fa-arrow-circle-left w right10"></i></button>
  <span class="big" id="modal-dialog-title"><a href="/"><img src="<?= $this->basePath('img/logo30.png') ?>" valign="middle" width="140" height="30" alt="DEMODYNE - Shape your Society"/></a> - <strong><?= $this->translate('Citizen Registration')?></strong></span>
</div>



<div class="jumbotron" style="border-top-left-radius: 0px;border-top-right-radius: 0px;" id="">
        
<?= $this->translate('Website under construction. Registration closed.')?>


</div><!--/j-->  

