

	
	<?php
$form->prepare();
$form->setAttribute('method', 'post'); 
$form->setAttribute('action', $this->url('home/user-register')); ?>
  
<?=$this->form()->openTag($form);?>
	<fieldset>
		<div class="row">
			<div class="col-md-12">
				

				
				<div class="form-group">
					<label class="col-md-4 control-label text-right"><?= $this->translate('E-mail'); ?></label>
					<div class="col-md-8 bot5"><?= $this->formElement($form->get('usrEmail'));?>
						<span class="text-danger"><?= $this->formElementErrors($form->get('usrEmail'));?></span>
					</div>
				</div>
			</div>
			<!-- /6 -->
		</div>
		<!-- end row -->
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<label class="col-md-4 control-label text-right"><?= $this->translate('Username'); ?></label>
					<div class="col-md-8 bot5"><?= $this->formElement($form->get('usrName'));?>
						<span class="text-danger"><?= $this->formElementErrors($form->get('usrName'));?></span>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<label class="col-md-4 control-label text-right"><?= $this->translate('Password'); ?></label>
					<div class="col-md-8 bot5"><?= $this->formElement($form->get('usrPassword'));?>
						<span class="text-danger"><?= $this->formElementErrors($form->get('usrPassword'));?></span>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<label class="col-md-4 control-label text-right"><?= $this->translate('Confirm password'); ?></label>
					<div class="col-md-8 bot5"><?= $this->formElement($form->get('usrPasswordConfirm'));?>
						<span class="text-danger"><?= $this->formElementErrors($form->get('usrPasswordConfirm'));?></span>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<label class="col-md-4 control-label text-right"><?=$this->translate('Retype the characters displayed in the image')?></label>
					<div class="col-md-8 bot5"><?= $this->formElement($form->get('captcha'));?> 
                    <?php if ($form->get('captcha')->getMessages()):?>
                    <span class="text-danger"><?= $this->formElementErrors($form->get('captcha'));?></span>
                    <?php endif;?>
                    </div>
				</div>
			</div>
		</div>
		
		<div class="row">
			<div class="col-md-12">
		<hr>
		</div>
		</div>     
		<div class="row" style="text-align: center;">
			<div class="col-md-12 top10 bot10">
			   <a href="<?=$this->url('home/user-register', ['action' => 'facebook-registration'])?>" id="user-registration-facebook" 
		data-dialog-title="<?=$this->translate('Register with Facebook')?>">
			<img alt="<?=$this->translate('Register with Facebook')?>" src="<?=$this->basePath('/img/register-facebook-'.$_SESSION['language']['language'].'.png')?>"></a>
			  
              </div>
		</div>      
		<?= $this->formHidden($form->get('userCSRF'));?>

	</fieldset>






	<div class="row">
		<div class="col-xs-12">
			<hr />
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 text-right">
			<button type="button" class="btn btn-default"
				data-dismiss="modal">
				<i class="fa fa-ban"></i>
              <?= $this->translate('Cancel')?>
              
            </button>
            <button type="submit" class="btn btn-orange" id="user-registration-submit">
<i class="fa fa-sign-in" aria-hidden="true"></i> <?= $this->translate('Register')?></button>
		</div>
	</div>
	<!-- /r -->


	<?=  $this->form()->closeTag();?> 
</div>



<script type="text/javascript">

$(function() {
	userRegistrationUserRegistrationHandlers();

	$('#user-registration-facebook').click(function() {
		
		FB.login(function(response){
			if (response.status === 'connected') {
				testAPI();
			    	modalDialog('facebook-registration-dialog', $('#user-registration-facebook').data("dialog-title"), $('#user-registration-facebook').attr("href"), false);
		    } else if (response.status === 'not_authorized') {

		    } else {

		    }
		}, {scope: 'public_profile,email,user_location,user_birthday'});
		return false;
	});
	
});    

</script>

<script>
  
  window.fbAsyncInit = function() {
      FB.init({
        appId      : '220020655059875',
        cookie     : true,  
        status     : true,      
        xfbml      : true, 
        version    : 'v2.7' 
      });

    };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  function testAPI() {
    FB.api('/me?fields=id,name,email,first_name,last_name,age_range,link,gender,locale,picture,timezone,updated_time,verified,location,birthday', function(response) {
        console.log(response);
      	console.log('Successful login for: ' + response.name);
    });
  }
  
</script>

