


<div class="row">
	<div class="col-md-12">
<?= $this->translate('An e-mail has been sent to you. Please, check your inbox and confirm your registration!')?>
</div>
</div>

<div class="row"><div class="col-md-12">
<?= $this->translate('Remember to also check your <strong>spam/junk folder</strong>, sometimes validation emails end up there by accident :) ')?>
</div></div>

<div class="row">
	<div class="col-xs-12">
		<hr />
	</div>
</div>
<div class="row">
	
	<div class="col-md-12 text-right">
		<button type="button" class="btn btn-default" data-dismiss="modal">
			<i class="fa fa-ban"></i>
              <?= $this->translate('Close')?>
              
            </button>
		
	</div>
</div>
<!-- /r -->
        
