<?php $article = $this->article; $user=$this->user; $now = new \DateTime();?>


<?= $this->partial('partial/page-header.phtml', ['title' => '<a href="'.$this->url('blog', array('action'=>'articles')).'"><i class="fa fa-coffee size15em w" title="'.$this->translate('Go To Blog').'"></i></a>  '.$this->translate('Blog Article')])?>


<div class="jumbotron" id="blog-view-article"
     style="border-top-left-radius: 0px; border-top-right-radius: 0px;">



    <div class="row">
        <div class="col-md-8 col-md-offset-2 col-xs-12 col-xs-offset-0">

          <span class="blog-title" id="blog-view-article-articleTitle"><?= $article?$article->getArticleTitle():'Title'?></span>
          <hr>
          <?if (!$article || $article->getArticleImage()):?>
          <img id="blog-view-article-preview" style="min-width: 200px!important; max-width: 100%;" src="<?=$article?$article->getArticleImage():''?>" title="<?=$this->translate('Article Image')?>">
            <?endif;?>
          <hr>
          <i class="fa fa-user"></i> <?=$article?$article->getUsr()->getUsrName():($user?$user->getUsrName():'Author')?> |
          <i class="fa fa-tag"></i> <?= $this->translate('Tag')?> - <span id="blog-view-article-articleCategory"><?=ucfirst(array_search($article?$article->getArticleCategory():1, $this->configItem('demodyne.blog.tag')))?></span> |
          <i class="fa fa-clock-o"></i> <?=$this->dateFormat($article?($article->getArticlePublishedDate()?$article->getArticlePublishedDate():$article->getArticleCreatedDate()):$now, IntlDateFormatter::MEDIUM,  IntlDateFormatter::NONE, $article?$article->getCountry()->getCountryFormat():$user->getCountry()->getCountryFormat())?> |
          <i class="fa fa-eye"></i> <?=$article?$article->getArticleViews():0?> |
          <i class="fa fa-comments"></i> <?=$article?count($article->getComments()):0?>
<br><br>
<?= $this->partial('partial/social-links.phtml', [
      'type' => 'proposal',
      'url' => $this->url('proposal', array('action'=>'view', 'id'=>'123456'), array('force_canonical' => true)),
      'title' => 'title',
      'description' => 'description'
  ]); ?>
  <hr>
  <br>
          <span id="blog-view-article-articleDescription"><?= $article?$article->getArticleDescription():'This article talks about...'?></span>
<hr>
            <?= $this->commentsSection;?>
        </div>
    </div>
</div>
