
<?php $paging = $this->sortingDivPaginationHelper($pagedArticles, $page, $this->url('blog', array('action'=>'list', 'country'=> $countryCode, 'tag'=>$tag)), 'list', $limit); ?>


<div id="blog-list-published">
	<?php if (count($pagedArticles)):?>

  <?php foreach ($pagedArticles as $article):?>

 


  
  
  <div class="row">

  <div class="col-xs-12 col-sm-12 col-md-12 wbr">
			
			<div class="pull-left" style="min-width: 90px!important">
			<img src="<?=$this->basePath($article->getArticleImage())?>"
				height="57" width="75" class="round5" title="<?=$article->getArticleTitle()?>">
	  </div>
<div style="margin-left: 90px!important">	  
					<a
						href="<?= $this->url('blog', array('action'=>'article', 'id'=> $article->getArticleSlug()))?>"><span
						class="big">

						<?=$article->getArticleTitle()?></span></a><br>
			<i class="fa fa-user"></i> <?=$article?$article->getUsr()->getUsrName():($user?$user->getUsrName():'Author')?> | 
			<i class="fa fa-tag"></i> <?= $this->translate('Tag')?> - <?=$this->translate(ucfirst(array_search($article->getArticleCategory(), $this->configItem('demodyne.blog.tag'))))?> |
            <i class="fa fa-clock-o"></i> <?=$this->dateFormat($article->getArticlePublishedDate()?$article->getArticlePublishedDate():$article->getArticleCreatedDate(), IntlDateFormatter::MEDIUM,  IntlDateFormatter::NONE, $article?$article->getCountry()->getCountryFormat():$user->getCountry()->getCountryFormat())?> |
            <i class="fa fa-eye"></i> <?=$article?$article->getArticleViews():0?> |
            <i class="fa fa-comments"></i> <?=$article?count($article->getComments()):0?>

           <br>

          <?php $articleDescription = preg_replace('/<[^>]*>/', ' ', $article->getArticleDescription());

      $articleDescription = (strlen($articleDescription) > 150) ? substr($articleDescription, 0, 150) . '...' : $articleDescription;?>

          <?=$articleDescription?>
</div>
</div>




</div>
 

	<hr>

  

  

  <?php endforeach;?>

<div class="row">
		<div class="col-md-12">
				<?= $paging; ?>
			</div>
		<!--/12-->
	</div>
	<!-- /row -->


  <?php else:?>
  <div class="row">
		<div class="col-md-12">
				<?php if (!$searchTerms):?>
            		<?=sprintf($this->translate('No articles published for Demodyne %s.'), $selectedCountry->getCountryName())?>
            	<?php else:?>
            		<?=$this->translate('No articles matching your search terms.')?>
            	<?php endif;?>
			</div>
		<!--/12-->
	</div>
	<!-- /row -->
	
  <?php endif;?>

</div>



