
<?php $paging = $this->sortingDivPaginationHelper($pagedArticles, $page, $this->url('blog', array('action'=>'list-draft', 'country'=> $countryCode, 'tag'=>$tag)), 'list-draft', $limit); ?>

<div id="blog-list-draft">


	<?php if (count($pagedArticles)):?>

  <?php foreach ($pagedArticles as $article):?>

 

  <div class="bot10">
  	<img src="<?=$this->basePath($article->getArticleImage())?>" style="min-width: 200px!important; max-width: 100%;" class="round5" title="<?=$article->getArticleTitle()?>">
  	<br>
					<a
						href="<?= $this->url('blog', array('action'=>'article', 'id'=> $article->getArticleSlug()))?>"><span
						class="big">

						<?=$article->getArticleTitle()?></span></a><br>
			<i class="fa fa-user"></i> <?=$article?$article->getUsr()->getUsrName():($user?$user->getUsrName():'Author')?> |
			<i class="fa fa-tag"></i> <?= $this->translate('Tag')?> - <?=$this->translate(ucfirst(array_search($article->getArticleCategory(), $this->configItem('demodyne.blog.tag'))))?><br>
            <i class="fa fa-clock-o"></i> <?=$this->dateFormat($article->getArticlePublishedDate()?$article->getArticlePublishedDate():$article->getArticleCreatedDate(), IntlDateFormatter::MEDIUM,  IntlDateFormatter::NONE, $article?$article->getCountry()->getCountryFormat():$user->getCountry()->getCountryFormat())?> |
            <i class="fa fa-eye"></i> <?=$article?$article->getArticleViews():0?> |
            <i class="fa fa-comments"></i> <?=$article?count($article->getComments()):0?>


               <br>

          <?php $articleDescription = preg_replace('/<[^>]*>/', ' ', $article->getArticleDescription());

      $articleDescription = (strlen($articleDescription) > 150) ? substr($articleDescription, 0, 150) . '...' : $articleDescription;?>

          <?=$articleDescription?>
</div>

 

	<hr>

  

  

  <?php endforeach;?>

<div class="row">
		<div class="col-md-12">
				<?= $paging; ?>
			</div>
		<!--/12-->
	</div>
	<!-- /row -->


  <?php else:?>
  <div class="row">
		<div class="col-md-12">
				<?php if (!$searchTerms):?>
            		<?=$this->translate('No draft articles.')?>
            	<?php else:?>
            		<?=$this->translate('No articles matching your search terms.')?>
            	<?php endif;?>
			</div>
		<!--/12-->
	</div>
	<!-- /row -->
	
  <?php endif;?>


</div>

  <script type="text/javascript">

$(function() {


	blogListDraftHandlers();

});



</script>

