
<?php
$title = 'Change Password Request';
?>

<div style="Margin-left:20px;Margin-right:20px;Margin-top:24px">
    <h1 style="Margin-top:0;Margin-bottom:20px;font-style:normal;font-weight:normal;color:#3b3e42;font-size:24px;line-height:40px;font-family:Roboto,sans-serif;text-align:center"><?=$this->translate("Your password has been changed!")?></h1>
</div>

<div style="Margin-left:20px;Margin-right:20px">
    <p style="Margin-top:30px;Margin-bottom:20px;"><?=sprintf($this->translate("You've received this email because you requested a new password for your %s account."), '<a href="'.$this->url('home', [], ['force_canonical' => true]).'" style="color: #62a8ea!important">demodyne.org</a> ')?>

        <?=$this->translate("Your new password is:")?><br>

        <center><span style="font-size: 20px!important;"><?=$password?></span></center>
    </p>
</div>

<br>

<div style="Margin-left:20px;Margin-right:20px">
    <div style="Margin-bottom:20px;text-align:center">
        <center><a style="border-radius:4px;display:block;font-size:14px;font-weight:normal;line-height:24px;padding:12px 24px 13px 24px;text-align:center;text-decoration:none!important;color:#000;background-color:#fa9c18;font-family:Roboto,sans-serif; max-width: 200px;" href="<?=$this->url('home', [], array('force_canonical' => true))?>">Login to Demodyne</a>
        </center>
    </div>
</div>