<!-- vote/view -->

<?php

$proposal->setPropSavedName(str_replace('"', '&rdquo;', $proposal->getPropSavedName()) );

$opposed = $voteValue['opposed'];
$unfavourable = $voteValue['unfavourable'];
$neutral = $voteValue['neutral'];
$favourable = $voteValue['favourable'];
$veryfavourable = $voteValue['veryfavourable'];
$totalvotes = $voteValue['totalvotes'];
$totalpoints = ((5+$voteValue['totalpoints'])/10)*100;
?>





<!-- LINIAR GAUGE atention we have 2 lines of javascript at the bottom of the file  -->

<div class="row">

	<div class="<?= $text?'col-md-9 col-xs-8':'col-md-12 col-xs-12'?>">





<a href="#" data-popover-content="#myPopover<?=$proposal->getPropUUID()?>" rel="popover" data-placement="bottom" data-original-title="<strong><?= $proposal->getPropSavedName() ?></strong> <br> <?= $this->translate('Breakdown of votes')?>">

		<div class="progress" style="width: 100%; height:15px; background: -moz-linear-gradient(left,  #d81515 0%, #ffd400 50%, #2d7200 100%);
    background: -webkit-linear-gradient(left,  #d81515 0%,#ffd400 50%,#2d7200 100%);
    background: linear-gradient(to right,  #d81515 0%,#ffd400 50%,#2d7200 100%);
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#d81515', endColorstr='#2d7200',GradientType=1 );">

			<?php if (!$proposal->isMeasure()):?>
			<div style="padding-left: 70%; color:#000; position:absolute; z-index:1;"><img src="<?= $this->basePath('img/line.png')?>"></div>
			<?php endif;?>

			 <div style="padding-left: calc((<?=$totalpoints?>% + 1.2%) - 8px); color:#000; position:relative; z-index:1;"><img src="<?= $this->basePath('img/square.png')?>"></div>

            <div class="progress-bar progress-bar-degrade" style=" width: 100%" ></div>

		</div>

</a>



<div id="myPopover<?=$proposal->getPropUUID()?>" class="hide" style="width:250px !important;">





<div class="row bot5">
<div class="col-md-12 small">
<?= $this->translate('Very Favorable')?> - <strong><?=$veryfavourable?></strong> <?= $this->translate('votes')?> (<?= $totalvotes?round(($veryfavourable/$totalvotes)*100):0?>%)
</div>
<div class="col-md-12">
<div class="progress" style="max-height:10px;">
<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: <?= $totalvotes?($veryfavourable/$totalvotes)*100:0?>%"></div></div>
</div>
</div><!--/r-->

<div class="row bot5">
<div class="col-md-12 small">
<?= $this->translate('Favorable')?> - <strong><?=$favourable?></strong> <?= $this->translate('votes')?> (<?= $totalvotes?round(($favourable/$totalvotes)*100):0?>%)
</div>
<div class="col-md-12">
<div class="progress" style="max-height:10px;">
<div class="progress-bar progress-bar-favorable" role="progressbar" aria-valuenow="7" aria-valuemin="0" aria-valuemax="100" style="width: <?= $totalvotes?($favourable/$totalvotes)*100:0?>%"></div></div>
</div>
</div><!--/r-->

<div class="row bot5">
<div class="col-md-12 small">
<?= $this->translate('Neutral')?> - <strong><?=$neutral?></strong> <?= $this->translate('votes')?> (<?= $totalvotes?round(($neutral/$totalvotes)*100):0?>%)
</div>
<div class="col-md-12">
<div class="progress" style="max-height:10px;">
<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="22" aria-valuemin="0" aria-valuemax="100" style="width: <?= $totalvotes?($neutral/$totalvotes)*100:0?>%"></div></div>
</div>
</div><!--/r-->

<div class="row bot5">
<div class="col-md-12 small">
<?= $this->translate('Unavorable')?> - <strong><?=$unfavourable?></strong> <?= $this->translate('votes')?> (<?= $totalvotes?round(($unfavourable/$totalvotes)*100):0?>%)
</div>
<div class="col-md-12">
<div class="progress" style="max-height:10px;">
<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="18" aria-valuemin="0" aria-valuemax="100" style="width: <?= $totalvotes?($unfavourable/$totalvotes)*100:0?>%"></div></div>
</div>
</div><!--/r-->

<div class="row bot5">
<div class="col-md-12 small">
<?= $this->translate('Opposed')?> - <strong><?=$opposed?></strong> <?= $this->translate('votes')?> (<?= $totalvotes?round(($opposed/$totalvotes)*100):0?>%)
</div>
<div class="col-md-12">
<div class="progress" style="max-height:10px;">
<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: <?= $totalvotes?($opposed/$totalvotes)*100:0?>%"></div></div>
</div>
</div><!--/r-->


<div class="row bot5">
<div class="col-md-12 small">
<?php if ($proposal->getPropCheck()==0):?>
<?= $this->translate('A minimum of 30 votes is required for significance')?>
<?php elseif ($proposal->getPropCheck()==1):?>
<?=$this->translate('A minimum of 20% of active users is required. Users with at least 1 login within the last 3 months are considered active.')?>
<?php elseif ($proposal->getPropCheck()==2):?>
<?=$this->translate('Insufficient citizen support so far.')?>
<?php else:?>
<?php $dDiff = $proposal->getPropCheckTimer()->diff(new \DateTime());
      $dDiff->format('%R');?>
      <?= sprintf($this->translate("Ratio of positive votes reached. Implementation starts in %d days"), 14-$dDiff->days)?>

<?php endif;?>
</div>

</div><!--/r-->



</div><!--/popover-->











	</div><!--/9-->

	<?php if ($text):?>

    	<div class="col-md-3 col-xs-4">

        <span class="badge" title="Total Votes"><?=$totalvotes?></span> <?= $this->translate('votes')?>

        </div><!--/3-->

    <?php endif;?>

</div><!--/r-->



<?php if ($text):?>

<div class="row">

<div class="col-md-12 small">

<?php if ($proposal->getPropCheck()==0):?>
<?= $this->translate('More votes required for significance')?>
<?php elseif ($proposal->getPropCheck()==1):?>
<?=$this->translate('More votes required for significance')?>
<?php elseif ($proposal->getPropCheck()==2):?>
<?=$this->translate('Insufficient citizen support so far.')?>
<?php else:?>
<?php $dDiff = $proposal->getPropCheckTimer()->diff(new \DateTime());
      $dDiff->format('%R');?>
      <?= sprintf($this->translate("Ratio of positive votes reached. Implementation starts in %d days"), 14-$dDiff->days)?>

<?php endif;?>

</div><!--/12-->

</div><!--/r-->

<?php endif;?>





<script>$(function(){    $('[rel="popover"]').popover({		trigger: "hover" ,        container: 'body',		width: '25px',        html: true,        content: function () {            var clone = $($(this).data('popover-content')).clone(true).removeClass('hide');            return clone;        }    }).click(function(e) {        e.preventDefault();    });});    </script>
<!-- /vote/view -->
    