<div id="banner-carousel-banners" class="carousel slide bot20"

     data-url="<?= $this->url('administration/banner', array('action'=>'carousel-banners'));?>">

    <?php $activeBanners = count($activeBanners)?$activeBanners:$user->getCountry()->getLevelBanners($_SESSION['level']['levelValue']);?>

    <?php if (count($activeBanners)):?>

        <?php if (count($activeBanners)>1):?>
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <?php foreach($activeBanners as $index => $banner):?>
                <li data-target="#banner-carousel-banners"
                    data-slide-to="<?=$index?>" <?=$index==0?'class="active"':''?>></li>
            <?php endforeach;?>
        </ol>
    <?php endif;?>

        <!-- Wrapper for slides -->

        <div class="carousel-inner bggray round5" role="listbox">



            <?php if (count($activeBanners)):?>

                <?php foreach($activeBanners as $index => $banner):?>

                    <div class="item bg-image <?=$index==0?'active':''?> round5" style="background-image: url(<?=$this->basepath($banner->getBannerImage())?>); background-size: 100% 100%;

                            background-repeat: no-repeat;">

                        <a href="<?=$banner->getBannerUrl()?>" target="_blank"

                           title="<?=$banner->getBannerDescription()?>"><span

                                    style="align-content: center; margin: 0 auto;"><img

                                        src="/img/blank.png" class="img-responsive"></span></a>

                    </div>

                    <!-- /.item -->



                <?php endforeach;?>


            <?php endif;?>



        </div>

        <!-- /.carousel-inner -->

    <?php if (count($activeBanners)>1):?>

        <!-- Controls -->

        <a class="left carousel-control" href="#banner-carousel-banners"

           role="button" data-slide="prev"> <span

                    class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <span

                    class="sr-only">

      <?= $this->translate('Previous'); ?>

      </span>

        </a> <a class="right carousel-control" href="#banner-carousel-banners"

                role="button" data-slide="next"> <span

                    class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> <span

                    class="sr-only">

      <?= $this->translate('Next'); ?>

      </span>

        </a>

    <?php endif;?>

        <script>

            !function ($) {

                $(function(){

                    // carousel demo

                    $('#banner-carousel-banners').carousel()

                })

            }(window.jQuery)

        </script>



    <?php endif;?>

</div>





<!-- /.carousel -->