<?php

$city = $user->getCity();
if ($_SESSION['level']['level']=='city') {
    $levelName = ($city->getFullCity()?$city->getFullCity()->getCityName():$city->getCityName());
    $levelUrl = $this->url('browse', [
        'country' => $city->getCountry()->getCountryName(),
        'postalcode' => $city->getCityPostalcode(),
        'region'=> $city->getRegion()->getRegionName(),
        'cityname' => $city->getCityName()
    ], array('force_canonical' => true));
}
elseif ($_SESSION['level']['level']=='region') {
    $levelName = $city->getRegion()->getRegionName();
    $levelUrl = $this->url('browse',
        ['country' => $city->getCountry()->getCountryName(),
            'region'=> $city->getRegion()->getRegionName(),
        ], array('force_canonical' => true));
}
elseif ($_SESSION['level']['level']=='country') {
    $levelName = '<img src="/img/flags/'.str_replace(' ', '-', $city->getCountry()->getCountryName()).'.png" style="margin-bottom: 4px;" width="20" height="14" alt="'. $city->getCountry()->getCountryName() .'"> '.$city->getCountry()->getCountryName();
    $levelUrl = $this->url('browse', ['country' => $city->getCountry()->getCountryName()]);
}
else {

}
?>

<?php $paging = $this->sortingDivPaginationHelper($pagedProposals, $page, $this->url('measure', array('action'=>'all-measures')), 'all-measures', $limit, $sort, $order); ?>
<div class="jumbotron parent" id="measure-all-measures"
	data-url="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>$sort, 'page'=>$page, 'order'=>$order, 'results' => $limit));?>"
	data-add-to-my-program="<?=$this->translate('Add to my Program')?>"
	data-add-favorite="<?=$this->translate('Add Favorite')?>"
	data-remove-favorite="<?=$this->translate('Remove Favorite')?>">
	
	

	
	
	<div class="panel panel-default panel-body orangebackground">
<?= sprintf($this->translate('These are the Official Measures announced by the Public Administration in charge of <a href="%s">%s</a>.'), $levelUrl, $levelName)?>
 <br>
<?= $this->translate('They are either published directly by the Administration with its Demodyne account, or crowdsourced by the citizens.')?><br>
<?= $this->translate('If you notice that an official measure is missing, you can add it as long as you cite sources (administration website, reliable news websites).')?><br>
<?= $this->translate('Do not post here your own proposals or ideas as a citizen: go to the <a href="#allprop">Citizen Proposals</a> tab')?>.
</div>
	
	
	
	
	
	
	
	<div class="row">
		<div class="col-md-8">
			<?php if ($user->getUsrId() && ($user->isCitizen() || ($user->isAdministration() && $user->getAdmin()->getAdminLevel() == $_SESSION['level']['levelValue'] ))):?>
			<button type="button"
				data-url="<?= $this->url('measure', array('action'=>'add-measure')); ?>"
				class="btn btn-orange" id="measure-all-measures-add-new-measure"
				data-dialog-title="<?=$user->isAdministration()?$this->translate('New Official Measure for $level$'):$this->translate('Submit missing Official Measure for $level$')?>">
				<i class="fa fa-plus-circle"></i> 
                <?php if ($user->isAdministration()):?>
                <?= $this->translate('Create a new measure')?>
                <?php else:?>
                <?= $this->translate('Submit missing measure')?>
                <?php endif;?>
            </button>
            <?php elseif (!$user->getUsrId()):?>
				<?= $this->partial('partial/please-register-button.phtml', ['text' => '<i class="fa fa-plus-circle"></i> '.$this->translate('Submit missing measure')]); ?>
			<?php endif;?>	
			<span class="big"><?= sprintf($this->translate('%d Official Measures for <span id="level-name">%s</span>'), $proposalCount, $levelName)?></span>
		</div>
		<!-- /8 -->
		<div class="col-md-4">
			<div class="fltr">
				<ul class="nav">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-down"></i> </span>
							<!--  by <span class="caret"></span> -->
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'category', 'page'=>1, 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Category')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'name', 'page'=>1, 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Name')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'status', 'page'=>1, 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Status')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'user', 'page'=>1, 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Owner')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'page'=>1, 'sort'=>'votes', 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Number of Votes')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'page'=>1, 'sort'=>'vote-average', 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Vote average')?></a></li>
							<li class="divider"></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'page'=>1, 'sort'=>'published', 'order'=>'desc'));?>"><?= $this->translate('Published date')?></a></li>
						</ul></li>
				</ul>
			</div>
			<div class="fltr">
				<ul class="nav">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-up"></i> </span>
							<!-- by <span class="caret"></span> -->
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'category', 'page'=>1, 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Category')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'name', 'page'=>1, 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Name')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'status', 'page'=>1, 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Status')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'user', 'page'=>1, 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Owner')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'page'=>1, 'sort'=>'votes', 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Number of Votes')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'page'=>1, 'sort'=>'vote-average', 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Vote average')?></a></li>
							<li class="divider"></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'published', 'page'=>1, 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Published date')?></a></li>
						</ul></li>
				</ul>
			</div>
			<div class="fltr right10 top5"> <?= $this->translate('Sorted by')?> <?php if ($sort=='published'):?><?= $this->translate('Published date')?>
                    									<?php elseif ($sort=='votes'):?><?= $this->translate('Number of Votes')?>
                    									<?php elseif ($sort=='vote-average'):?><?= $this->translate('Vote average')?>
                    									<?php else:?><?=$this->translate(ucfirst($sort))?>
                    									<?php endif;?>  
                    <?=$order=='asc'?'<i class="fa fa-arrow-up"></i>':'<i class="fa fa-arrow-down"></i>'?></div>
		</div>
		<!--/6-->
	</div>
	<!-- /row -->
	<hr>

            <?php if(count($pagedProposals)>0):?>

                <?php foreach($pagedProposals as $index => $proposal): ?>








	<div class="row">

		<div class="col-xs-12 col-sm-12 col-md-4">

			<div class="pull-left" style="min-width: 42px !important">
				<img
					src="<?= $this->basePath()?>/files/<?= $proposal->getCat()->getCatImage() ?>"
					height="34" width="34" class="round5" 
					title="<?= $proposal->getCat()->getCatCat()->getCatName() ?>">
			</div>
			<div style="margin-left: 42px !important">
<?php $proposalDescription = preg_replace('/<[^>]*>/', ' ', $proposal->getPropDescription());  
      $proposalDescription = (strlen($proposalDescription) > 150) ? substr($proposalDescription, 0, 150) . '...' : $proposalDescription;?>

<a
					href="<?= $this->url('measure', array('action'=>'view-measure', 'id'=>$proposal->getPropUUID()));?>"
					title="<?= $proposalDescription ?>" id="city-proposal-item"
					data-id="<?= $proposal->getPropUUID()?>"><span class="big"><?= $proposal->getPropSavedName() ?></span></a>
				<br />
<?= $this->translate('in')?> <?= $proposal->getCat()->getCatCat()->getCatName() ?> - <?= $proposal->getCat()->getCatName()?>
					<br />
				<!-- user -->
					<?= $this->translate('by')?> <a
					href="<?= $this->url('user/profile', array('action'=>'mini-profile', 'id'=>$proposal->getUsr()->getUsrUUID()));?>"
					data-title="<?= $proposal->getUsr()->getUsrName() ?>'s mini profile"
					data-id="<?=$proposal->getUsr()->getUsrUUID()?>" id="view-profile">
					<span class="badge"><?= $proposal->getUsr()->getUsrName() ?></span>
				</a> <span class="nobr"><i class="fa fa-clock-o"></i> <?= $proposal->getPropPublishedDate()?$proposal->getPropPublishedDate()->format('d/m/Y'):'' ?></span>
			</div>
		</div>

	
		<?php if ($_SESSION['level']['level']=='country'):?>
		<div class="col-xs-12 col-sm-4 col-md-4">
			<?=$proposalDescription?>
  		</div>
		<?php else:?>
		<div class="col-xs-12 col-sm-4 col-md-2">
			<?= $this->translate('Current Status')?>:
			<br /> 
			<?= $this->partial('partial/proposal-status.phtml', ['proposal' => $proposal])?>
			<br/> 
			<?= $this->translate('Last updated')?>: <span
				class="nobr"><i class="fa fa-clock-o"></i> <?= $proposal->getPropSavedDate()->format('d/m/Y')?> </span>
		</div>
		<?php $measure = $proposal->getMeasure();?>
		<div class="col-xs-12 col-sm-4 col-md-2">
			<?= $this->translate('Start')?>: <?=$measure->getMesStartDate()?$measure->getMesStartDate()->format('d/m/Y'):$this->translate('Undefined')?> <br>
			<br>
			<?= $this->translate('Cost')?>: <?=$measure->getMesCost()?$measure->getMesCost().' '.$proposal->getCity()->getCountry()->getCountryCurrency():$this->translate('Undefined')?>
  		</div>
		<?php endif;?>
		<div class="col-xs-6 col-sm-4 col-md-2">
    		<?= $this->{"status-details-$index"}?>
       	</div>
		<div class="col-xs-6 col-sm-4 col-md-2 text-right">
	<?= $this->partial('partial/proposal-actions.phtml', ['user' => $user, 'proposal' => $proposal])?>
	</div>
	</div>




	<hr />

                        <?php endforeach; ?>
<div class="row">
		<div class="col-md-12">
				<?= $paging; ?>
			</div>
		<!--/12-->
	</div>
	<!-- /row -->
                    <?php else:?>
<div class="row">
		<div class="col-md-12">
			<?php if ($_SESSION['level']['level']=='city'):?>
        		<?php if ($user->isAdministration()):?>
                	<?= $this->translate('There are no measures in your city.')?>
                <?php else:?>
               		<?= $this->translate('There are no measures in your city. Be the first to submit a missing measure.')?>
                <?php endif;?>
			<?php elseif ($_SESSION['level']['level']=='region'):?>
        		<?php if ($user->isAdministration()):?>
                	<?= $this->translate('There are no measures in your region.')?>
                <?php else:?>
               		<?= $this->translate('There are no measures in your region. Be the first to submit a missing measure.')?>
                <?php endif;?>
			<?php elseif ($_SESSION['level']['level']=='country'):?>
        		<?php if ($user->isAdministration()):?>
                	<?= $this->translate('There are no measures in your country.')?>
                <?php else:?>
               		<?= $this->translate('There are no measures in your country. Be the first to submit a missing measure.')?>
                <?php endif;?>
			<?php endif;?>
			</div>
		<!--/12-->
	</div>
	<!-- /row -->
                     
                    <?php endif;?>


        </div>
<!-- /jumbotron -->

        <script type="text/javascript">
		$(function () {
            	mesureAllMeasuresHandlers();
            });
        </script>