<!-- measure/all-measures -->

<?php 

    $level = $_SESSION['level']['level'];
    $levelValue = $_SESSION['level']['levelValue'];
    if ($level=='city') {
        $levelName = ($user->getCity()->getFullCity()?$user->getCity()->getFullCity()->getCityName().' <span class="small"><i>'.$user->getCity()->getDistrictName().'</i></span>':$user->getCity()->getCityName());
    }
    else if ($level=='region') {
        $levelName = $user->getCity()->getRegion()->getRegionName();
    }
    else if ($level=='country') {
        $levelName = '<img src="/img/flags/'.str_replace(' ', '-', $user->getCountry()->getCountryName()).'.png" style="margin-bottom: 4px;" width="20" height="14"> '.$user->getCountry()->getCountryName() .'</span>';
    }
    
?>

<?php $paging = $this->sortingDivPaginationHelper($pagedProposals, $page, $this->url('measure', array('action'=>'all-measures')), 'all-measures', $limit, $sort, $order); ?>
<div class="jumbotron parent" id="measure-all-measures"
	data-url="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>$sort, 'page'=>$page, 'order'=>$order, 'results' => $limit));?>"
	data-add-to-my-program="<?=$this->translate('Add to my Program')?>"
	data-add-favorite="<?=$this->translate('Add Favorite')?>"
	data-remove-favorite="<?=$this->translate('Remove Favorite')?>">
	<div class="row">
		<div class="col-md-8">
			<?php if ($user->getUsrId() && ($user->isCitizen() || ($user->isAdministration() && $user->getAdmin()->getAdminLevel() == $levelValue ))):?>
			<button type="button"
				data-url="<?= $this->url('measure', array('action'=>'add-measure')); ?>"
				class="btn btn-orange" id="measure-all-measures-add-new-measure"
				data-dialog-title="<?=$user->isAdministration()?$this->translate('New Official Measure for $level$'):$this->translate('Submit Official Measure for $level$')?>">
				<i class="fa fa-plus-circle"></i> 
                <?php if ($user->isAdministration()):?>
                <?= $this->translate('Create a new measure')?>
                <?php else:?>
                <?= $this->translate('Submit missing measure')?>
                <?php endif;?>
            </button>
            <?php elseif (!$user->getUsrId()):?>
				<?= $this->partial('partial/please-register-button.phtml', ['text' => '<i class="fa fa-plus-circle"></i> '.$this->translate('Submit missing measure')]); ?>
			<?php endif;?>	
			<span class="big"><?= sprintf($this->translate('%d Official Measures for <span id="level-name">%s</span>'), $proposalCount, $levelName)?></span>
		</div>
		<!-- /8 -->
		<div class="col-md-4">
			<div class="fltr">
				<ul class="nav">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-down"></i> </span>
							<!--  by <span class="caret"></span> -->
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'category', 'page'=>1, 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Category')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'name', 'page'=>1, 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Name')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'status', 'page'=>1, 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Status')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'user', 'page'=>1, 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Owner')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'page'=>1, 'sort'=>'votes', 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Number of Votes')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'page'=>1, 'sort'=>'vote-average', 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Vote average')?></a></li>
							<li class="divider"></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'page'=>1, 'sort'=>'published-date', 'order'=>'desc'));?>"><?= $this->translate('Published date')?></a></li>
						</ul></li>
				</ul>
			</div>
			<div class="fltr">
				<ul class="nav">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-up"></i> </span>
							<!-- by <span class="caret"></span> -->
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'category', 'page'=>1, 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Category')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'name', 'page'=>1, 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Name')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'status', 'page'=>1, 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Status')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'user', 'page'=>1, 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Owner')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'page'=>1, 'sort'=>'votes', 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Number of Votes')?></a></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'page'=>1, 'sort'=>'vote-average', 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Vote average')?></a></li>
							<li class="divider"></li>
							<li><a id="page-all-measures"
								href="<?= $this->url('measure', array('action'=>'all-measures', 'sort'=>'published-date', 'page'=>1, 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Published date')?></a></li>
						</ul></li>
				</ul>
			</div>
			<div class="fltr right10 top5"> <?= $this->translate('Sorted by')?> <?php if ($sort=='published-date'):?><?= $this->translate('Published date')?>
                    									<?php elseif ($sort=='votes'):?><?= $this->translate('Number of Votes')?>
                    									<?php elseif ($sort=='vote-average'):?><?= $this->translate('Vote average')?>
                    									<?php else:?><?=$this->translate(ucfirst($sort))?>
                    									<?php endif;?>  
                    <?=$order=='asc'?'<i class="fa fa-arrow-up"></i>':'<i class="fa fa-arrow-down"></i>'?></div>
		</div>
		<!--/6-->
	</div>
	<!-- /row -->
	<hr>

            <?php if(count($pagedProposals)>0):?>

                <?php foreach($pagedProposals as $index => $proposal): ?>
	<div class="table-layout">
		<div class="table-cell fixed-width-40">
			<img
				src="<?= $this->basePath()?>/files/<?= $proposal->getCat()->getCatImage() ?>"
				height="34" width="34"
				title="<?= $proposal->getCat()->getCatCat()->getCatName() ?>">
		</div>
		<div class="table-cell">
			<div class="row">
				<div class="col-md-4 col-xs-12">

<?php $proposalDescription = preg_replace('/<[^>]*>/', ' ', $proposal->getPropDescription());  
      $proposalDescription = (strlen($proposalDescription) > 150) ? substr($proposalDescription, 0, 150) . '...' : $proposalDescription;?>

<a
						href="<?= $this->url('measure', array('action'=>'view-measure', 'id'=>$proposal->getPropUUID()));?>"
						title="<?= $proposalDescription ?>" id="city-proposal-item"
						data-id="<?= $proposal->getPropUUID()?>"><span class="big"><?= $proposal->getPropSavedName() ?></span></a>
					<br />
<?= $this->translate('in')?> <?= $proposal->getCat()->getCatCat()->getCatName() ?> - <?= $proposal->getCat()->getCatName()?>
					<br />
					<!-- user -->
					<?= $this->translate('by')?> <a
						href="<?= $this->url('user/profile', array('action'=>'mini-profile', 'id'=>$proposal->getUsr()->getUsrUUID()));?>"
						data-title="<?= $proposal->getUsr()->getUsrName() ?>'s mini profile"
						data-id="<?=$proposal->getUsr()->getUsrUUID()?>"
						id="view-profile"> <span class="badge"><?= $proposal->getUsr()->getUsrName() ?></span></a>
					<span class="nobr"><i class="fa fa-clock-o"></i> <?= $proposal->getPropPublishedDate()?$proposal->getPropPublishedDate()->format('d/m/Y'):'' ?></span>
				</div>
				
				<?php if ($level=='country'):?>
    				<div class="col-md-5 col-xs-12">
    					<span class=""><?=$proposalDescription?></span>
    				</div>
				<?php else:?>
				<div class="col-md-3 col-xs-12">
					<?= $this->translate('Current Status')?>:<br /> 

<?= $this->{"status-$index"}?><br /> <?= $this->translate('Last updated')?> <span
						class="nobr"><i class="fa fa-clock-o"></i> <?= $proposal->getPropSavedDate()->format('d/m/Y')?> </span>
				</div>

				<?php $measure = $proposal->getMeasure();?>
				<div class="col-md-2 col-xs-12">        
					<?= $this->translate('Start')?>: <?=$measure->getMesStartDate()?$measure->getMesStartDate()->format('d/m/Y'):'Undefined'?> <br>
					<br>
					<?= $this->translate('Cost')?>: <?=$measure->getMesCost()?$measure->getMesCost().' '.$proposal->getCity()->getCountry()->getCountryCurrency():'Undefined'?>
				</div>
				<?php endif;?>

				<div class="col-md-3 col-xs-12">

<?= $this->{"status-details-$index"}?><br />
				</div>
			</div>
		</div>
		<div class="table-cell fixed-width-150 text-right">

<?php if ($user->getUsrId() && !$user->isAdministration()):?>
<a
				href="<?= $this->url('proposal', array('action'=>'favorite', 'id'=>$proposal->getPropUUID()));?>"
				alt="Favorite Proposal" id="measure-all-measures-favorite"
				data-favorite="<?= $proposal->getPropUUID()?>"><?php if (in_array($user, $proposal->getUsers())):?><i
				class="fa fa-heart"
				title="<?= $this->translate('Remove Favorite')?>"></i> <?= $this->translate('Remove Favorite')?><?php else:?><i
				class="fa fa-heart-o" title="<?= $this->translate('Add Favorite')?>"></i> <?= $this->translate('Add Favorite')?><?php endif;?></a> <br /> 
				
            <?= $this->partial('partial/add-proposal-to-program.phtml', ['proposal' => $proposal]); ?>
            				
<?php endif;?>
<a target="_parent"
				href="<?= $this->url('measure', array('action'=>'view-measure', 'id'=>$proposal->getPropUUID()));?>#comment-list"
				title="<?= $this->translate('Comments')?>"><i class="fa fa-comments"></i> <?= sprintf($this->translate('%d Comments'), count($proposal->getComments()))?></a>
		</div>
	</div>
	<hr />

                        <?php endforeach; ?>
<div class="row">
		<div class="col-md-12">
				<?= $paging; ?>
			</div>
		<!--/12-->
	</div>
	<!-- /row -->
                    <?php else:?>
<div class="row">
		<div class="col-md-12">
    		<?php if ($user->isAdministration()):?>
            	<?= $this->translate('There are no measures in your city.')?>
            <?php else:?>
           		<?= $this->translate('There are no measures in your city. Be the first to submit a missing measure.')?>
            <?php endif;?>
				
			</div>
		<!--/12-->
	</div>
	<!-- /row -->
                     
                    <?php endif;?>


        </div>
<!-- /jumbotron -->

<script type="text/javascript">
	$(function () {
    	mesureAllMeasuresHandlers();
    });
</script>

<!-- /measure/all-measures -->
        