
<?php $paging = $this->sortingDivPaginationHelper($pagedEvents, $page, $this->url('admin', array('action'=>'events')), 'events', $limit, $sort, $order); ?>
<div id="event-all-events"
	data-attend-event="<?= $this->translate('Attend Event')?>"
	data-attend-session="<?= $this->translate('Attend Session')?>"
	data-decline="<?= $this->translate('Cancel attendance')?>"
	data-url="<?=$this->url('admin', array('action'=>'events', 'sort'=>$sort, 'page'=>$page, 'order'=>$order, 'results' => $limit))?>">
	
	

	<div class="row top20">
		<div class="col-md-6"> 

      <span class="big"><?= sprintf($this->translate('%d Events'), $eventsCount)?> </span>
		</div>
		<div class="col-md-6">
			<div class="fltr">
				<ul class="nav">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-down"></i> </span>
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-all-events"
								href="<?= $this->url('admin', array('action'=>'events', 'sort'=>'name', 'page'=>1, 'order'=>'desc'), true);?>">

                <?=$this->translate('Name')?>

                </a></li>
							<li><a id="page-all-events"
								href="<?= $this->url('admin', array('action'=>'events', 'sort'=>'status', 'page'=>1, 'order'=>'desc'), true);?>">

                <?=$this->translate('Status')?>

                </a></li>
							<li class="divider"></li>
							<li><a id="page-all-events"
								href="<?= $this->url('admin', array('action'=>'events', 'sort'=>'start_date', 'page'=>1, 'order'=>'desc'), true);?>">

                <?=$this->translate('Start date')?>

                </a></li>
							<li><a id="page-all-events"
								href="<?= $this->url('admin', array('action'=>'events', 'sort'=>'end_date', 'page'=>1, 'order'=>'desc'), true);?>">

                <?=$this->translate('End date')?>

                </a></li>
						</ul></li>
				</ul>
			</div>
			<div class="fltr">
				<ul class="nav">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-up"></i> </span>
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-all-events"
								href="<?= $this->url('admin', array('action'=>'events', 'sort'=>'name', 'page'=>1, 'order'=>'asc'), true);?>">

                <?=$this->translate('Name')?>

                </a></li>
							<li><a id="page-all-events"
								href="<?= $this->url('admin', array('action'=>'events', 'sort'=>'status', 'page'=>1, 'order'=>'asc'), true);?>">

                <?=$this->translate('Status')?>

                </a></li>
							<li class="divider"></li>
							<li><a id="page-all-events"
								href="<?= $this->url('admin', array('action'=>'events', 'sort'=>'start_date', 'page'=>1, 'order'=>'asc'), true);?>">

                <?=$this->translate('Start date')?>

                </a></li>
							<li><a id="page-all-events"
								href="<?= $this->url('admin', array('action'=>'events', 'sort'=>'end_date', 'page'=>1, 'order'=>'asc'), true);?>">

                <?=$this->translate('End date')?>

                </a></li>
						</ul></li>
				</ul>
			</div>
			<div class="fltr right10 top5"><?= $this->translate('Sorted by')?>

        <?php if ($sort=='start_date'):?>

        <?=$this->translate('Start date')?>

        <?php elseif ($sort=='end_date'):?>

        <?=$this->translate('End date')?>

        <?php else:?>

        <?=$this->translate(ucfirst($sort))?>

        <?php endif;?>

        <?=$order=='asc'?'<i class="fa fa-arrow-up"></i>':'<i class="fa fa-arrow-down"></i>'?>

      </div>
		</div>
	</div>
	<hr>


	<?php if (count($pagedEvents)):?>


  <?php foreach ($pagedEvents as $event):?>






  <div class="row">

  <div class="col-xs-12 col-sm-12 col-md-5 wbr">

			<div class="pull-left" style="min-width: 80px!important">
			<img src="<?=$event->getEventImage()?$this->basePath($event->getEventImage()):$this->basePath('/img/events/noimage.png')?>"
				height="57" width="75" class="round5" title="<?=$event->getEventName()?>">
	  </div>
<div style="margin-left: 80px!important">
					<a
						href="<?= $this->url('event', array('action'=>'view-event', 'id'=> $event->getEventUUID()))?>"><span
						class="big">

          <?=$event->getEventName()?> <?=$event->getUsr()==$user?'(owner)':''?>

          </span></a> <br>

          <?php $eventDescription = preg_replace('/<[^>]*>/', ' ', $event->getEventDescription());

      $eventDescription = (strlen($eventDescription) > 150) ? substr($eventDescription, 0, 150) . '...' : $eventDescription;?>

          <?=$eventDescription?>
</div>
</div>

        <?php
$eventStartDate = $event->getEventStartDate();//->setTimezone(new DateTimeZone($user->getCity()->getRegion()->getRegionTimezone()));
$eventEndDate = $event->getEventEndDate();//->setTimezone(new DateTimeZone($user->getCity()->getRegion()->getRegionTimezone()));
$countryFormat = $event->getCity()->getCountry()->getCountryFormat();
?>
<div class="col-xs-12 col-sm-5 col-md-3">
	  					<span class="glyphicon glyphicon-calendar"></span>
					<?=$this->dateFormat(
                                            $eventStartDate,
                                            IntlDateFormatter::MEDIUM, // date
                                            IntlDateFormatter::SHORT, // time
            							    $countryFormat
                                        );?>
    						<i class="fa fa-arrow-right"></i>
    						<?=$eventEndDate->format('d/m/Y') == $event->getEventStartDate()->format('d/m/Y')?
    						      $this->dateFormat(
                                            $eventEndDate,
                                            IntlDateFormatter::NONE, // date
                                            IntlDateFormatter::SHORT, // time
                                            $countryFormat
                                        )
                                :
    						      $this->dateFormat(
                                            $eventEndDate,
                                            IntlDateFormatter::MEDIUM, // date
                                            IntlDateFormatter::SHORT, // time
                                            $countryFormat
                                        )?><br>
	  </div>
   <div class="col-xs-12 col-sm-4 col-md-2">
	  <i class="fa fa-map-marker"></i> <?=$event->getCity()->getCityName()?> (<?=$event->getCity()->getCityPostalcode()?>)<br>
	  <?=$event->getEventLocation()?>
	  </div>
    <div class="col-xs-12 col-sm-4 col-md-2 text-right text-xs-left">
	  <span class="right5"><a
						href="<?= $this->url('event', array('action'=>'view-event', 'id'=> $event->getEventUUID()))?>"
						id="event-all-events-view-attendees" title="<?=count($event->getAttendees())?> <?= $this->translate('Attendees')?>"><i class="fa fa-users size15em"></i> <span id="event-all-events-attendees-count"><?=count($event->getAttendees())?></span></a></span>




					<a
						href="<?= $this->url('event', array('action'=>'attend-event', 'id' => $event->getEventUUID()));?>"
						data-event="<?=$event->isSession()?'false':'true'?>"
						id="event-all-events-attend">


              <?php if (!$event->hasAttendee($user)):?>

                  		<i class="fa fa-check-circle-o size15em" title="<?= $event->isSession()?$this->translate('Attend Session'):$this->translate('Attend Event')?>"></i>

              <?php else:?>
    <i class="fa fa-times-circle size15em" title="<?= $this->translate('Cancel attendance')?>"></i><?php endif;?></a><br>



      <?php if ($event->getEventCanceledDate()):?>

      	 <span class="red"><strong><?= $this->translate('CANCELED')?></strong></span>

      <?php endif;?>
	  </div>
</div>


	<hr>





  <?php endforeach;?>

<div class="row">
		<div class="col-md-12">
				<?= $paging; ?>
			</div>
		<!--/12-->
	</div>
	<!-- /row -->


  <?php else:?>
  <div class="row">
		<div class="col-md-12">

            		<?=$this->translate('No events found.')?>

			</div>
		<!--/12-->
	</div>
	<!-- /row -->
	
  <?php endif;?>

  

   <?php $lang = $this->plugin('translate')->getTranslator()->getLocale();?>

  <script type="text/javascript">

$(function() {


	eventAllEventsHandlers('<?=$lang?>');

});



</script>
</div>
