
<?php $paging = $this->sortingDivPaginationHelper($pagedSessions, $page, $this->url('admin', array('action'=>'sessions')), 'sessions', $limit, $sort, $order); ?>
<div id="session-all-sessions"
	data-attend-session="<?= $this->translate('Attend session')?>"
	data-attend-session="<?= $this->translate('Attend Session')?>"
	data-decline="<?= $this->translate('Cancel attendance')?>"
	data-url="<?=$this->url('admin', array('action'=>'sessions', 'sort'=>$sort, 'page'=>$page, 'order'=>$order, 'results' => $limit))?>">
	
	

	<div class="row top20">
		<div class="col-md-6"> 

      <span class="big"><?= sprintf($this->translate('%d sessions'), $sessionsCount)?> </span>
		</div>
		<div class="col-md-6">
			<div class="fltr">
				<ul class="nav">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-down"></i> </span>
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-all-sessions"
								href="<?= $this->url('admin', array('action'=>'sessions', 'sort'=>'name', 'page'=>1, 'order'=>'desc'), true);?>">

                <?=$this->translate('Name')?>

                </a></li>
							<li><a id="page-all-sessions"
								href="<?= $this->url('admin', array('action'=>'sessions', 'sort'=>'status', 'page'=>1, 'order'=>'desc'), true);?>">

                <?=$this->translate('Status')?>

                </a></li>
							<li class="divider"></li>
							<li><a id="page-all-sessions"
								href="<?= $this->url('admin', array('action'=>'sessions', 'sort'=>'start_date', 'page'=>1, 'order'=>'desc'), true);?>">

                <?=$this->translate('Start date')?>

                </a></li>
							<li><a id="page-all-sessions"
								href="<?= $this->url('admin', array('action'=>'sessions', 'sort'=>'end_date', 'page'=>1, 'order'=>'desc'), true);?>">

                <?=$this->translate('End date')?>

                </a></li>
						</ul></li>
				</ul>
			</div>
			<div class="fltr">
				<ul class="nav">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-up"></i> </span>
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-all-sessions"
								href="<?= $this->url('admin', array('action'=>'sessions', 'sort'=>'name', 'page'=>1, 'order'=>'asc'), true);?>">

                <?=$this->translate('Name')?>

                </a></li>
							<li><a id="page-all-sessions"
								href="<?= $this->url('admin', array('action'=>'sessions', 'sort'=>'status', 'page'=>1, 'order'=>'asc'), true);?>">

                <?=$this->translate('Status')?>

                </a></li>
							<li class="divider"></li>
							<li><a id="page-all-sessions"
								href="<?= $this->url('admin', array('action'=>'sessions', 'sort'=>'start_date', 'page'=>1, 'order'=>'asc'), true);?>">

                <?=$this->translate('Start date')?>

                </a></li>
							<li><a id="page-all-sessions"
								href="<?= $this->url('admin', array('action'=>'sessions', 'sort'=>'end_date', 'page'=>1, 'order'=>'asc'), true);?>">

                <?=$this->translate('End date')?>

                </a></li>
						</ul></li>
				</ul>
			</div>
			<div class="fltr right10 top5"><?= $this->translate('Sorted by')?>

        <?php if ($sort=='start_date'):?>

        <?=$this->translate('Start date')?>

        <?php elseif ($sort=='end_date'):?>

        <?=$this->translate('End date')?>

        <?php else:?>

        <?=$this->translate(ucfirst($sort))?>

        <?php endif;?>

        <?=$order=='asc'?'<i class="fa fa-arrow-up"></i>':'<i class="fa fa-arrow-down"></i>'?>

      </div>
		</div>
	</div>
	<hr>


	<?php if (count($pagedSessions)):?>


  <?php foreach ($pagedSessions as $session):?>






  <div class="row">

  <div class="col-xs-12 col-sm-12 col-md-5 wbr">

			<div class="pull-left" style="min-width: 80px!important">
			<img src="<?=$session->getEventImage()?$this->basePath($session->getEventImage()):$this->basePath('/img/sessions/noimage.png')?>"
				height="57" width="75" class="round5" title="<?=$session->getEventName()?>">
	  </div>
<div style="margin-left: 80px!important">
					<a
						href="<?= $this->url('session', array('action'=>'view-session', 'id'=> $session->getEventUUID()))?>"><span
						class="big">

          <?=$session->getEventName()?> <?=$session->getUsr()==$user?'(owner)':''?>

          </span></a> <br>

          <?php $sessionDescription = preg_replace('/<[^>]*>/', ' ', $session->getEventDescription());

      $sessionDescription = (strlen($sessionDescription) > 150) ? substr($sessionDescription, 0, 150) . '...' : $sessionDescription;?>

          <?=$sessionDescription?>
</div>
</div>

        <?php
$sessionStartDate = $session->getEventStartDate();//->setTimezone(new DateTimeZone($user->getCity()->getRegion()->getRegionTimezone()));
$sessionEndDate = $session->getEventEndDate();//->setTimezone(new DateTimeZone($user->getCity()->getRegion()->getRegionTimezone()));
$countryFormat = $session->getCity()->getCountry()->getCountryFormat();
?>
<div class="col-xs-12 col-sm-5 col-md-3">
	  					<span class="glyphicon glyphicon-calendar"></span>
					<?=$this->dateFormat(
                                            $sessionStartDate,
                                            IntlDateFormatter::MEDIUM, // date
                                            IntlDateFormatter::SHORT, // time
            							    $countryFormat
                                        );?>
    						<i class="fa fa-arrow-right"></i>
    						<?=$sessionEndDate->format('d/m/Y') == $session->getEventStartDate()->format('d/m/Y')?
    						      $this->dateFormat(
                                            $sessionEndDate,
                                            IntlDateFormatter::NONE, // date
                                            IntlDateFormatter::SHORT, // time
                                            $countryFormat
                                        )
                                :
    						      $this->dateFormat(
                                            $sessionEndDate,
                                            IntlDateFormatter::MEDIUM, // date
                                            IntlDateFormatter::SHORT, // time
                                            $countryFormat
                                        )?><br>
	  </div>
   <div class="col-xs-12 col-sm-4 col-md-2">
	  <i class="fa fa-map-marker"></i> <?=$session->getCity()->getCityName()?> (<?=$session->getCity()->getCityPostalcode()?>)<br>
	  <?=$session->getEventLocation()?>
	  </div>
    <div class="col-xs-12 col-sm-4 col-md-2 text-right text-xs-left">
	  <span class="right5"><a
						href="<?= $this->url('session', array('action'=>'view-session', 'id'=> $session->getEventUUID()))?>"
						id="session-all-sessions-view-attendees" title="<?=count($session->getAttendees())?> <?= $this->translate('Attendees')?>"><i class="fa fa-users size15em"></i> <span id="session-all-sessions-attendees-count"><?=count($session->getAttendees())?></span></a></span>




					<a
						href="<?= $this->url('session', array('action'=>'attend-session', 'id' => $session->getEventUUID()));?>"
						data-session="<?=$session->isSession()?'false':'true'?>"
						id="session-all-sessions-attend">


              <?php if (!$session->hasAttendee($user)):?>

                  		<i class="fa fa-check-circle-o size15em" title="<?= $session->isSession()?$this->translate('Attend Session'):$this->translate('Attend session')?>"></i>

              <?php else:?>
    <i class="fa fa-times-circle size15em" title="<?= $this->translate('Cancel attendance')?>"></i><?php endif;?></a><br>



      <?php if ($session->getEventCanceledDate()):?>

      	 <span class="red"><strong><?= $this->translate('CANCELED')?></strong></span>

      <?php endif;?>
	  </div>
</div>


	<hr>





  <?php endforeach;?>

<div class="row">
		<div class="col-md-12">
				<?= $paging; ?>
			</div>
		<!--/12-->
	</div>
	<!-- /row -->


  <?php else:?>
  <div class="row">
		<div class="col-md-12">

            		<?=$this->translate('No sessions found.')?>

			</div>
		<!--/12-->
	</div>
	<!-- /row -->
	
  <?php endif;?>

  



  <script type="text/javascript">

$(function() {


	adminSessionsHandlers();

});



</script>
</div>
