<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>DEMODYNE -
<?= $this->translate('Shape Your Society')?>
</title>
<link rel="icon" href="<?= $this->basePath('img/favicon.ico') ?>" type="image/x-icon">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<link href="/homepage/font-awesome-4.5.0/css/font-awesome.css" rel="stylesheet" />
<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
<link href="/homepage/homepage.css" rel="stylesheet" />
<link href="/homepage/animate.css" rel="stylesheet" />
</head>

<body>
<?php

$lang = $this->plugin('translate')->getTranslator()->getLocale();

$language = ($lang=='en')?['United-Kingdom', 'English']:

(($lang=='fr')?['France', 'Français']:

(($lang=='it')?['Italy', 'Italiano']:

(($lang=='de')?['Germany', 'Deutsch']:

(($lang=='ro')?['Romania', 'Română']:

['United-Kingdom', 'English']))));

?>

<!-- LANGUAGES -->

<nav class="mainmenu">
  <div class="languages">
    <div class="dropdown">
      <button type="button" class="navbar-toggle" data-toggle="dropdown"> <img src="<?= $this->basePath('img/flags/'.$language[0].'.png') ?>" width="25" height="17" alt="<?= $language[1]?>"/></button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li><a href="<?=$this->url('home', [], array(  'query' => array( 'lang' => 'en')))?>"><img src="<?= $this->basePath('img/United-Kingdom.png') ?>" width="25" height="17" alt="English"/> EN</a></li>
        <li><a href="<?=$this->url('home', [], array(  'query' => array( 'lang' => 'fr')))?>"><img src="<?= $this->basePath('img/France.png') ?>" width="25" height="17" alt="Français"/> FR</a></li>

        <!-- <li><a href="<?=$this->url('home', [], array(  'query' => array( 'lang' => 'de')))?>"><img src="/img/Germany.png" width="25" height="17" alt="Deutsch"/> DE</a></li>

<li><a href="<?=$this->url('home', [], array(  'query' => array( 'lang' => 'it')))?>"><img src="/img/Italy.png" width="25" height="17" alt="Italiano"/> IT</a></li> -->

      </ul>
    </div>
  </div>
</nav>
<section id="top"></section>
<div class="container-vertical">
  <div class="vertical">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2 class="shadow" style="margin-bottom:5px !important;">
          <?= $this->translate('CITIZENS WITH IDEAS?')?>
        </h2>
        <hr class="orange">
        <p><img class="imgfade" src="<?= $this->basePath('img/logo-vertical.png') ?>" width="300" height="135" title="DEMODYNE - Shape your Society" /></p>
        <hr class="orange">
        <h2 class="shadow">
          <?= $this->translate('SHAPE YOUR SOCIETY')?>
        </h2>
        <center>
          <?php

$loginForm = $this->loginForm;

if ($redirect) $loginForm->setAttribute('action', $this->url('home/login', array('action' => 'login'),  array(  'query' => array( 'redirect' => $redirect)), true));

else $loginForm->setAttribute('action', $this->url('home/login', array('action' => 'login'),true));

$loginForm->prepare();

?>
          <?= $this->form()->openTag($loginForm);?>
          <div style="border-radius: 5px; color:#000000; font-size:1em; width:170px;padding-bottom:5px;">
            <?= $this->formElement($loginForm->get('username'));?>
          </div>

          <div style="border-radius: 5px; color:#000000; font-size:1em; width:170px;padding-bottom:5px;">
            <?= $this->formElement($loginForm->get('password'));?>
          </div>

          <?php if ($error):?>
          	<span class="label label-danger size1em"><?=$this->translate('Supplied credential is invalid.')?></span>
          	<?php endif;?>

          <div class="top5">
          <button type="submit" class="btn btn-orange" style="width:170px;">
          <?= $this->translate('Login') ?>
          </button>
          </div>
          <br />
          <?= $this->formElement($loginForm->get('rememberme'));?>
          <a href="<?= $this->url('home/user-register', array('action' => 'forgotten-password'), true);?>" style="color:#ffcc00;font-size:1em;">
          <?= $this->translate('Forgot your password?') ?>
          </a>
          <?=  $this->form()->closeTag();?>
        </center>
      </div>
    </div>
    <!-- //row -->

  </div>
</div>
<!-- //container -->

<div id="notvisible"> <a href="#go" class="more scrolly">
  <?= $this->translate('Discover')?>
  &amp; <span style="color:#FFC600;">
  <?= $this->translate('Register')?>
  </span><br>
  <i class="fa fa-arrow-down shadow"></i> </a> </div>

<!-- VIDEO & REGISTER -->

<section id="go">
  <div class="container-fluid maro">
    <div class="row">
      <div class="col-md-2 col-xs-0"></div>
      <div class="col-md-4 col-xs-12">
        <h3 class="orange bot10">
          <?= $this->translate('What is DEMOCRACY?')?>
        </h3>
        <p>
          <?= $this->translate('Is it just picking a name every 4 or 5 years and being left out of all decisions the rest of the time? Is it just choosing between two fixed lists of measures from party A and party B, while actually agreeing with neither? Now imagine democracy was invented today, in an age of seamless communication and instant data sharing. Do you think it would work like this?')?>
        </p>
        <p>
          <?= $this->translate('We are the <span class="orange shadow">DEMODYNE Team</span>, and we believe DEMOCRACY should mean much more.')?>
        </p>

	<div class="bot20">
    <div class="embed-responsive embed-responsive-16by9">
		<iframe src="https://player.vimeo.com/video/165296374" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    </div>
    </div>


      </div>
      <div class="col-md-4 col-xs-12">
        <h3 class="orange bot10">
          <?= $this->translate('Register with DEMODYNE')?>
        </h3>
        <div class="row bot20">
          <div class="col-lg-2 col-md-3 col-xs-2"> <span style="color:#fdfdfd;"> <a href="<?= $this->url('home/administration-register');?>"><i class="fa fa-university custom-icon"></i> </a> </span> </div>
          <div class="col-lg-10 col-md-9 col-xs-10">
            <h4 class="orange" style="margin-bottom:1px !important;">
              <?= $this->translate('Administration')?>
            </h4>
            <?= $this->translate('Public Administration looking to move things forward?')?>
          </div>
        </div>
        <div class="row bot20">
          <div class="col-lg-2 col-md-3 col-xs-2"> <span style="color:#fdfdfd;"> <a href="<?= $this->url('home/user-register');?>"><i class="fa fa-bullhorn custom-icon"></i> </a> </span> </div>
          <div class="col-lg-10 col-md-9 col-xs-10">
            <h4 class="orange" style="margin-bottom:1px !important;">
              <?= $this->translate('Citizen')?>
            </h4>
            <?= $this->translate('Citizen with ideas for better future?')?>
          </div>
        </div>
        <div class="row bot10">
          <div class="col-lg-2 col-md-3 col-xs-2"> <span style="color:#fdfdfd;"> <a href="<?= $this->url('home/partner-register');?>"><i class="fa fa-industry custom-icon"></i> </a> </span> </div>
          <div class="col-lg-10 col-md-9 col-xs-10">
            <h4 class="orange" style="margin-bottom:1px !important;">
              <?= $this->translate('Partner')?>
            </h4>
            <?= $this->translate('Association / Company / Entrepreneur willing to do business?')?>
          </div>
        </div>



        <div class="row">
          <div class="col-lg-2 col-md-3 col-xs-2"> <span style="color:#fdfdfd;"> <a href="<?=$this->url('browse', ['country'=> 'france'])?>" id="layout-browse"><i class="fa fa-search custom-icon"></i> </a> </span> </div>
          <div class="col-lg-10 col-md-9 col-xs-10"><hr class="orangeleft topm10" style="width:100% !important;">
            <h4 class="orange" style="margin-bottom:1px !important;">
              <?= $this->translate('Browse')?>
            </h4>
            <?= $this->translate('Discover DEMODYNE system')?>
          </div>
        </div>



      </div>
      <div class="col-md-2 col-xs-0"></div>
    </div>
  </div>
</section>







<!-- FOOTER -->

<section id="go">
  <div class="container-fluid darkmaro">






    <div class="row">
      <div class="col-md-3 col-xs-1"></div>
      <div class="col-md-6 col-xs-12 text-center shadow">



          <h3 class="orange bot10">
          <?= $this->translate('Our Partners')?>
        </h3>
        <?= $this->translate('Member of')?><br><a href="http://democratieouverte.org" target="_blank"><img src="<?= $this->basePath('img/logo-do-250x70.jpg') ?>" width="250" height="70" title="Democratie ouverte" /></a>

        <hr class="orange topm20" style="width:100% !important;">

        <h3 class="orange top20 bot10">
          <?= $this->translate('About DEMODYNE')?>
        </h3>
        <div class="row">
          <div class="col-md-3 col-sm-3 col-xs-6 bot10"> <a href="http://forum.demodyne.org/showthread.php?tid=6" target="_blank"><!--<a href="/pages">--><i class="fa fa-info-circle fa-2x"></i><br>
            <span class="big">
            <?= $this->translate('About us')?>
            </span></a> </div>
          <div class="col-md-3 col-sm-3 col-xs-6 bot10"> <a href="https://www.vimeo.com/demodyne" target="_blank"><i class="fa fa-film fa-2x"></i><br>
            <span class="big">
            <?= $this->translate('Video & Tutorials')?>
            </span></a> </div>
          <div class="col-md-3 col-sm-3 col-xs-6 bot10"> <a href="http://forum.demodyne.org" target="_blank"><i class="fa fa-comments-o fa-2x"></i><br>
            <span class="big">Forum</span></a> </div>
          <div class="col-md-3 col-sm-3 col-xs-6 bot10"> <a href="/page/support"><i class="fa fa-rocket fa-2x"></i><br>
            <span class="big">
            <?= $this->translate('Support us!')?>
            </span></a> </div>
        </div>
        <hr class="orange topm20" style="width:100% !important;">
        <div class="row text-center top20">
          <div class="col-md-12">
            <?= $this->translate('You can find us on:')?>
            <br>
            <a href="https://www.facebook.com/demodyne.official" target="_blank"><i class="fa fa-facebook fa-2x shadow padding20"></i></a>&nbsp; <a href="https://www.linkedin.com/company/demodyne" target="_blank"><i class="fa fa-linkedin fa-2x shadow padding20"></i></a>&nbsp; <a href="https://twitter.com/demodyne" target="_blank"><i class="fa fa-twitter fa-2x shadow padding20"></i></a>&nbsp;
            <p>
              <?= $this->translate('or you can reach us by email at')?>
              <a href="mailto:contact@demodyne.org" class="orange">contact (at) demodyne.org</a></p>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-xs-1"></div>
    </div>
    <div class="row">
      <div class="col-md-3 col-xs-1"></div>
      <div class="col-md-6 col-xs-10 small shadow">
        <hr class="orange topm20" style="width:100% !important;">
        <div class="row top20">
          <div class="col-md-6 col-xs-6"> © 2015 - 2016 DEMODYNE<br>
            <?= $this->translate('All rights reserved')?>
          </div>
          <div class="col-md-6 col-xs-6 text-right">
          <a href="/page/legal"><?= $this->translate('Legal')?><br>
          <a href="https://forum.demodyne.org/showthread.php?tid=8" target="_blank">
            <?= $this->translate('Terms & Conditions')?>
            </a></div>
        </div>
      </div>
      <div class="col-md-3 col-xs-1"></div>
    </div>
    <div class="row top20 margintop70">
      <div class="col-md-12 text-center"> <a href="#top" class="more scrolly"><i class="fa fa-arrow-up shadow"></i><br>
        <span class="orange">Top</span></a> </div>
    </div>
  </div>
</section>
<script src="/js/jquery-2.1.3.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script>

$('#layout-browse').popover({ 
 	trigger: "manual" , 
 	html: true, 
 	placement: 'auto',
 	container: 'body',
 	animation:false, 
 	content: function(){
 		
 		if (!$('#layout-browse-content').length) {
    		$('<div id="layout-browse-content" style="display:none">')
		        .html('Loading...')
		        .appendTo('body'); 
    		$.ajax({
	            url: $('#layout-browse').attr('href'),
	            success: function(response){
	                $('#layout-browse-content').html(response);
	                //$('.popover-content').html(response);
	                $('#layout-browse').popover("show");
	            }
	        });
    	}
    	return $('#layout-browse-content').html();
    	
//         return profileDetailsInPopup($(this), $(this).data('id'));
 	}
 })
//	.on("mouseenter", function () {
	.on("click", function () {
// 		console.log('pop');
	    var _this = this;
// 	    $('.popover').popover('hide');
	    $(this).popover("show");
	    return false;
//	    $(".popover").on("mouseleave", function () {
//	        $(_this).popover('hide');
//	    });
	})
//	.on("mouseleave", function () {
//	    var _this = this;
//	    setTimeout(function () {
//	        if (!$(".popover:hover").length) {
//	            $(_this).popover("hide");
//	        }
//	    }, 300);
//	})
	;
//	.on("click", function () {
// 	return false;
//	});
	
	$('body').on('click', function (e) {
	    //only buttons
	    if (!$(e.target).parent().hasClass('mini-profile')
	        && $(e.target).parents('.popover.in').length === 0) { 
	    	$('#layout-browse').popover('hide');
	    }
//	    console.log(e.target);
	    //buttons and icons within buttons
	    /*
	    if ($(e.target).data('toggle') !== 'popover'
	        && $(e.target).parents('[data-toggle="popover"]').length === 0
	        && $(e.target).parents('.popover.in').length === 0) { 
	        $('[data-toggle="popover"]').popover('hide');
	    }
	    */
	});

  	/* Smooth Scrolling

  	------------------------------------------------------ */

  	$('.scrolly').on('click', function (e) {



	 	e.preventDefault();



   	var target = this.hash,

    	$target = $(target);



    	$('html, body').stop().animate({

       	'scrollTop': $target.offset().top

      }, 800, 'swing', function () {

      	window.location.hash = target;

      });



  	});

	</script>
</body>
</html>
