<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>DEMODYNE -
<?= $this->translate('Shape Your Society')?>
</title>
<link rel="icon" href="<?= $this->basePath('img/favicon.ico') ?>" type="image/x-icon">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<link href="/homepage/font-awesome-4.5.0/css/font-awesome.min.css" rel="stylesheet" />
<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
<link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css" media="screen" rel="stylesheet" type="text/css">
<link href="/homepage/homepage.css" rel="stylesheet" />
<link href="/homepage/animate.css" rel="stylesheet" />
<meta property="og:image" content="https://www.demodyne.org/img/demodyne-facebook-square.png">
</head>

<body>

<!-- LANGUAGES -->

<nav class="mainmenu">
  <div class="languages">
    <div class="dropdown">
      <button type="button" class="navbar-toggle" data-toggle="dropdown"> <img src="<?= $this->basePath('img/flags/'.$currentLanguage->getLangFlag().'.png') ?>" width="25" height="17" alt="<?= $currentLanguage->getLangName()?>"/></button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
      	<?php foreach ($languages as $language):?>
									<li><a
										href="<?= $this->url($this->route, [], ['query' => array( 'lang' => $language->getLangId())]); ?>">
											<img
    											src="<?= $this->basePath('img/flags/'.$language->getLangFlag().'.png') ?>"
    											valign="middle" width="25" height="17" alt="<?=$language->getLangFlag()?>" />
											<?=strtoupper($language->getLangId())?>
									</a></li>
		<?php endforeach;?>

      </ul>
    </div>
  </div>
</nav>
<section id="top"></section>
<div class="container-vertical">
  <div class="vertical">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2 class="shadow" style="margin-bottom:5px !important;">
          <?= $this->translate('CITIZENS WITH IDEAS?')?>
        </h2>
        <hr class="orange">
        <p><img class="imgfade" src="<?= $this->basePath('img/logo-vertical.png') ?>" width="300" height="135" title="DEMODYNE - Shape your Society" /></p>
        <hr class="orange">
        <h2 class="shadow">
          <?= $this->translate('SHAPE YOUR SOCIETY')?>
        </h2>
        <center>
          <?php

$loginForm = $this->loginForm;

if ($redirect) $loginForm->setAttribute('action', $this->url('home/login', array('action' => 'login'),  array(  'query' => array( 'redirect' => $redirect)), true));

else $loginForm->setAttribute('action', $this->url('home/login', array('action' => 'login'),true));

$loginForm->prepare();

?>
          <?= $this->form()->openTag($loginForm);?>
          <div style="border-radius: 5px; color:#000000; font-size:1em; width:170px;padding-bottom:5px;">
            <?= $this->formElement($loginForm->get('username'));?>
          </div>

          <div style="border-radius: 5px; color:#000000; font-size:1em; width:170px;padding-bottom:5px;">
            <?= $this->formElement($loginForm->get('password'));?>
          </div>

          <?php if ($error && !$facebook):?>
          	<span class="label label-danger size1em"><?=$errorMessage?></span>
          	<?php endif;?>

          <div class="top5">
          <button type="submit" class="btn btn-orange" style="width:170px;">
          <?= $this->translate('Login') ?>
          </button>
          </div>


          <a href="<?= $this->url('home/user-register', array('action' => 'forgotten-password'), true);?>" style="color:#ffcc00;font-size:1em;">
          <?= $this->translate('Forgot your password?') ?>
          </a>


          <br><br>
<a href="<?= $this->url('home/login', array('action' => 'facebook-login'), true);?>" id="facebook-login" data-dialog-title="<?=$this->translate('Login with Facebook')?>">
			<img alt="<?=$this->translate('Login with Facebook')?>" src="<?=$this->basePath('/img/login-facebook-'.$currentLanguage->getLangId().'.png')?>"></a>
		<br>
          <?php if ($error && $facebook):?>
          	<span class="label label-danger size1em"><?=$this->translate('You are not registered with your Facebook account.')?></span>
          	<?php endif;?>


          <?=  $this->form()->closeTag();?>
        </center>
      </div>
    </div>
    <!-- //row -->

  </div>
</div>
<!-- //container -->

<div id="notvisible"> <a href="#go" class="more scrolly">
  <?= $this->translate('Discover')?>
  &amp; <span style="color:#FFC600;">
  <?= $this->translate('Register')?>
  </span><br>
  <i class="fa fa-arrow-down shadow"></i> </a> </div>

<!-- VIDEO & REGISTER -->

<section>
  <div class="container-fluid maro">
    <div class="row">
      <div class="col-md-2 col-xs-0"></div>
      <div class="col-md-4 col-xs-12">
        <h3 class="orange bot10">
          <?= $this->translate('What is DEMOCRACY?')?>
        </h3>
        <p>
          <?= $this->translate('Is it just picking a name every 4 or 5 years and being left out of all decisions the rest of the time? Is it just choosing between two fixed lists of measures from party A and party B, while actually agreeing with neither? Now imagine democracy was invented today, in an age of seamless communication and instant data sharing. Do you think it would work like this?')?>
        </p>
        <p>
          <?= $this->translate('We are the <span class="orange shadow">DEMODYNE Team</span>, and we believe DEMOCRACY should mean much more.')?>
        </p>

	<div class="bot20">


    <?= $this->partial('dgi-module/pages/homepage-'.$currentLanguage->getLangId().'.phtml'); ?>

    </div>


      </div>
      <div class="col-md-4 col-xs-12" id="pageContent">
        <h3 class="orange bot10" id="go">
          <?= $this->translate('Register with DEMODYNE')?>
        </h3>
        <div class="row bot20">
          <div class="col-lg-2 col-md-3 col-xs-3"> <span style="color:#fdfdfd;"> <a href="<?= $this->url('home/administration-register');?>"><i class="fa fa-university custom-icon"></i> </a> </span> </div>
          <div class="col-lg-10 col-md-9 col-xs-9">
            <h4 class="orange" style="margin-bottom:1px !important;">
              <?= $this->translate('Administration')?>
            </h4>
            <?= $this->translate('Public Administration looking to move things forward?')?>
          </div>
        </div>
					<div class="row bot20">
						<div class="col-lg-2 col-md-3 col-xs-3">
							<span style="color: #fdfdfd;"> <a id="homepage-user-registration"
								href="<?= $this->url('home/user-register');?>"
								data-dialog-title="<?=$this->translate('Register as Citizen on Demodyne')?>">
								<i class="fa fa-bullhorn custom-icon"></i></a>
							</span>
						</div>
						<div class="col-lg-10 col-md-9 col-xs-9">
							<h4 class="orange" style="margin-bottom: 1px !important;">
              <?= $this->translate('Citizen')?>
            </h4>
            <?= $this->translate('Citizen with ideas for better future?')?>
          </div>
        </div>
        <div class="row bot10">
          <div class="col-lg-2 col-md-3 col-xs-3"> <span style="color:#fdfdfd;"> <a href="<?= $this->url('home/partner-register');?>"><i class="fa fa-industry custom-icon"></i> </a> </span> </div>
          <div class="col-lg-10 col-md-9 col-xs-9">
            <h4 class="orange" style="margin-bottom:1px !important;">
              <?= $this->translate('Partner')?>
            </h4>
            <?= $this->translate('Association / Company / Entrepreneur willing to do business?')?>
          </div>
        </div>



        <div class="row">
          <div class="col-lg-2 col-md-3 col-xs-3"> <span style="color:#fdfdfd;"> <a href="<?=$this->url('browse', ['action'=> 'browse-dialog'])?>" data-dialog-title="<?=$this->translate('Browse Demodyne')?>"
					id="layout-browse"><i class="fa fa-search custom-icon"></i> </a> </span> </div>
          <div class="col-lg-10 col-md-9 col-xs-9"><hr class="orangeleft topm10" style="width:100% !important;">
            <h4 class="orange" style="margin-bottom:1px !important;">
              <?= $this->translate('Browse')?>
            </h4>
            <?= $this->translate('Discover DEMODYNE, the platform for direct citizen governance and collaborative construction of citizens program')?>
          </div>
        </div>



      </div>
      <div class="col-md-2 col-xs-0"></div>
    </div>
  </div>
</section>







<!-- FOOTER -->

<section>
  <div class="container-fluid darkmaro">






    <div class="row">
      <div class="col-md-3 col-xs-1"></div>
      <div class="col-md-6 col-xs-12 text-center shadow">



          <h3 class="orange bot10">
          <?= $this->translate('Our Partners')?>
        </h3>

        <div class="row">
		<div class="col-md-4 text-center"><?= $this->translate('Member of')?><br></div>
		<div class="col-md-4 text-center"></div>
		<div class="col-md-4 text-center"></div>
        </div>

        <div class="row">
		<div class="col-md-4 text-center bot5"><a href="http://democratieouverte.org" target="_blank"><img src="<?= $this->basePath('img/democratie-ouverte.jpg') ?>" width="206" height="70" title="Democratie ouverte" /></a></div>
		<div class="col-md-4 text-center bot5"><a href="https://visionspol.eu" target="_blank"><img src="<?= $this->basePath('img/visions.jpg') ?>" width="206" height="70" title="VISIONS" /></a></div>
      
       <div class="col-md-4 text-center"><a href="http://rectangleblanc.zici.fr/accueil.html" target="_blank"><img src="<?= $this->basePath('img/rectangle-blanc.png') ?>" width="206" height="70" title="RECTANGLE BLANC" /></a></div>

        </div>
		<br>
        <hr class="orange topm20" style="width:100% !important;">

        <h3 class="orange top20 bot10">
          <?= $this->translate('About DEMODYNE')?>
        </h3>
        <?php
                            if ($currentLanguage->getLangId()=='fr') {
                                $aboutUsLink = 'https://forum.demodyne.org/showthread.php?tid=231';
                                $supportUsLink = 'https://forum.demodyne.org/showthread.php?tid=9';
                                $forumLink = 'https://forum.demodyne.org';
                            }
                            elseif ($currentLanguage->getLangId()=='ro') {
                                $aboutUsLink = 'https://forum.demodyne.org/showthread.php?tid=28';
                                $supportUsLink = 'https://forum.demodyne.org/showthread.php?tid=27';
                                $forumLink = 'https://forum.demodyne.org/forumdisplay.php?fid=12';
                            }
                            else {
                                $aboutUsLink = 'http://forum.demodyne.org/showthread.php?tid=230';
                                $supportUsLink = 'https://forum.demodyne.org/showthread.php?tid=9';
                                $forumLink = 'https://forum.demodyne.org';
                            }

                        ?>
        <div class="row">
          <div class="col-md-3 col-sm-3 col-xs-6 bot10"> <a href="<?=$this->url('home/pages', ['page'=>'about']);?>" target="_blank">
			  <img class="icon" src="/img/icons-site-about.svg" title="<?= $this->translate('About us')?>"><br>
            <h5 class="big"><?= $this->translate('About us')?></h5></a> </div>
          <div class="col-md-3 col-sm-3 col-xs-6 bot10"> <a href="https://www.vimeo.com/demodyne" target="_blank">
			  <img class="icon" src="/img/icons-site-video.svg" title="<?= $this->translate('Videos & Tutorials')?>"><br>
								<h5 class="big"><?= $this->translate('Videos & Tutorials')?></h5></a> </div>
          <div class="col-md-3 col-sm-3 col-xs-6 bot10"> <a href="<?=$forumLink?>" target="_blank">
			  <img class="icon" src="/img/icons-site-forum.svg" title="<?= $this->translate('Forum')?>"><br>
								<h5 class="big"><?= $this->translate('Forum')?></h5></a> </div>
          <div class="col-md-3 col-sm-3 col-xs-6 bot10"> <a href="<?=$this->url('home/pages', ['page'=>'support']);?>" target="_blank">
			  <img class="icon" src="/img/icons-site-support.svg" title="<?= $this->translate('Support us')?>"><br>
								<h5 class="big"><?= $this->translate('Support us')?>!</h5></a> </div>
        </div>
        <hr class="orange topm20" style="width:100% !important;">
        <div class="row text-center top20">
          <div class="col-md-12">
            <?= $this->translate('You can find us on:')?>
            <br>
            <a href="https://www.facebook.com/demodyne" target="_blank"><i class="fa fa-facebook fa-2x shadow padding20"></i></a>&nbsp; <a href="https://www.linkedin.com/company/demodyne" target="_blank"><i class="fa fa-linkedin fa-2x shadow padding20"></i></a>&nbsp; <a href="https://twitter.com/demodyne" target="_blank"><i class="fa fa-twitter fa-2x shadow padding20"></i></a>&nbsp;
            <p>
              <?= $this->translate('or you can reach us by email at')?>
              <a href="mailto:contact@demodyne.org" class="orange">contact (at) demodyne.org</a></p>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-xs-1"></div>
    </div>
    <div class="row">
      <div class="col-md-3 col-xs-1"></div>
      <div class="col-md-6 col-xs-10 small shadow">
        <hr class="orange topm20" style="width:100% !important;">
        <div class="row top20">
          <div class="col-md-6 col-xs-6"> © 2015 - 2016 DEMODYNE<br>
            <?= $this->translate('All rights reserved')?>
          </div>
          <div class="col-md-6 col-xs-6 text-right">
          <a href="/page/legal"><?= $this->translate('Legal')?><br>
          <?php if ($currentLanguage->getLangId()=='en')
                    $link = 'https://forum.demodyne.org/showthread.php?tid=4';
                elseif ($currentLanguage->getLangId()=='fr')
                    $link = 'https://forum.demodyne.org/showthread.php?tid=8';
                elseif ($currentLanguage->getLangId()=='ro')
                    $link = 'https://forum.demodyne.org/showthread.php?tid=26';

              ?>
          <a href="<?=$this->url('home/pages', ['page'=>'terms']);?>" target="_blank">
            <?= $this->translate('Terms & Conditions')?>
            </a></div>
        </div>
      </div>
      <div class="col-md-3 col-xs-1"></div>
    </div>
    <div class="row top20 margintop70">
      <div class="col-md-12 text-center"> <a href="#top" class="more scrolly"><i class="fa fa-arrow-up shadow"></i><br>
        <span class="orange">Top</span></a> </div>
    </div>
  </div>
</section>
<script src="/js/jquery-2.1.3.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script type="text/javascript" src="/jqueryUI/jquery-ui.min.js"></script>
<script type="text/javascript" src="/js/demodyne.common.js"></script>
<script type="text/javascript" src="/js/demodyne.js"></script>
<script type="text/javascript">

$(function() {

});

</script>
<script>


  	/* Smooth Scrolling

  	------------------------------------------------------ */

  	$('.scrolly').on('click', function (e) {



	 	e.preventDefault();



   	var target = this.hash,

    	$target = $(target);



    	$('html, body').stop().animate({

       	'scrollTop': $target.offset().top

      }, 800, 'swing', function () {

      	window.location.hash = target;

      });



  	});

	</script>

	<script type="text/javascript">

	window.fbAsyncInit = function() {
	      FB.init({
	        appId      : '220020655059875',
	        cookie     : true,  // enable cookies to allow the server to access
	        status     : true,       // the session
	        xfbml      : true,  // parse social plugins on this page
	        version    : 'v2.7' // use graph api version 2.5
	      });

	    };

	 // Load the SDK asynchronously
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));


	$(function() {



	$('#facebook-login').click(function() {

		FB.login(function(response){
			if (response.status === 'connected') {
			      // Logged into your app and Facebook.
				window.location = $('#facebook-login').attr('href');
		    } else if (response.status === 'not_authorized') {
			      // The person is logged into Facebook, but not your app.
//			       document.getElementById('status').innerHTML = 'Please log ' +
//			         'into this app.';
			    } else {
			      // The person is not logged into Facebook, so we're not sure if
			      // they are logged into this app or not.
//			       document.getElementById('status').innerHTML = 'Please log ' +
//			         'into Facebook.';
			    }
			}, {scope: 'public_profile,email,user_location,user_birthday'});
		return false;
	});

});
</script>
</body>
</html>
