<?php
if ($currentLanguage->getLangId()=='fr') {
    $aboutUsLink = 'https://forum.demodyne.org/showthread.php?tid=231';
    $supportUsLink = 'https://forum.demodyne.org/showthread.php?tid=9';
    $forumLink = 'https://forum.demodyne.org';
}
elseif ($currentLanguage->getLangId()=='ro') {
    $aboutUsLink = 'https://forum.demodyne.org/showthread.php?tid=28';
    $supportUsLink = 'https://forum.demodyne.org/showthread.php?tid=27';
    $forumLink = 'https://forum.demodyne.org/forumdisplay.php?fid=12';
}
else {
    $aboutUsLink = 'http://forum.demodyne.org/showthread.php?tid=230';
    $supportUsLink = 'https://forum.demodyne.org/showthread.php?tid=9';
    $forumLink = 'https://forum.demodyne.org';
}

?>



<div class="jumbotron-mobile round5top" id="logged-in">



    <div class="row">
        <div class="col-md-12  col-xs-12 ">





            <?php if ($user->isAdministration()):?>
                <?= $this->partial('administration-steps.mobile.phtml', array('user' => $user)); ?>
            <?php else:?>
                <?= $this->partial('user-steps.mobile.phtml', array('user' => $user, 'count'=>$count)); ?>
            <?php endif;?>








            <!--<div class="row">
                <div class="col-xs-3 text-center">
                    <a href="<?=$this->url('home/pages', ['page'=>'about']);?>" class="gray">
                        <img class="icon" src="/img/icons-site-about.svg" title="<?= $this->translate('About us')?>"><br>
                        <?= $this->translate('About us')?></a>
                </div>
                <div class="col-xs-3 text-center">
                    <a
                            href="https://www.vimeo.com/demodyne" class="gray">
                        <img class="icon" src="/img/icons-site-video.svg" title="<?= $this->translate('Videos & Tutorials')?>"><br>
                        <?= $this->translate('Videos & Tutorials')?></a>
                </div>
                <div class="col-xs-3 text-center">
                    <a href="<?=$forumLink?>" class="gray" target="_blank">
                        <img class="icon" src="/img/icons-site-forum.svg" title="<?= $this->translate('Forum')?>"><br>
                        <?= $this->translate('Forum')?></a>
                </div>
                <div class="col-xs-3 text-center">
                    <a href="<?=$this->url('home/pages', ['page'=>'support']);?>" class="gray">
                        <img class="icon" src="/img/icons-site-support.svg" title="<?= $this->translate('Support us')?>"><br>
                        <?= $this->translate('Support us')?>!</a>
                </div>
            </div>-->
            <!-- /row -->
        </div><!--/col-->


    </div>
    <!-- end row -->











</div><!-- /j -->



<script>
    $(function(){
        homeLoggedinHandlers();
    });
</script>