<!-- error/access-denied -->

<div class="modal-header-soft round5top ui-draggable-handle">

<a href="<?= $this->url($_SESSION['level']['level']);?>" class="close"><i class="fa fa-home w"></i></a>
  <button type="button" class="close" id="history-back"><i class="fa fa-arrow-circle-left w right10"></i></button>
  &nbsp; <span class="big" id="modal-dialog-title"><strong>
  <?= $this->translate('Access denied to this ressource.')?>
  </strong></span>
</div>


<div class="jumbotron" style="border-top-left-radius: 0px; border-top-right-radius: 0px;">



<div class="row">
<div class="col-md-12">

    <p><?= $this->translate('Access denied to this ressource.') ?></p>
  </div>

</div><!-- end row -->



</div><!-- end jumbotron -->

<!-- /error/access-denied -->

