<!-- error/access-denied-dialog -->

<div id="error-access-denied">

	<div class="row">
		<div class="col-md-12">
		
           <?= $this->translate('Access denied to this ressource.')?><br>
           
           
			</div>
			<!-- /12 -->
			
	</div>
		<!-- end row -->

    <div class="row">
    	<div class="col-xs-12">
    		<hr />
		</div>
	</div>
    
    <div class="row">
    	<div class="col-xs-12 text-right">
			<button type="button" class="btn" data-dismiss="modal"><i class="fa fa-ban"></i> <?= $this->translate('Close')?></button>
		</div>
    </div><!-- /r -->


	
</div>

<!-- /error/access-denied-dialog -->

	
	