
<?= $this->partial('partial/page-header.phtml', ['title' => $this->translate('Access denied to this ressource.')])?>

<div class="jumbotron" style="border-top-left-radius: 0px; border-top-right-radius: 0px;">



<div class="row">
<div class="col-md-12">

    <p><?= $this->translate('Access denied to this ressource.') ?></p>
  </div>

</div><!-- end row -->



</div><!-- end jumbotron -->

