
<?= $this->partial('partial/page-header.phtml', ['title' => $this->translate('Error')])?>


<div class="jumbotron" style="border-top-left-radius: 0px; border-top-right-radius: 0px;">



<div class="row">
<div class="col-md-12">

    <p><span class="red"><strong><i class="fa fa-exclamation-triangle"></i></strong></span> <?= $message?></p>
  </div>

</div><!-- end row -->



</div><!-- end jumbotron -->

