<!-- error/error-dialog -->

<div id="error">
	<div class="row">
		<div class="col-md-12">
		
           <span class="red"><strong><i class="fa fa-exclamation-triangle"></i></strong></span> <?= $message?><br>
           
			</div>
			<!-- /12 -->
			
	</div>
		<!-- end row -->

    <div class="row">
    	<div class="col-xs-12">
    		<hr />
		</div>
	</div>
    
    <div class="row">
    	<div class="col-xs-12 text-right">
			<button type="button" class="btn" data-dismiss="modal"><i class="fa fa-ban"></i> <?= $this->translate('Close')?></button>
		</div>
    </div><!-- /r -->


	
</div>

<!-- /error/error-dialog -->
