<!-- program/add-proposals-from-city -->

<?php $paging = $this->sortingDivPaginationHelper($pagedProposals, $page, $this->url('program', array('action'=>'add-proposals-from-city', 'id' => $program->getProgUUID())), 'add-city-proposals', $limit, $sort, $order, $filter); ?>

<div id="program-add-proposals-from-city"
	data-remove-proposal="<?=$this->translate('Remove Proposal')?>"
	data-add-proposal="<?=$this->translate('Add Proposal')?>"
	data-remove-measure="<?=$this->translate('Remove Measure')?>"
	data-add-measure="<?=$this->translate('Add Measure')?>">
  <div class="row">
    <div class="col-md-12"> 
      <?= sprintf($this->translate('You have <strong id="program-add-proposals-from-city-count">%d</strong> Proposals in your Program <strong>%s</strong>'), count($program->getProposals()),$program->getProgName())?>
       </div>
    <!-- /11 --> 
  </div>
  <!-- /row -->
  <hr />
  <div class="row">
    <div class="col-md-9">
      <div class="btn-group" role="group" aria-label="..."> 
      	<a
				href="<?= $this->url('program', array('action'=>'add-proposals-from-city', 'id' => $program->getProgUUID(), 'page'=>1, 'filter' => 'none'));?>"
				class="btn btn-sm <?= $filter=='none'?'btn-success':'btn-default'?>" id="page-add-city-proposals">
        <?= $this->translate('All')?>
        </a>
        <a
				href="<?= $this->url('program', array('action'=>'add-proposals-from-city', 'id' => $program->getProgUUID(), 'page'=>1, 'filter' => 'included'));?>"
				class="btn btn-sm <?= $filter=='included'?'btn-success':'btn-default'?>" id="page-add-city-proposals">
        <?= $this->translate('Included')?>
        </a> 
        <a
				href="<?= $this->url('program', array('action'=>'add-proposals-from-city', 'id' => $program->getProgUUID(), 'page'=>1, 'filter' => 'proposal-not-included'));?>"
				class="btn btn-sm <?= $filter=='proposal-not-included'?'btn-success':'btn-default'?>" id="page-add-city-proposals">
        <?= $this->translate('Proposals not included')?>
        </a> 
        <a
				href="<?= $this->url('program', array('action'=>'add-proposals-from-city', 'id' => $program->getProgUUID(), 'page'=>1, 'filter' => 'measures-not-included'));?>"
				class="btn btn-sm <?= $filter=='measures-not-included'?'btn-success':'btn-default'?>" id="page-add-city-proposals">
        <?= $this->translate('Measures not included')?>
        </a> 
        <a
				href="<?= $this->url('program', array('action'=>'add-proposals-from-city', 'id' => $program->getProgUUID(), 'page'=>1, 'filter' => 'my-proposals'));?>"
				class="btn btn-sm <?= $filter=='my-proposals'?'btn-success':'btn-default'?>" id="page-add-city-proposals">
        <?= $this->translate('My Proposals')?>
        </a> 
         </div>
    </div>
    <!-- /6 -->
    <div class="col-md-3">
      <div class="fltr">
        <ul class="nav">
          <li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-down"></i> </span> 
            <!--  by <span class="caret"></span> --> 
            </a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a id="page-add-city-proposals"
								href="<?= $this->url('program', array('action'=>'add-proposals-from-city', 'id' => $program->getProgUUID(), 'sort'=>'category', 'order'=>'desc', 'results'=>$limit), true);?>">
                <?= $this->translate('Category')?>
                </a></li>
              <li><a id="page-add-city-proposals"
								href="<?= $this->url('program', array('action'=>'add-proposals-from-city', 'id' => $program->getProgUUID(), 'sort'=>'name', 'order'=>'desc', 'results'=>$limit), true);?>">
                <?= $this->translate('Name')?>
                </a></li>
              <li><a id="page-add-city-proposals"
								href="<?= $this->url('program', array('action'=>'add-proposals-from-city', 'id' => $program->getProgUUID(), 'sort'=>'status', 'order'=>'desc', 'results'=>$limit), true);?>">
                <?= $this->translate('Status')?>
                </a></li>
              <li><a id="page-add-city-proposals"
								href="<?= $this->url('program', array('action'=>'add-proposals-from-city', 'id' => $program->getProgUUID(), 'sort'=>'user', 'order'=>'desc', 'results'=>$limit), true);?>">
                <?= $this->translate('Owner')?>
                </a></li>
              <li class="divider"></li>
              <li><a id="page-add-city-proposals"
								href="<?= $this->url('program', array('action'=>'add-proposals-from-city', 'id' => $program->getProgUUID(), 'sort'=>'published-date', 'order'=>'desc'), true);?>">
                <?= $this->translate('Published date')?>
                </a></li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="fltr">
        <ul class="nav">
          <li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-up"></i> </span> 
            <!-- by <span class="caret"></span> --> 
            </a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a id="page-add-city-proposals"
								href="<?= $this->url('program', array('action'=>'add-proposals-from-city', 'id' => $program->getProgUUID(), 'sort'=>'category', 'order'=>'asc', 'results'=>$limit), true);?>">
                <?= $this->translate('Category')?>
                </a></li>
              <li><a id="page-add-city-proposals"
								href="<?= $this->url('program', array('action'=>'add-proposals-from-city', 'id' => $program->getProgUUID(), 'sort'=>'name', 'order'=>'asc', 'results'=>$limit), true);?>">
                <?= $this->translate('Name')?>
                </a></li>
              <li><a id="page-add-city-proposals"
								href="<?= $this->url('program', array('action'=>'add-proposals-from-city', 'id' => $program->getProgUUID(), 'sort'=>'status', 'order'=>'asc', 'results'=>$limit), true);?>">
                <?= $this->translate('Status')?>
                </a></li>
              <li><a id="page-add-city-proposals"
								href="<?= $this->url('program', array('action'=>'add-proposals-from-city', 'id' => $program->getProgUUID(), 'sort'=>'user', 'order'=>'asc', 'results'=>$limit), true);?>">
                <?= $this->translate('Owner')?>
                </a></li>
              <li class="divider"></li>
              <li><a id="page-add-city-proposals"
								href="<?= $this->url('program', array('action'=>'add-proposals-from-city', 'id' => $program->getProgUUID(), 'sort'=>'published-date', 'order'=>'asc', 'results'=>$limit), true);?>">
                <?= $this->translate('Published date')?>
                </a></li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="fltr right10 top5">
        <?= $this->translate('Sorted by')?>
        <?php if ($sort=='published-date'):?>
        <?= $this->translate('Published date')?>
        <?php else:?>
        <?=ucfirst($sort)?>
        <?php endif;?>
        <?=$order=='asc'?'<i class="fa fa-arrow-up"></i>':'<i class="fa fa-arrow-down"></i>'?>
      </div>
    </div>
    <!--/6--> 
  </div>
  <!-- /row -->
  <hr>
  <?php if(count($pagedProposals)>0):?>
  <?php foreach($pagedProposals as $index => $proposal): ?>
  <div class="row">
    <div class="col-md-1" style="max-width: 60px;"> <img
				src="<?= $this->basePath()?>/files/<?= $proposal->getCat()->getCatImage() ?>"
				height="42" width="42"
				title="<?= $proposal->getCat()->getCatCat()->getCatName() ?>"> </div>
    <!-- /1 -->
    <div class="col-md-5" style="min-width: 300px;">
      <?= $proposal->getCat()->getCatCat()->getCatName() ?>
      -
      <?= $proposal->getCat()->getCatName()?>
      <br />
      <?php $proposalDescription = preg_replace('/<[^>]*>/', ' ', $proposal->getPropDescription()); 

      $proposalDescription = (strlen($proposalDescription) > 200) ? substr($proposalDescription, 0, 200) . '...' : $proposalDescription;?>



<a
						href="<?= $this->url('proposal', array('action'=>'view', 'id'=>$proposal->getPropUUID()));?>"
						title="<?= $proposalDescription ?>" id="country-proposal-item"
						data-id="<?= $proposal->getPropUUID()?>"><span class="big"><?= $proposal->getPropSavedName() ?></span></a>
      </span> <br />
      <!-- user -->
      <?= $this->translate('by')?>
      <a
						href="<?= $this->url('user/profile', array('action'=>'mini-profile', 'id'=>$proposal->getUsr()->getUsrUUID()));?>"
						data-title="<?= $proposal->getUsr()->getUsrName() ?>'s mini profile"
						data-id="<?=$proposal->getUsr()->getUsrUUID()?>"
						id="program-add-proposals-from-city-view-profile"> <span class="badge"><?= $proposal->getUsr()->getUsrName() ?></span></a>
      </span> <i class="fa fa-clock-o"></i>
      <?= $proposal->getPropPublishedDate()->format('d/m/Y') ?>
    </div>
    <!-- /4 -->
    <div class="col-md-3">
      
      <?= $this->{"status-$index"}?>
      
    </div>
    <div class="col-md-1">
    </div>
    <div class="col-md-2">
      <?php $hasProposal = $program->getProposals()->contains($proposal);?>
      <button type="button"
				data-url="<?= $this->url('program', array('action'=>'add-remove-proposal', 'id'=>$proposal->getPropUUID()));?>"
				class="btn <?=$hasProposal?'btn-primary':'btn-orange'?>"
				id="add-remove-proposal"
				data-measure=<?= $proposal->getMeasure()!=null?>> <i class="fa <?=$hasProposal?'fa-times-circle':'fa-plus-circle'?>"></i> <span>
      <?= $hasProposal?($proposal->getMeasure()?$this->translate('Remove Measure'):$this->translate('Remove Proposal')):($proposal->getMeasure()?$this->translate('Add Measure'):$this->translate('Add Proposal'))?>
      </span> </button>
    </div>
    <!-- /2 --> 
  </div>
  <!-- /row -->
  <hr />
  <?php endforeach; ?>
  <?php else:?>
  <div class="row">
    <div class="col-md-12">
      <?= $this->translate('There are no Proposals or Measures that can be attached to this program')?>
      .</div>
  </div>
  <?php endif;?>
  <?= $paging; ?>
  <div class="row">
    <div class="col-xs-12">
      <hr />
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 text-right">
      <button type="button" class="btn btn-default"
				id="program-add-proposals-from-city-donned" data-dismiss="modal">
      <?= $this->translate('Done')?>
      </button>
    </div>
  </div>
  <!-- /r --> 
</div>
<!-- /jumbotron --> 
<script type="text/javascript">
    $(function () {
    	programAddProposalsFromCityHandlers();
    });
</script>

<!-- /program/add-proposals-from-city -->
