

<div id="program-add-proposal">

	<?php 
        $levelName = '';$level=$proposal->getPropLevel();
        if ($level==$this->configItem('demodyne.level.city')) {
            $level = 'city';
            $levelName = $user->getCity()->getFullCity()?$user->getCity()->getFullCity()->getCityName():$user->getCity()->getCityName();
            $createProgramTitle = sprintf($this->translate('Create my Program for my City, %s'), $levelName);
            $noProgram = sprintf($this->translate('You must first create your Program for your City, %s, to be able to add Proposals or Measures.'), $levelName);
            if ($proposal->isMeasure()) {
                $addToProgram = sprintf($this->translate('Do you want to add the Measure <br><strong>%s</strong><br> to your Program for your City, %s ?'), $proposal->getPropSavedName(), $levelName);
            }
            else {  
                $addToProgram = sprintf($this->translate('Do you want to add the Proposal <br><strong>%s</strong><br> to your Program for your City, %s ?'), $proposal->getPropSavedName(), $levelName);
            }
        }
        elseif ($level==$this->configItem('demodyne.level.region')) {
            $level = 'region';
            $levelName = $user->getCity()->getRegion()->getRegionName();
            $createProgramTitle = sprintf($this->translate('Create my Program for my Region, %s'), $levelName);
            $noProgram = sprintf($this->translate('You must first create your Program for your Region, %s, to be able to add Proposals or Measures.'), $levelName);
            if ($proposal->isMeasure()) {
                $addToProgram = sprintf($this->translate('Do you want to add the Measure <br><strong>%s</strong><br> to your Program for your Region, %s ?'), $proposal->getPropSavedName(), $levelName);
            }
            else {  
                $addToProgram = sprintf($this->translate('Do you want to add the Proposal <br><strong>%s</strong><br> to your Program for your Region, %s ?'), $proposal->getPropSavedName(), $levelName);
            }
        }
        else {
            $level = 'country';
            $levelName =  '<img src="/img/flags/'. str_replace(' ', '-', $user->getCountry()->getCountryName()).'.png" style="margin-bottom: 4px;" width="18" height="12"> '.$user->getCountry()->getCountryName();
                
            $createProgramTitle = sprintf($this->translate('Create my Program for my Country, %s'), $levelName);
            $noProgram = sprintf($this->translate('You must first create your Program for your Country, %s, to be able to add Proposals or Measures.'), $levelName);
            if ($proposal->isMeasure()) {
                $addToProgram = sprintf($this->translate('Do you want to add the Measure <br><strong>%s</strong><br> to your Program for your Country, %s ?'), $proposal->getPropSavedName(), $levelName);
            }
            else {  
                $addToProgram = sprintf($this->translate('Do you want to add the Proposal <br><strong>%s</strong><br> to your Program for your Country, %s ?'), $proposal->getPropSavedName(), $levelName);
            }
        }
    ?>


	<?php if (isset($program)):?>
	<div class="row">
		<div class="col-md-12">


			<p class="big center"><?= $addToProgram ?> <br>

			</p>

		</div>
		<!-- /12 -->

	</div>
	<!-- end row -->
	<hr />
	<div class="row">
		<div class="col-md-12 text-right">
			<button type="button" class="btn btn-orange"
				id="program-add-proposal-add-button"
				data-url="<?= $this->url('program', array( 'action'=>'add-proposal', 'id'=>$proposal->getPropUUID()));?>">
				<i class="fa fa-plus-circle"></i> <?= $this->translate('Add')?></button>
			<button type="button" class="btn" data-dismiss="modal">
				<i class="fa fa-ban"></i> <?= $this->translate('Cancel')?></button>
		</div>
	</div>  
	<?php else:?>
	<div class="row">
		<div class="col-md-12">


			<p class="big"><?= $noProgram ?> <br>

			</p>

		</div>

	</div>
	<!-- end row -->
	<hr />
	<div class="row">
		<div class="col-md-12 text-right">
			<button type="button" class="btn btn-orange"
			id="program-add-proposal-create-program"
				data-url="<?= $this->url('program', array( 'action'=>'add-program', 'proposal'=>$proposal->getPropUUID(), 'level' => $level));?>"
				data-dialog-title="<?=$createProgramTitle?>">
				<i class="fa fa-plus-circle"></i> <?= $this->translate('Create now')?></button>
			<button type="button" class="btn" data-dismiss="modal">
				<i class="fa fa-ban"></i> <?= $this->translate('Cancel')?></button>
		</div>
	</div>  
	<?php endif;?>
	
</div>

<script type="text/javascript">
		$(document).ready(function () {
			programAddProposalHandlers();
		});
	</script>
	