<?php $paging = $this->sortingDivPaginationHelper($pagedProposals, $page, $this->url('program', array('action'=>'get-proposals', 'id'=>$program->getProgUUID())), 'prog-prop', $limit, $sort, $order); ?>

<div id="program-get-proposals"

	data-url="<?= $this->url('program', ['action'=>'get-proposals'], true);?>">
  <?php if ($owner):?>
  <div class="row bot10">
    <div class="col-md-12">
    <?php
    $levelName = '';
    $levels = $this->configItem('demodyne.level');
    if (array_search($program->getProgLevel(), $levels)=='city') {
        $levelName = $program->getCity()->getFullCity()?$program->getCity()->getFullCity()->getCityName():$program->getCity()->getCityName();
    }
    elseif (array_search($program->getProgLevel(), $levels)=='region') {
        $levelName = $program->getCity()->getRegion()->getRegionName();
    }
    elseif (array_search($program->getProgLevel(), $levels)=='country') {
        $levelName = $program->getCity()->getCountry()->getCountryName();
    }
    
    ?>
    
    
      <button type="button"

				data-url="<?= $this->url('program', array('action'=>'add-proposals-from-city', 'id' => $program->getProgUUID()));?>"

				class="btn btn-orange" id="add-remove-proposals"

				data-dialog-title="<?=sprintf($this->translate('Add/Remove Proposals/Measures in my Program for %s'), $levelName)?>"> <i class="fa fa-plus-circle"></i>
      <?= $this->translate('Add Proposals & Measures')?>
      </button>
      <button type="button"

				data-url="<?= $this->url('program', array('action'=>'sort-proposals', 'id' => $program->getProgUUID()));?>"

				class="btn btn-default" id="sort-proposals-button"

				data-dialog-title="<?=sprintf($this->translate('Rank Proposals and Measures in my Program for %s'), $levelName)?>"> <i class="fa fa-sort"></i>
      <?= $this->translate('Rank Priorities')?>
      </button>
    </div>
    
    <!-- /12 --> 
    
  </div>
  
  <!-- /row -->
  
  <hr>
  <?php endif;?>
  <div class="row">
    <div class="col-md-4 big"> 
      <?= sprintf($this->translate('<span title="Linked Proposals / Official Measures"><strong>%d</strong> Linked Items</span>'), count($program->getProposals()))?>
       </div>
    
    <!-- /6 -->
    
    <div class="col-md-8 bot10">
      <div class="fltr">
        <ul class="nav">
          <li class="dropdown"><a class="dropdown-toggle"

						data-toggle="dropdown" href="#" aria-expanded="false"> <span

							class="label label-default"><i class="fa fa-caret-down"></i> </span> </a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a id="page-prog-prop"

								href="<?= $this->url('program', array('action'=>'get-proposals', 'sort'=>'priority', 'page'=>1, 'order'=>'desc'), true);?>">
                <?= $this->translate('Priority')?>
                </a></li>
              <li><a id="page-prog-prop"

								href="<?= $this->url('program', array('action'=>'get-proposals', 'sort'=>'name', 'page'=>1, 'order'=>'desc'), true);?>">
                <?= $this->translate('Name')?>
                </a></li>
              <li><a id="page-prog-prop"

								href="<?= $this->url('program', array('action'=>'get-proposals', 'sort'=>'user', 'page'=>1, 'order'=>'desc'), true);?>">
                <?= $this->translate('Owner')?>
                </a></li>
              <li><a id="page-prog-prop"

								href="<?= $this->url('program', array('action'=>'get-proposals', 'sort'=>'category', 'page'=>1, 'order'=>'desc'), true);?>">
                <?= $this->translate('Category')?>
                </a></li>
              <li class="divider"></li>
              <li><a id="page-prog-prop"

								href="<?= $this->url('program', array('action'=>'get-proposals', 'sort'=>'published-date', 'page'=>1, 'order'=>'desc'), true);?>">
                <?= $this->translate('Published date')?>
                </a></li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="fltr">
        <ul class="nav">
          <li class="dropdown"><a class="dropdown-toggle"

						data-toggle="dropdown" href="#" aria-expanded="false"> <span

							class="label label-default"><i class="fa fa-caret-up"></i> </span> </a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a id="page-prog-prop"

								href="<?= $this->url('program', array('action'=>'get-proposals', 'sort'=>'priority', 'page'=>1, 'order'=>'asc'), true);?>">
                <?= $this->translate('Priority')?>
                </a></li>
              <li><a id="page-prog-prop"

								href="<?= $this->url('program', array('action'=>'get-proposals', 'sort'=>'name', 'page'=>1, 'order'=>'asc'), true);?>">
                <?= $this->translate('Name')?>
                </a></li>
              <li><a id="page-prog-prop"

								href="<?= $this->url('program', array('action'=>'get-proposals', 'sort'=>'user', 'page'=>1, 'order'=>'asc'), true);?>">
                <?= $this->translate('Owner')?>
                </a></li>
              <li><a id="page-prog-prop"

								href="<?= $this->url('program', array('action'=>'get-proposals', 'sort'=>'category', 'page'=>1, 'order'=>'asc'), true);?>">
                <?= $this->translate('Category')?>
                </a></li>
              <li class="divider"></li>
              <li><a id="page-prog-prop"

								href="<?= $this->url('program', array('action'=>'get-proposals', 'sort'=>'published-date', 'page'=>1, 'order'=>'asc'), true);?>">
                <?= $this->translate('Published date')?>
                </a></li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="fltr right10 top5">
        <?= $this->translate('Sorted by')?>
        <?php if ($sort=='published-date'):?>
        <?= $this->translate('Published date')?>
        <?php else:?>
        <?=$this->translate(ucfirst($sort))?>
        <?php endif;?>
        <?=$order=='asc'?'<i class="fa fa-arrow-up"></i>':'<i class="fa fa-arrow-down"></i>'?>
      </div>
    </div>
    
    <!-- /6 --> 
    
  </div>
  
  <!-- /row -->
  
  <?php if (count($pagedProposals)>0):?>
  <?php foreach ($pagedProposals as $proposalScn): ?>
  <?php $proposal = $proposalScn->getProp();?>
  <hr>
  <div class="table-layout">
    <div class="table-cell fixed-width-30" title="Priority: <?= $proposalScn->getSortPosition()?>/<?=count($program->getProposals())?>">
      <?= $proposalScn->getSortPosition()?>
      <br>
      <?php if ($proposal->isMeasure()):?>
      <span	title="<?= $this->translate('Measure')?>"><i

				class="fa fa-university size15em"></i></span>
      <?php else:?>
      <span	title="<?= $this->translate('Proposal')?>"><i

				class="fa fa-bullhorn size15em"></i></span>
      <?php endif;?>
    </div>
    <div class="table-cell fixed-width-40"> <img

				src="<?= $this->basePath()?>/files/<?= $proposal->getCat()->getCatCat()->getCatImage() ?>"

				height="34" width="34"

				title="<?= $proposal->getCat()->getCatCat()->getCatName() ?> - <?= $proposal->getCat()->getCatName();?>"> </div>
    <div class="table-cell"> <a

				href="<?= $this->url($proposal->isMeasure()?'measure':'proposal', array('id'=>$proposal->getPropUUID()));?>"

				style="text-decoration: none !important;"

				id="program-get-proposals-list-item"> <span class="big">
      <?= $proposal->getPropSavedName() ?>
      </span></a> <?= $proposal->getPropAggregatedScore() ?><br>
      <?= $this->translate('Published by')?>
      <a

				href="<?= $this->url('user/profile', array('action'=>'mini-profile', 'id'=>$proposal->getUsr()->getUsrUUID()));?>"

				data-title="<?= $proposal->getUsr()->getUsrName() ?>'s <?= $this->translate('mini profile')?>"

				data-id="<?=$proposal->getUsr()->getUsrUUID()?>"

				id="program-get-proposals-view-profile"> <span class="badge">
      <?= $proposal->getUsr()->getUsrName() ?>
      </span></a> <i class="fa fa-clock-o"></i>
      <?= $proposal->getPropPublishedDate()->format('d/m/Y') ?>
    </div>
    <div class="table-cell fixed-width-30 text-right"> 
    	<a
				href="<?= $this->url('proposal', array('action'=>'favorite', 'id'=>$proposal->getPropUUID()));?>"
				id="program-get-proposals-favorite"
				data-favorite="<?= $proposal->getPropUUID()?>"><?php if (in_array($user, $proposal->getUsers())):?><i
    				class="fa fa-heart"
    				title="<?= $this->translate('Remove Favorite')?>"></i><?php else: ?><i
					class="fa fa-heart-o" title="<?= $this->translate('Add Favorite')?>"></i><?php endif; ?></a><br />
      <?php if ($owner):?>
      <a
				href="<?= $this->url('program', array('action'=>'add-remove-proposal', 'id'=>$proposal->getPropUUID()));?>"
				alt="Remove Proposal" id="program-get-proposals-remove-proposal"> <i
				class="fa fa-times-circle"
				title="<?= $this->translate('Remove from Program')?>"></i> </a>
      <?php endif;?>
    </div>
  </div>
  <?php endforeach;?>
  <hr>
  <div class="row">
    <div class="col-md-12">
      <?= $paging; ?>
    </div>
    
    <!--/12--> 
    
  </div>
  
  <!-- /row -->
  
  <?php else:?>
<table class="table table-condensed table-hover table-striped"><tr><td>  
  <?php if ($user==$program->getUsr()):?>
  <?= $this->translate('This program is empty. Fill it with Citizen Proposals and Official Measures.')?>
  <?php else:?>
	<?= $this->translate('This program is empty.')?>
  <?php endif;?>
  
  </td></tr></table>
  <?php endif;?>
</div>

<!-- /jumbotron --> 

<script type="text/javascript">

	$(function(){  

		programGetProposalsHandlers(<?=$owner?>)

	});

</script> 
