<div id="program-my-programs"
     data-url="<?= $this->url('program', array('action'=>'my-programs'));?>">


    <div class="row"><div class="col-md-12">
            <div class="big"><?= $this->translate('My Programs for City / Region / Country')?></div>
        </div>
    </div>




    <hr>
    <?php $levels = $this->configItem('demodyne.level');?>
    <?php foreach ($myPrograms as $level => $program):?>







        <div class="row">
            <?php if ($program):?>
                <?php $index = $program->getProgLevel();?>
                <div class="col-md-9 col-xs-12">
                    <div class="row">
                        <?php
                        $levelName = '';
                        $level = '';$levelNameFlag=null;
                        if (array_search($program->getProgLevel(), $levels)=='city') {
                            $levelName = $program->getCity()->getCityName();
                            $level='city';
                            $programLevel=$this->translate('Program for City');
                        }
                        elseif (array_search($program->getProgLevel(), $levels)=='region') {
                            $levelName = $program->getCity()->getRegion()->getRegionName();
                            $level='region';
                            $programLevel=$this->translate('Program for Region');
                        }
                        elseif (array_search($program->getProgLevel(), $levels)=='country') {
                            $levelName = $program->getCity()->getCountry()->getCountryName();
                            $levelNameFlag = '<img src="/img/flags/'.str_replace(' ', '-', $levelName).'.png" style="margin-bottom: 4px;" width="25" height="17"> '.$levelName;
                            $level='country';
                            $programLevel=$this->translate('Program for Country');
                        }


                        $programDescription = $program->getProgDescription();
                        $programDescription = (strlen($programDescription) > 150) ? substr($programDescription, 0, 150) . '...' : $programDescription

                        ?>
                        <div class="col-md-6 col-xs-12">
					<span class="big"><a
                                href="<?= $this->url('program', array('action' => 'view-program', 'id'=>$program->getProgUUID()));?>"
                                id="program-my-programs-item"
                                title="<?= $programDescription ?>"><?= $program->getProgName(); ?></a></span><br>
                            <?= $programLevel?>
                            <?= $this->partial('partial/show-level.phtml', ['level' => $program->getProgLevel(), 'city'=>$program->getCity()]); ?>
                            <br>

                            <div class="top5"><?= $this->translate('Published')?> <i class="fa fa-clock-o"></i> <?= $program->getProgCreatedDate()->format("d/m/Y") ?></div>

                        </div>
                        <div class="col-md-6 col-xs-12"><?= $this->{"categories-$index"}?></div>
                    </div>
                </div>
                <div class="col-md-3 col-xs-12 text-right">

                    <?= $this->partial('partial/program-actions.phtml', ['program' => $program, 'user'=>$user]); ?>



                </div>

            <?php else:?>

                <?php
                $levelName = $level;
                if ($user && $user->getCity()) {
                    if ($level=='city') {
                        $levelName = $user->getCity()->getCityName();
                    }
                    elseif ($level=='region') {
                        $levelName = $user->getCity()->getRegion()->getRegionName();
                    }
                    elseif ($level=='country') {
                        $levelName = $user->getCity()->getCountry()->getCountryName();
                    }
                }
                ?>







                <div class="row">
                    <div class="col-md-12 text-xs-center">
                        <?php if ($user):?>
                            <button type="button" class="btn btn-orange btn-break"
                                    id="program-my-programs-add-new-program" data-url="<?=$this->url('program', array('action'=>'add-program', 'level' => $level))?>"
                                    data-dialog-title="<?=sprintf($this->translate('Create my Program for my %s, %s'), ucfirst($this->translate($level)), $levelName)?>">
                                <i class="fa fa-plus-circle"></i> <?= sprintf($this->translate('Create my Program for %s'), $levelName)?></button>
                        <?php else:?>
                            <button type="button" class="btn btn-orange btn-break"
                                    data-url="<?=$this->url('home/user-register', array('action'=>'please-register'))?>"
                                    data-dialog-title="<?=$this->translate('Please register')?>"
                                    id="please-register-button">
                                <i class="fa fa-plus-circle"></i> <?= sprintf($this->translate('Create my Program for %s'), ucfirst($this->translate($levelName)))?></button>
                        <?php endif;?>
                    </div>
                </div>

            <?php endif;?>
        </div>
        <hr>

    <?php endforeach;?>

</div><!--/id-->
<script type="text/javascript">
    //var myScenariosUrl = ;
    $(function(){
        programMyProgramsHandlers();
    });
</script>
