<?php

$city = $user->getCity();
if ($_SESSION['level']['level']=='city') {
    $levelName = ($city->getFullCity()?$city->getFullCity()->getCityName():$city->getCityName());
    $levelUrl = $this->url('browse', [
        'country' => $city->getCountry()->getCountryName(),
        'postalcode' => $city->getCityPostalcode(),
        'region'=> $city->getRegion()->getRegionName(),
        'cityname' => $city->getCityName()
    ], array('force_canonical' => true));
}
elseif ($_SESSION['level']['level']=='region') {
    $levelName = $city->getRegion()->getRegionName();
    $levelUrl = $this->url('browse',
        ['country' => $city->getCountry()->getCountryName(),
            'region'=> $city->getRegion()->getRegionName(),
        ], array('force_canonical' => true));
}
elseif ($_SESSION['level']['level']=='country') {
    $levelName = '<img src="/img/flags/'.str_replace(' ', '-', $city->getCountry()->getCountryName()).'.png" style="margin-bottom: 4px;" width="20" height="14" alt="'. $city->getCountry()->getCountryName() .'"> '.$city->getCountry()->getCountryName();
    $levelUrl = $this->url('browse', ['country' => $city->getCountry()->getCountryName()]);
}
else {

}
?>

<?php $paging = $this->sortingDivPaginationHelper($pagedEvents, $page, $this->url('event', array('action'=>'all-events')), 'all-events', $limit, $sort, $order, null, $month?'/date/'.$month.'/'.$year:''); ?>
<div class="jumbotron" id="event-all-events"
     data-attend-event="<?= $this->translate('Attend Event')?>"
     data-attend-session="<?= $this->translate('Attend Session')?>"
     data-decline="<?= $this->translate('Cancel attendance')?>"
     data-edit-event="<?=$this->translate('Edit Event')?>"
     data-add-event="<?=$this->translate('Add New Event')?>"
     data-cancel-event="<?=$this->translate('Cancel Event')?>"
     data-url="<?=$this->url('event', array('action'=>'all-events', 'sort'=>$sort, 'page'=>$page, 'order'=>$order, 'results' => $limit))?>"
     data-loading-text="<?= $this->translate('Loading ...')?>">




    <div class="row">
        <div class="col-md-6">

            <?php if ($user->isAdministration()):?>

                <button
                        data-href="<?= $this->url('event', array('action'=>'add-event')); ?>"
                        class="btn btn-orange" id="event-all-events-add-new-event">
                    <i class="fa fa-plus-circle"></i>

                    <?= $this->translate('Create Event')?>

                </button>

            <?php endif;?>

            <span class="title-mobile"><?=$eventsCount?> <?= $this->translate('Upcoming Events for')?> <?= $levelName?></span>
        </div>
        <div class="col-md-6">
            <div class="fltr">
                <ul class="nav">
                    <li class="dropdown"><a class="dropdown-toggle"
                                            data-toggle="dropdown" href="#" aria-expanded="false"> <span
                                    class="label label-default"><i class="fa fa-caret-down"></i> </span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a id="page-all-events"
                                   href="<?= $this->url('event', array('action'=>'all-events', 'sort'=>'name', 'page'=>1, 'order'=>'desc'), true);?>">

                                    <?=$this->translate('Name')?>

                                </a></li>
                            <li><a id="page-all-events"
                                   href="<?= $this->url('event', array('action'=>'all-events', 'sort'=>'status', 'page'=>1, 'order'=>'desc'), true);?>">

                                    <?=$this->translate('Status')?>

                                </a></li>
                            <li class="divider"></li>
                            <li><a id="page-all-events"
                                   href="<?= $this->url('event', array('action'=>'all-events', 'sort'=>'start_date', 'page'=>1, 'order'=>'desc'), true);?>">

                                    <?=$this->translate('Start date')?>

                                </a></li>
                            <li><a id="page-all-events"
                                   href="<?= $this->url('event', array('action'=>'all-events', 'sort'=>'end_date', 'page'=>1, 'order'=>'desc'), true);?>">

                                    <?=$this->translate('End date')?>

                                </a></li>
                        </ul></li>
                </ul>
            </div>
            <div class="fltr">
                <ul class="nav">
                    <li class="dropdown"><a class="dropdown-toggle"
                                            data-toggle="dropdown" href="#" aria-expanded="false"> <span
                                    class="label label-default"><i class="fa fa-caret-up"></i> </span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a id="page-all-events"
                                   href="<?= $this->url('event', array('action'=>'all-events', 'sort'=>'name', 'page'=>1, 'order'=>'asc'), true);?>">

                                    <?=$this->translate('Name')?>

                                </a></li>
                            <li><a id="page-all-events"
                                   href="<?= $this->url('event', array('action'=>'all-events', 'sort'=>'status', 'page'=>1, 'order'=>'asc'), true);?>">

                                    <?=$this->translate('Status')?>

                                </a></li>
                            <li class="divider"></li>
                            <li><a id="page-all-events"
                                   href="<?= $this->url('event', array('action'=>'all-events', 'sort'=>'start_date', 'page'=>1, 'order'=>'asc'), true);?>">

                                    <?=$this->translate('Start date')?>

                                </a></li>
                            <li><a id="page-all-events"
                                   href="<?= $this->url('event', array('action'=>'all-events', 'sort'=>'end_date', 'page'=>1, 'order'=>'asc'), true);?>">

                                    <?=$this->translate('End date')?>

                                </a></li>
                        </ul></li>
                </ul>
            </div>

        </div>
    </div>
    <hr>


<div class="row top5">
  <div class="col-xs-12">
            <div class="btn-group right10" role="group" aria-label="...">

                <a type="button"
                   class="btn btn-sm <?=($month || $searchTerms)?'btn-default':'btn-success'?>"
                   data-url="<?=$this->url('event', array('action'=>'all-events', 'sort'=>$sort, 'page'=>1, 'order'=>$order, 'results' => $limit))?>"
                   id="event-all-events-see-all"><?= $this->translate('All upcoming')?></a>

                <a type="button"
                   class="btn btn-sm <?=$month?'btn-success':'btn-default'?>"
                   data-url="<?=$this->url('event', array('action'=>'all-events', 'sort'=>$sort, 'page'=>1, 'order'=>$order, 'results' => $limit, 'month' => $month?$month:date('n'), 'year' => $year?$year:date('Y')))?>"
                   id="event-all-events-see-month"><?= $this->translate('By month')?></a>


            </div>
          </div>
</div>

<div class="row top5">
  <div class="col-xs-2 text-right top5">
              <?php
              $month = $month?:date('n');
              $nextYear =  $prevYear =  $year = $year?:date('Y');
              if ($month==1) {
                  $prevMonth = 12;
                  $prevYear = $year-1;
              }
              else {
                  $prevMonth = $month - 1;
              }
              if ($month==12) {
                  $nextMonth = 1;
                  $nextYear = $year + 1;
              }
              else {
                  $nextMonth = $month + 1;

              }
              ?>
              <a href="<?=$this->url('event', array('action'=>'all-events', 'page'=>1, 'month' => $prevMonth, 'year' => $prevYear))?>" id="page-all-events"><i class="fa fa-arrow-left"></i></a>
          </div>

<div class="col-xs-8">
<input type="text" name="event-all-events-start-month" id="event-all-events-start-month" class="form-control" value="">
</div>

<div class="col-xs-2 top5">
<a href="<?=$this->url('event', array('action'=>'all-events', 'page'=>1, 'month' => $nextMonth, 'year' => $nextYear))?>" id="page-all-events"><i class="fa fa-arrow-right"></i></a>
</div>

</div>


        <form
                action="<?=$this->url('event', array('action'=>'all-events', 'sort'=>$sort, 'page'=>1, 'order'=>$order, 'results' => $limit))?>"
                method="post" id="event-all-events-search-form">

            <div class="top5">
                <div class="form-group input-group">
                    <input style="min-height: 37px !important;" type="text"
                           class="form-control"
                           placeholder="<?= $this->translate('Search')?>" required="required"
                           name="searchTerms" <?=$searchTerms?'value="'.$searchTerms.'"':''?>>
                    <span class="input-group-btn">
						<button type="submit"
                                class="btn <?=$searchTerms?'btn-success':'btn-default'?>">
							<i class="fa fa-search fa-fw"></i>
          </button>
					</span>
                </div>
            </div>
        </form>

    <hr>
    <div id="event-all-events-results">
        <?php if (count($pagedEvents)):?>

            <?php foreach ($pagedEvents as $event):?>

                <?php
                if ($event->isSession()) {
                    $viewUrl = $this->url('session', array('action'=>'view-session', 'id'=> $event->getEventUUID()));
                }
                else {
                    $viewUrl = $this->url('event', array('action'=>'view-event', 'id'=> $event->getEventUUID()));
                }
                ?>




                <div class="row">

                    <div class="col-xs-12 wbr">

                        <div class="pull-left" style="min-width: 42px!important">
                            <img src="<?=$event->getEventImage()?$this->basePath($event->getEventImage()):$this->basePath('/img/events/noimage.png')?>"
                                 width="34" class="round5" title="<?=$event->getEventName()?>">
                            <? $now = new \DateTime();?>
                            <?php if ($event->getEventStartDate()>$now && $event->getEventEndDate()<$now):?>
                                <br>
								<span class="green right5"><i class="fa fa-circle size15em" title="<?= $event->isSession()?$this->translate('Session Started'):$this->translate('Event Started')?>"></i>
								</span>
                            <?php endif;?>
                        </div>
                        <div style="margin-left: 42px!important">
                            <a href="<?= $viewUrl?>"><span class="big"><?=$event->getEventName()?> <?=$event->getUsr()==$user?'(owner)':''?></span></a>
                            <br>
                            <?php
                            $eventStartDate = $event->getEventStartDate();//->setTimezone(new DateTimeZone($city->getRegion()->getRegionTimezone()));
                            $eventEndDate = $event->getEventEndDate();//->setTimezone(new DateTimeZone($city->getRegion()->getRegionTimezone()));
                            $countryFormat = $event->getCity()->getCountry()->getCountryFormat();
                            ?>

                                <span class="glyphicon glyphicon-calendar"></span>
                                <?=$this->dateFormat(
                                    $eventStartDate,
                                    IntlDateFormatter::MEDIUM, // date
                                    IntlDateFormatter::SHORT, // time
                                    $countryFormat
                                );?>
                                 - 
                                <?=$eventEndDate->format('d/m/Y') == $event->getEventStartDate()->format('d/m/Y')?
                                    $this->dateFormat(
                                        $eventEndDate,
                                        IntlDateFormatter::NONE, // date
                                        IntlDateFormatter::SHORT, // time
                                        $countryFormat
                                    )
                                    :
                                    $this->dateFormat(
                                        $eventEndDate,
                                        IntlDateFormatter::MEDIUM, // date
                                        IntlDateFormatter::SHORT, // time
                                        $countryFormat
                                    )?>
                                    <br>
                                    <i class="fa fa-map-marker"></i> <?=$event->getCity()->getCityName()?> (<?=$event->getCity()->getCityPostalcode()?>)
                        </div>
                    </div>
</div>







                <hr>





            <?php endforeach;?>

            <div class="row">
                <div class="col-md-12">
                    <?= $paging; ?>
                </div>
                <!--/12-->
            </div>
            <!-- /row -->


        <?php else:?>
            <div class="row">
                <div class="col-xs-12">
                    <?php if (!$searchTerms):?>
                        <?=$this->translate('No events planned this month.')?>
                    <?php else:?>
                        <?=$this->translate('No events matching your search terms.')?>
                    <?php endif;?>
                </div>
                <!--/12-->
            </div>
            <!-- /row -->

        <?php endif;?>
    </div>


    <?php $lang = $this->plugin('translate')->getTranslator()->getLocale();?>

    <script type="text/javascript">

        var month = ("<?=$this->translate('January')?> <?=$this->translate('February')?> <?=$this->translate('March')?> <?=$this->translate('April')?> <?=$this->translate('May')?> <?=$this->translate('June')?> <?=$this->translate('July')?> <?=$this->translate('August')?> <?=$this->translate('September')?> <?=$this->translate('October')?> <?=$this->translate('November')?> <?=$this->translate('December')?>").split(" ");

        var now = new Date();

        $(function() {

            <?php if ($month):?>

            $('#event-all-events-start-month').val(month[<?=$month-1?>] + " " + <?=$year?>);

            <?php else:?>

            $('#event-all-events-start-month').val(month[now.getMonth()] + " " + now.getFullYear());

            <?php endif;?>

            eventAllEventsHandlers('<?=$lang?>');

        });



    </script>
</div>
