<!-- event/all-events -->

<?php 
if ($_SESSION['level']['level']=='city') {
    $levelName = ($user->getCity()->getFullCity()?$user->getCity()->getFullCity()->getCityName():$user->getCity()->getCityName());
}
elseif ($_SESSION['level']['level']=='region') {
    $levelName = $user->getCity()->getRegion()->getRegionName();
}
elseif ($_SESSION['level']['level']=='country') {
    $levelName = '<img src="/img/flags/'.str_replace(' ', '-', $user->getCountry()->getCountryName()).'.png" style="margin-bottom: 4px;" width="20" height="14" alt="'. $user->getCountry()->getCountryName() .'"> '.$user->getCountry()->getCountryName();
} 
else {
        
}
?>

<?php $paging = $this->sortingDivPaginationHelper($pagedEvents, $page, $this->url('event', array('action'=>'all-events')), 'all-events', $limit, $sort, $order, null, $month?'/date/'.$month.'/'.$year:''); ?>
<div class="jumbotron" id="event-all-events"
	data-attend="<?= $this->translate('Attend Event')?>"
	data-decline="<?= $this->translate('Cancel attendance')?>"
	data-edit-event="<?=$this->translate('Edit Event')?>"
	data-add-event="<?=$this->translate('Add New Event')?>"
	data-cancel-event="<?=$this->translate('Cancel Event')?>"
	data-url="<?=$this->url('event', array('action'=>'all-events', 'sort'=>$sort, 'page'=>$page, 'order'=>$order, 'results' => $limit))?>">
	<div class="row">
		<div class="col-md-6"> 

      <?php if ($user->isAdministration()):?>

      <button
				data-href="<?= $this->url('event', array('action'=>'add-event')); ?>"
				class="btn btn-orange" id="event-all-events-add-new-event">
				<i class="fa fa-plus-circle"></i>

      	<?= $this->translate('Create Event')?>

      </button>

      <?php endif;?>

      <span class="big"><?=$eventsCount?> <?= $this->translate('Upcoming Events for')?> <?= $levelName?></span>
		</div>
		<div class="col-md-6">
			<div class="fltr">
				<ul class="nav">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-down"></i> </span>
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-all-events"
								href="<?= $this->url('event', array('action'=>'all-events', 'sort'=>'name', 'page'=>1, 'order'=>'desc'), true);?>">

                <?=$this->translate('Name')?>

                </a></li>
							<li><a id="page-all-events"
								href="<?= $this->url('event', array('action'=>'all-events', 'sort'=>'status', 'page'=>1, 'order'=>'desc'), true);?>">

                <?=$this->translate('Status')?>

                </a></li>
							<li class="divider"></li>
							<li><a id="page-all-events"
								href="<?= $this->url('event', array('action'=>'all-events', 'sort'=>'start_date', 'page'=>1, 'order'=>'desc'), true);?>">

                <?=$this->translate('Start date')?>

                </a></li>
							<li><a id="page-all-events"
								href="<?= $this->url('event', array('action'=>'all-events', 'sort'=>'end_date', 'page'=>1, 'order'=>'desc'), true);?>">

                <?=$this->translate('End date')?>

                </a></li>
						</ul></li>
				</ul>
			</div>
			<div class="fltr">
				<ul class="nav">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-up"></i> </span>
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-all-events"
								href="<?= $this->url('event', array('action'=>'all-events', 'sort'=>'name', 'page'=>1, 'order'=>'asc'), true);?>">

                <?=$this->translate('Name')?>

                </a></li>
							<li><a id="page-all-events"
								href="<?= $this->url('event', array('action'=>'all-events', 'sort'=>'status', 'page'=>1, 'order'=>'asc'), true);?>">

                <?=$this->translate('Status')?>

                </a></li>
							<li class="divider"></li>
							<li><a id="page-all-events"
								href="<?= $this->url('event', array('action'=>'all-events', 'sort'=>'start_date', 'page'=>1, 'order'=>'asc'), true);?>">

                <?=$this->translate('Start date')?>

                </a></li>
							<li><a id="page-all-events"
								href="<?= $this->url('event', array('action'=>'all-events', 'sort'=>'end_date', 'page'=>1, 'order'=>'asc'), true);?>">

                <?=$this->translate('End date')?>

                </a></li>
						</ul></li>
				</ul>
			</div>
			<div class="fltr right10 top5"><?= $this->translate('Sorted by')?>

        <?php if ($sort=='start_date'):?>

        <?=$this->translate('Start date')?>

        <?php elseif ($sort=='end_date'):?>

        <?=$this->translate('End date')?>

        <?php else:?>

        <?=$this->translate(ucfirst($sort))?>

        <?php endif;?>

        <?=$order=='asc'?'<i class="fa fa-arrow-up"></i>':'<i class="fa fa-arrow-down"></i>'?>

      </div>
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="col-md-2 col-xs-4">
			<button type="button"
				class="btn <?=($month || $searchTerms)?'btn-default':'btn-success'?>"
				data-url="<?=$this->url('event', array('action'=>'all-events', 'sort'=>$sort, 'page'=>1, 'order'=>$order, 'results' => $limit))?>"
				id="event-all-events-see-all"><?= $this->translate('All upcoming')?></button>
		</div>
		<div class="col-md-7 col-xs-8">
			<div class="fltl right10">
				<button type="button"
					class="btn <?=$month?'btn-success':'btn-default'?>"
					data-url="<?=$this->url('event', array('action'=>'all-events', 'sort'=>$sort, 'page'=>1, 'order'=>$order, 'results' => $limit, 'month' => $month?$month:date('n'), 'year' => $year?$year:date('Y')))?>"
					id="event-all-events-see-month"><?= $this->translate('By month')?></button>
			</div>
			<div class='input-group date col-md-3 fltl'
				id='event-all-events-month'>
				<input style="max-height: 37px !important;" type="text"
					name="event-all-events-start-month"
					id="event-all-events-start-month" class="form-control" value=""> <span
					class="input-group-addon" style="padding-bottom: 5px;"> <span
					class="glyphicon glyphicon-calendar"></span>
				</span>
			</div>
		</div>
		<form
			action="<?=$this->url('event', array('action'=>'all-events', 'sort'=>$sort, 'page'=>1, 'order'=>$order, 'results' => $limit))?>"
			method="post" id="event-all-events-search-form">
			<div class="col-md-3 col-xs-12">
				<div class="form-group input-group">
					<input style="max-height: 37px !important;" type="text"
						class="form-control"
						placeholder="<?= $this->translate('Search')?>" required="required"
						name="searchTerms" <?=$searchTerms?'value="'.$searchTerms.'"':''?>>
					<span class="input-group-btn">
						<button type="submit"
							class="btn <?=$searchTerms?'btn-success':'btn-default'?>">
							<i class="fa fa-search fa-fw"></i>

          <?= $this->translate('Search')?>

          </button>
					</span>
				</div>
			</div>
		</form>
	</div>
	<hr>

	<?php if (count($pagedEvents)):?>

  <?php foreach ($pagedEvents as $event):?>

	<div class="table-layout">
		<div class="table-cell fixed-width-120">
			<img
				src="<?=$event->getEventImage()?$this->basePath($event->getEventImage()):$this->basePath('/img/events/noimage.png')?>"
				width="110" height="83" title="<?=$event->getEventName()?>">
		</div>
		<div class="table-cell">
			<div class="row">
				<div class="col-md-5 col-xs-12">
					<a
						href="<?= $this->url('event', array('action'=>'view-event', 'id'=> $event->getEventUUID()));?>"><span
						class="big">

          <?=$event->getEventName()?> <?=$event->getUsr()==$user?'(owner)':''?>

          </span></a> <br>

          <?php $eventDescription = preg_replace('/<[^>]*>/', ' ', $event->getEventDescription());

      $eventDescription = (strlen($eventDescription) > 150) ? substr($eventDescription, 0, 150) . '...' : $eventDescription;?>

          <?=$eventDescription?>

        </div>
				<div class="col-md-3 col-xs-12">
					<span class="glyphicon glyphicon-calendar"></span> <?= $this->translate('Start Date')?>: <?=$event->getEventStartDate()->format('d/m/Y H:i')?><br>
					<span class="glyphicon glyphicon-calendar"></span> <?= $this->translate('End Date')?>: <?=$event->getEventEndDate()->format('d/m/Y H:i')?>

        </div>
				<div class="col-md-2 col-xs-12">
					<i class="fa fa-map-marker"></i> <?=$event->getEventLocation()?>

        </div>
				<div class="col-md-2 col-xs-12 text-right">
					<a
						href="<?= $this->url('event', array('action'=>'view-event', 'id'=> $event->getEventUUID()));?>"
						id="event-all-events-view-attendees"><i class="fa fa-users"></i> <span id="event-all-events-attendees-count"><?=count($event->getAttendees())?></span> <?= $this->translate('Attendees')?></a><br>     

      <?php if ($event->getUsr()==$user): // user is the owner?>

					<a
						href="<?= $this->url('event', array('action'=>'edit-event', 'id'=> $event->getEventUUID()));?>"
						id="event-all-events-edit"><i class="fa fa-pencil-square-o"></i> <?= $this->translate('Edit Event')?></a><br>

                        <?php if (!$event->getEventCanceledDate()):?>

                    		<a
						href="<?= $this->url('event', array('action'=>'cancel-event', 'id'=> $event->getEventUUID()));?>"
						id="event-all-events-cancel"><i class="fa fa-share-square-o"></i> <?= $this->translate('Cancel Event')?></a><br>

                        <?php endif;?>

                        

                        <a
						href="<?= $this->url('event', array('action'=>'duplicate-event', 'id'=> $event->getEventUUID()));?>"><i
						class="fa fa-calendar-plus-o"></i> <?= $this->translate('Duplicate Event')?></a><br>

      <?php elseif ($user->getUsrId() && !$event->getEventCanceledDate()):?>

          <a
						href="<?= $this->url('event', array('action'=>'attend-event', 'id' => $event->getEventUUID()));?>"
						title="<?= $this->translate('Attend Event')?>"
						id="event-all-events-attend">

              <?php if (!$event->hasAttendee($user)):?>

              <i class="fa fa-check-circle-o"></i>

              <?= $this->translate('Attend Event')?>

              <?php else:?>

              <i class="fa fa-times-circle-o"></i>

              <?= $this->translate('Cancel attendance')?>	

              <?php endif;?>

          </a><br>

      <?php endif;?>        

      <?php if ($event->getEventCanceledDate()):?>

      	 <span class="red"><strong><?= $this->translate('CANCELED')?></strong></span>

      <?php endif;?>        

        </div>
			</div>
		</div>
	</div>
	<hr>

  

  

  <?php endforeach;?>

<div class="row">
		<div class="col-md-12">
				<?= $paging; ?>
			</div>
		<!--/12-->
	</div>
	<!-- /row -->


  <?php else:?>
  <div class="row">
		<div class="col-md-12">
				<?php if (!$searchTerms):?>
            		<?=$this->translate('No events planned this month.')?>
            	<?php else:?>
            		<?=$this->translate('No events matching your search terms.')?>
            	<?php endif;?>
			</div>
		<!--/12-->
	</div>
	<!-- /row -->
	
  <?php endif;?>

  

   <?php $lang = $this->plugin('translate')->getTranslator()->getLocale();?>

  <script type="text/javascript">

var month = ("<?=$this->translate('January')?> <?=$this->translate('February')?> <?=$this->translate('March')?> <?=$this->translate('April')?> <?=$this->translate('May')?> <?=$this->translate('June')?> <?=$this->translate('July')?> <?=$this->translate('August')?> <?=$this->translate('September')?> <?=$this->translate('October')?> <?=$this->translate('November')?> <?=$this->translate('December')?>").split(" ");

	var now = new Date();

$(function() {

	<?php if ($month):?>

	$('#event-all-events-start-month').val(month[<?=$month-1?>] + " " + <?=$year?>);

	<?php else:?>

	$('#event-all-events-start-month').val(month[now.getMonth()] + " " + now.getFullYear());

	<?php endif;?>

	eventAllEventsHandlers('<?=$lang?>');

});



</script>
</div>

<!-- /event/all-events -->
