
<div id="event-delete-event">
	<div class="row">
		<div class="col-md-12">
      <?= $this->translate('Your event')?>
      '
      <?= $event->getEventName()?>
      '
      <?= $this->translate('will be deleted')?>.<br>
			<h1>
        <?= $this->translate('Are you sure?')?>
      </h1>
		</div>
		<!-- /12 -->
	</div>
	<!-- end row -->
	<div class="row">
		<div class="col-xs-12">
			<hr />
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 text-right">
			<button type="button" class="btn btn-orange"
				id="event-delete-event-yes"
				data-href="<?= $this->url('event', array('action'=>'delete-event', 'id' => $event->getEventUUID()));?>">
				<i class="fa fa-trash"></i> <?= $this->translate('Delete')?></button>
			<button type="button" class="btn" data-dismiss="modal"><i class="fa fa-ban"></i> <?= $this->translate('Cancel')?></button>
		</div>
	</div>
	<!-- /r -->
</div>
<script type="text/javascript">

		$(function () {

			eventDeleteEventHandlers();
			

		});

	</script> 
