<!-- event/publish-event -->

<div id="event-publish-event"
	data-url="<?= $this->url('city/event', array('action'=>'publish-event', 'id' => $event->getEventUUID() ));?>">
	<div class="row">
		<div class="col-md-12">
           <?= $this->translate('Your event')?> '<?= $event->getEventName()?>' <?= $this->translate('will be published')?>.<br>
			<?= $this->translate('Are you sure')?>?
		</div>
		<!-- /12 -->
	</div>
	<!-- end row -->
	<div class="row">
		<div class="col-xs-12">
			<hr />
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 text-right">
			<button type="button" class="btn btn-orange"
				id="publish-event-yes-button">
				<i class="fa fa-floppy-o"></i>
				<?= $this->translate('Yes')?>
			</button>
			<button type="button" class="btn"
				data-dismiss="modal">
				<i class="fa fa-ban"></i> <?= $this->translate('No')?>
			</button>
		</div>
	</div>
	<!-- /r -->
</div>
<script type="text/javascript">
	$(document).ready(function () {
		eventPublishEventHandlers();
	});
</script>

<!-- /event/publish-event -->
