<?php $paging = $this->sortingDivPaginationHelper($pagedUsers, $page, $this->url('event', array('action'=>'view-attendees', 'id' => $event->getEventUUID())), 'view-attendees', $limit, $sort, $order); ?>
<? /** @var \DGIModule\Entity\Event $event */ ?>
<div id="event-view-attendees"
     data-attend="<?= $this->translate('Attend Event')?>"
     data-decline="<?= $this->translate('Cancel attendance')?>"
     data-url="<?= $this->url('event', array('action'=>'view-attendees', 'id' => $event->getEventUUID()))?>">

    <? if ($event->getEventEndDate()>new DateTime()):?>
        <?php if ($user && $user!=$event->getUsr()):?>
            <button type="button" class="btn btn-orange"
                    id="event-view-attendees-attend"
                    data-url="<?= $this->url('event', array('action'=>'attend-event', 'id' => $event->getEventUUID()));?>">
                <?php if (!$event->hasAttendee($user)):?>

                    <i class="fa fa-check-circle-o size15em"></i>

                    <?= $event->isSession()?$this->translate('Attend Session'):$this->translate('Attend Event')?>

                <?php else:?>

                    <i class="fa fa-times-circle size15em"></i>

                    <?= $this->translate('Cancel attendance')?>

                <?php endif;?>
            </button><br>
            <hr>
        <?php endif;?>

        <?php if (!$user):?>
            <?= $this->partial('partial/please-register-button.phtml', ['text' => '<i class="fa fa-check-circle-o"></i> '.($event->isSession()?$this->translate('Attend Session'):$this->translate('Attend Event'))]); ?>
            <br>
            <hr>
        <?php endif;?>
    <?endif;?>

    <?php if ($event->getAttendees()->count()):?>
        <div class="row">
            <div class="col-md-12">
                <span class="big"><?= sprintf($this->translate('<span class="badge">%d</span> Attendees'), $event->getAttendees()->count())?></span>
            </div>
        </div>
        <hr>


        <?if ($user):?>
            <div class="row">
                <div class="col-md-12">
                    <div class="fltr">
                        <ul class="nav">
                            <li class="dropdown"><a class="dropdown-toggle"
                                                    data-toggle="dropdown" href="#" aria-expanded="false"> <span
                                            class="label label-default"><i class="fa fa-caret-down"></i> </span>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a id="page-view-attendees"
                                           href="<?= $this->url('event', array('action'=>'view-attendees', 'sort'=>'name', 'page'=>1, 'order'=>'desc'), true);?>"><?=$this->translate('Name')?></a></li>
                                    <li><a id="page-view-attendees"
                                           href="<?= $this->url('event', array('action'=>'view-attendees', 'sort'=>'type', 'page'=>1, 'order'=>'desc'), true);?>"><?=$this->translate('Type')?></a></li>

                                </ul></li>
                        </ul>
                    </div>
                    <div class="fltr">
                        <ul class="nav">
                            <li class="dropdown"><a class="dropdown-toggle"
                                                    data-toggle="dropdown" href="#" aria-expanded="false"> <span
                                            class="label label-default"><i class="fa fa-caret-up"></i> </span>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a id="page-view-attendees"
                                           href="<?= $this->url('event', array('action'=>'view-attendees', 'sort'=>'name', 'page'=>1, 'order'=>'asc'), true);?>"><?=$this->translate('Name')?></a></li>
                                    <li><a id="page-view-attendees"
                                           href="<?= $this->url('event', array('action'=>'view-attendees', 'sort'=>'type', 'page'=>1, 'order'=>'asc'), true);?>"><?=$this->translate('Type')?></a></li>

                                </ul></li>
                        </ul>
                    </div>
                    <div class="fltr right10 top5"><?= $this->translate('Sorted by')?> <?=$this->translate(ucfirst($sort))?>
                        <?=$order=='asc'?'<i class="fa fa-arrow-up"></i>':'<i class="fa fa-arrow-down"></i>'?></div>
                </div>
            </div>
            <hr>

            <?php foreach ($pagedUsers as $index => $user):?>

                <div class="row">
                    <div class="col-md-2 col-xs-2" style="min-width:45px; max-width:45px;">
                        <img src="<?=$this->basePath($user->getUsrPicture())  ?>" valign="middle" width="36" height="36" title="<?= $user->getUsrName() ?>" class="round5"/>

                    </div>
                    <div class="col-md-10 col-xs-10">
        			<span class="badge white"><a
                                href="<?= $this->url('user/profile', array('action'=>'mini-profile', 'id'=>$user->getUsrUUID()));?>"
                                data-title="<?= $user->getUsrName() ?>'s <?= $this->translate('mini profile')?>"
                                data-id="<?=$user->getUsrUUID()?>"
                                id="event-view-attendees-view-profile" class="white">  <?=$user->getUsrName() ?></a></span><br>
                        <?=$user->isAdministration()?'Administrator':($user->isPartner()?'Partner':'Citizen')?>
                    </div>
                </div><!-- /r -->
                <hr>

            <?php endforeach;?>

            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <?= $paging; ?>
                </div>
            </div><!-- /r -->

        <?else:?>
            <?=sprintf($this->translate('If you want to see the list of attendees, please %s'), $this->partial('partial/please-register-button.phtml', ['text' => '<i class="fa fa-pencil-square-o"></i> '.$this->translate('Register')]))?>
        <?endif;?>

    <?php else:?>
        <div class="row">
            <div class="col-md-12">
                <span class="big"><?=$event->getAttendees()->count()?> <?= $event->isSession()?$this->translate('Attendees for this Session'):$this->translate('Attendees for this Event')?></span>
            </div>
        </div>
        <hr>
    <?php endif;?>




</div>



<script type="text/javascript">
    $(function () {
        eventViewAttendeesHandlers();
    });
</script>