<?php
$levelName = '';
/** @var \DGIModule\Entity\Event $event */
$level=$event->getEventLevel();
if ($level==$this->configItem('demodyne.level.city')) {
    $levelName = ($event->getCity()->getFullCity()?($event->getEventFullCity()?$event->getCity()->getFullCity()->getCityName().' ('._('Full city').')':$event->getCity()->getFullCity()->getCityName().' <span class="small"><i>'.$event->getCity()->getDistrictName().'</i></span>'):$event->getCity()->getCityName().($event->getCity()->isFullCity()?' ('._('Full city').')':''));
}
elseif ($level==$this->configItem('demodyne.level.region')) {
    $levelName = $event->getCity()->getRegion()->getRegionName();
}
else {
    $levelName = '<img src="/img/flags/'.str_replace(' ', '-', $event->getCity()->getCountry()->getCountryName()).'.png" style="margin-bottom: 4px;" width="20" height="14"> '.$event->getCity()->getCountry()->getCountryName() .'</span>';
}
?>

<?= $this->partial('partial/page-header.phtml', ['title' => '<img src="/img/icon-events-33.svg" width="20">  '.sprintf($this->translate('Event for %s'), $levelName)])?>

<div class="jumbotron"
	style="border-top-left-radius: 0px; border-top-right-radius: 0px;"
	id="event-view-event">
	<div class="row">
		<div class="col-md-8">

			<div class="panel panel-default">
				<div class="panel-body">

					<p>
						<span class="bigblack"><?=$this->escapeHtml($event->getEventName())?></span>
					</p>

<?php $countryFormat = $event->getCity()->getCountry()->getCountryFormat() ?>

					<div class="row">
						<div class="col-md-6 col-xs-12">
							<img class="img-thumbnail" id="event-view-event-preview"
								src="<?=$event->getEventImage()?$this->basePath($event->getEventImage()):$this->basePath('/img/events/noimage.png')?>"
								valign="middle" title="<?= $this->translate('Event Image')?>"
								style="max-width: 300px !important;">
						</div>
						<div class="col-md-6 col-xs-12 top10">
							<i class="fa fa-map-marker size15em"></i> <?=$event->getEventLocation()?>
<hr>
							<span class="glyphicon glyphicon-calendar"></span> 
							<?= $this->translate('Start Date')?>: 
							<?=$this->dateFormat(
                					        $event->getEventStartDate(),
                                            IntlDateFormatter::MEDIUM, // date
                                            IntlDateFormatter::SHORT, // time
								            $countryFormat
                                        )?>
							
							<br>
							
							<span class="glyphicon glyphicon-calendar"></span> 
							<?= $this->translate('End Date')?>: 
							<?=$this->dateFormat(
                					        $event->getEventEndDate(),
                                            IntlDateFormatter::MEDIUM, // date
                                            IntlDateFormatter::SHORT, // time
								            $countryFormat
                                        )?>
<hr>
							<i class="fa fa-globe size15em"></i> <a
								href="<?=$this->escapeHtml($event->getEventLink())?>"
								target="_blank"><?=$this->escapeHtml($event->getEventLink())?></a>

						</div>
					</div>


					<p>
					
					
					<div class="desc"><?=$event->getEventDescription()?></div>
					</p>




<?= $this->partial('partial/social-links.phtml', [
    'type' => 'event',
    'url' => $this->url('event', array('action'=>'view-event', 'id'=>$event->getEventUUID()), array('force_canonical' => true)),
    'title' => $event->getEventName(),
    'description' => $event->getEventDescription()
]); ?> 

</div>
			</div>
			<!--/panel -->



		</div>
		<!-- /6 -->
		<div class="col-md-4">

<?=$this->attendees?>

</div>
		<!-- /6 -->
	</div>
	<!-- /row -->







</div>
<!-- /j -->





	<script type="text/javascript">

		$(function () {

			eventViewEventHandlers();

		});

	</script>
