
  <?php $paging = $this->sortingDivPaginationHelper($pagedUsers, $page, $this->url('event', array('action'=>'view-invitations', 'id' => $event->getEventUUID())), 'view-invitations', $limit, $sort, $order); ?>

<div id="event-view-invitations"
	data-url="<?=$this->url('event', array('action'=>'view-invitations', 'id' => $event->getEventUUID()))?>">


	<button type="button" class="btn btn-orange"
		id="event-view-invitations-invite"
		data-dialog-title="<?= $this->translate('Invite attendees')?>"
		data-url="<?= $this->url('event', array('action'=>'invite-attendees', 'id' => $event->getEventUUID()));?>">
			<i class="fa fa-users size15em"></i> <?= $this->translate('Invite attendees')?>
	</button>

	<hr>



	<?php if ($event->getInvitations()->count()):?>
	<div class="row">
		<div class="col-md-12">
			<span class="big"><?= sprintf($this->translate('<span class="badge">%d</span> Invitations Sent'), $event->getInvitations()->count())?></span> /      <span class="big"><?= sprintf($this->translate('<span class="badge">%d</span> Attendees'), $event->getAttendees()->count())?></span>
		</div></div>    <hr>
			<div class="row">        <div class="col-md-12">
		<div class="fltr">
				<ul class="nav">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-down"></i> </span>
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-view-invitations"
								href="<?= $this->url('event', array('action'=>'view-attendees', 'sort'=>'name', 'page'=>1, 'order'=>'desc'), true);?>"><?=$this->translate('Name')?></a></li>
							<li><a id="page-view-invitations"
								href="<?= $this->url('event', array('action'=>'view-attendees', 'sort'=>'type', 'page'=>1, 'order'=>'desc'), true);?>"><?=$this->translate('Type')?></a></li>

						</ul></li>
				</ul>
			</div>
			<div class="fltr">
				<ul class="nav">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-up"></i> </span>
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-view-invitations"
								href="<?= $this->url('event', array('action'=>'view-attendees', 'sort'=>'name', 'page'=>1, 'order'=>'asc'), true);?>"><?=$this->translate('Name')?></a></li>
							<li><a id="page-view-invitations"
								href="<?= $this->url('event', array('action'=>'view-attendees', 'sort'=>'type', 'page'=>1, 'order'=>'asc'), true);?>"><?=$this->translate('Type')?></a></li>

						</ul></li>
				</ul>
			</div>
			<div class="fltr right10 top5"><?= $this->translate('Sorted by')?> <?=$this->translate(ucfirst($sort))?>
                    <?=$order=='asc'?'<i class="fa fa-arrow-up"></i>':'<i class="fa fa-arrow-down"></i>'?></div>
		</div>
	</div>
	<hr>




	<?php foreach ($pagedUsers as $index => $user):?>



	<div class="row">
		<div class="col-md-2 col-xs-2" style="min-width:45px; max-width:45px;">
        <img src="<?=$this->basePath($user->getUsrPicture())  ?>" valign="middle" width="36" height="36" title="<?= $user->getUsrName() ?>" class="round5"/>

		</div>
		<div class="col-md-5 col-xs-5">
        			<a
				href="<?= $this->url('user/profile', array('action'=>'mini-profile', 'id'=>$user->getUsrUUID()));?>"
				data-title="<?= $user->getUsrName() ?>'s <?= $this->translate('mini profile')?>"
				data-id="<?=$user->getUsrUUID()?>"
				id="event-view-invitations-view-profile">  <?=$user->getUsrName() ?></a><br>
        <span class="badge"><?=$user->isAdministration()?'Administrator':($user->isPartner()?'Partner':'Citizen')?></span>
        </div>
        <div class="col-md-5 col-xs-5 text-right">
    		<?php if ($user->isInvited($event)):?>
    			<?php if ($user->isAttending($event)):?>
       				<span class="green" id="userstat"><?= $this->translate('Attendance confirmed')?></span>
    			<?php else:?>
    				<span class="blue" id="userstat"><?= $this->translate('Invitation pending')?></span>
    			<?php endif;?>
			<?php else:?>
				<span class="green" id="userstat"><?= $this->translate('Attendance confirmed')?></span>
			<?php endif;?>
        </div>
	</div><!-- /r -->
	<hr>


	<?php endforeach;?>



	<div class="row">
		<div class="col-md-12 col-xs-12">
        <?= $paging; ?>
        </div>
        </div><!-- /r -->



	<?php else:?>
	<div class="row">
		<div class="col-md-6 col-xs-12">
			<span class="big"><?= $this->translate('No invitations for this Event')?></span>
		</div>
	</div>
	<?php endif;?>




</div>



<script type="text/javascript">
            $(function () {
            	eventViewInvitationsHandlers();
            });
        </script>