<div class="jumbotron">


    <div class="row">
        <div class="col-md-5 col-md-push-7">
            <!-- UPCOMOING EVENTS -->
            <div>
                <?= $this->upcomingEventsSection ?>
            </div>
            <div>
                <?= $this->topProposalsSection ?>
            </div>
        </div>
        <div class="col-md-7 col-md-pull-5">
            <div class="row">
                <div class="col-md-12 col-xs-12 hidden-xs">
                    <?=$this->carouselBannersSection?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <?= $this->newsSection ?>
                </div>
                <!-- end col6 -->
            </div>
        </div>
    </div>





</div>