


<div class="row">
	<div class="col-md-12"> Un email vous a été envoyé à l'adresse <?= $user->getUsrEmail()?>. Merci de consulter votre boîte de réception pour confirmer votre
        inscription !
</div>
</div>

<div class="row"><div class="col-md-12">
        Rappelez-vous de vérifier votre boîte de <strong>spam/courrier indésirable</strong>, parfois les emails de validation y atterrissent par accident :)
</div></div>

<div class="row">
	<div class="col-xs-12">
		<hr />
	</div>
</div>

        
