<div id="register"
     data-getcities="<?= $this->url('location', array('action'=>'get-cities')); ?>"
     data-write-postal-code="Veuillez introduire un code postal"
     data-no-cities="Pas de ville pour ce code postal">

    <?php
    $form->prepare();
    $form->setAttribute('method', 'post');
    $form->setAttribute('action', $this->url('e-referendum', ['action'=>'register'])); ?>

    <?=$this->form()->openTag($form);?>

    <fieldset>



        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="usrLastname">Nom :</label>
            <div class="col-md-6">
                <?= $this->formElement($form->get('usrLastname'));?>
                <span class="text-danger"><?= $this->formElementErrors($form->get('usrLastname'));?></span>
            </div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="usrFirstname">Prénom :</label>
            <div class="col-md-6">
                <?= $this->formElement($form->get('usrFirstname'));?>
                <span class="text-danger"><?= $this->formElementErrors($form->get('usrFirstname'));?></span>
            </div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="usrNIR">Numéro de Sécurité Sociale :</label>
            <div class="col-md-6">
                <?= $this->formElement($form->get('usrNIR'));?>
                <span class="text-danger"><?= $this->formElementErrors($form->get('usrNIR'));?></span>
            </div>
        </div>


        <?= $this->formElement($form->get('country'));?>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="usrPostalcode">Code postal :</label>
            <div class="col-md-3">
                <?= $this->formElement($form->get('usrPostalcode'));?>                 
                <span class="text-danger"><?= $this->formElementErrors($form->get('usrPostalcode'));?></span>
            </div>
			<div class="col-md-2">
				<i class="fa s18 fa-spinner fa-pulse" id="cityLoad"
                       style="display: none"></i>
			</div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="city">Ville :</label>
            <div class="col-md-6">
                <?= $this->formElement($form->get('city'));?>
                <span class="text-danger"><?= $this->formElementErrors($form->get('city'));?></span>
            </div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="email">Email :</label>
            <div class="col-md-6">
                <?= $this->formElement($form->get('usrEmail'));?>
                <span class="text-danger"><?= $this->formElementErrors($form->get('usrEmail'));?></span>
            </div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="usrName">Nom utilisateur Demodyne :</label>
            <div class="col-md-6">
                <?= $this->formElement($form->get('usrName'));?>
                <?php if ($form->get('usrName')->getMessages()):
                    $message = $this->formElementErrors($form->get('usrName'));

                    ?>
                    <span class="text-danger"><?= $this->formElementErrors($form->get('usrName'));?></span>
                <?php endif;?>

            </div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="email">Mot de passe :</label>
            <div class="col-md-6">
                <?= $this->formElement($form->get('usrPassword'));?>
                <span class="text-danger"><?= $this->formElementErrors($form->get('usrPassword'));?></span>
            </div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="usrPasswordConfirm">Confirmer le mot de passe :</label>
            <div class="col-md-6">
                <?= $this->formElement($form->get('usrPasswordConfirm'));?>
                <span class="text-danger"><?= $this->formElementErrors($form->get('usrPasswordConfirm'));?></span>
            </div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="captcha">Copier les caractères de l'image :</label>
            <div class="col-md-6">
                <?= $this->formElement($form->get('captcha'));?>
                    <?php if ($form->get('captcha')->getMessages()):?>
                        <span class="text-danger"><?= $this->formElementErrors($form->get('captcha'));?></span>
                    <?php endif;?>

            </div>
        </div>

        <?= $this->formHidden($form->get('userCSRF'));?>

         <div class="form-group">
            <label class="col-md-4"></label>
            <div class="col-md-6">
                <button class="btn btn-primary btn-lg" type="submit">JE VALIDE !</button>
            </div>
        </div>


        <div class="form-group">
            <label class="col-md-4"></label>
            <div class="col-md-6">
                Vous avez déjà un compte DEMODYNE?
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4"></label>
            <div class="col-md-6">
                <a href="/login?redirect=/e-referendum/vote" class="btn btn-primary btn-lg">Se connecter avec votre compte 
                <img src="https://www.demodyne.org/img/dsimplu-text.svg" height="20" title="Demodyne"></a>
            </div>
        </div>

    </fieldset>
    <?=  $this->form()->closeTag();?>

    <script type="text/javascript">

        $(function() {
            registrationHandlers();
        });

    </script>

</div>