<?php

    $level = $_SESSION['level']['level'];
    if ($level=='city') {
        $levelName = ($user->getCity()->getFullCity()?$user->getCity()->getFullCity()->getCityName().' <span class="small"><i>'.$user->getCity()->getDistrictName().'</i></span>':$user->getCity()->getCityName());
        $addProposalDialogTitle = $this->translate('Create New Proposal for my city, $level$');
        $sameLevel = 1;
    }
    else if ($level=='region') {
        $levelName = $user->getCity()->getRegion()->getRegionName();
        $addProposalDialogTitle = $this->translate('Create New Proposal for my region, $level$');
    }
    else if ($level=='country') {
        $levelName = '<img src="/img/flags/'.str_replace(' ', '-', $user->getCountry()->getCountryName()).'.png" style="margin-bottom: 4px;" width="20" height="14"> '.$user->getCountry()->getCountryName() .'</span>';
        $addProposalDialogTitle = $this->translate('Create New Proposal for my country, $level$');
    }

?>


<?php $paging = $this->sortingDivPaginationHelper($pagedProposals, $page, $this->url('proposal', array('action'=>'all-proposals')), 'all-proposals', $limit, $sort, $order); ?>


<div class="jumbotron-mobile" id="proposal-all-proposals"
	data-url="<?= $this->url('proposal', array('action'=>'all-proposals', 'sort'=>$sort, 'page'=>$page, 'order'=>$order, 'results' => $limit));?>"
	data-add-to-my-program="<?=$this->translate('Add to my Program')?>"
	data-add-favorite="<?=$this->translate('Add Favorite')?>"
	data-remove-favorite="<?=$this->translate('Remove Favorite')?>">



<div class="title-mobile"><?=$proposalCount?> <?= $this->translate('Proposals for')?> <span id="level-name"><?=$levelName?></div>

<div class="row">
<div class="col-xs-6">

			<?php if ($user->getUsrId() && $user->isCitizen()):?>
			<button
				data-url="<?= $this->url('proposal', array('action'=>'add-proposal', 'level'=>$level));?>"
				id="add-new-proposal" type="button"
				class="btn btn-orange"
				data-dialog-title="<?= $addProposalDialogTitle ?> ">
					<i class="fa fa-plus-circle"></i> <?= $this->translate('Create New Proposal')?>

			</button>
			<?php elseif (!$user->getUsrId()):?>
				<?= $this->partial('partial/please-register-button.phtml', ['text' => '<i class="fa fa-plus-circle"></i> '.$this->translate('Create New Proposal')]); ?>
			<?php endif;?>
	</div>
<div class="col-xs-6">
			<div class="fltr">
				<ul class="nav" style="z-index: 1001!important;">
					<li class="dropdown" id="test">
                        <a class="dropdown-toggle"  role="button"
						    data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-down"></i> </span>
							<!--  by <span class="caret"></span> -->
					    </a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-all-proposals"
								href="<?= $this->url('proposal', array('action'=>'all-proposals', 'page'=>1, 'sort'=>'category', 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Category')?></a></li>
							<li><a id="page-all-proposals"
								href="<?= $this->url('proposal', array('action'=>'all-proposals', 'page'=>1, 'sort'=>'name', 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Name')?></a></li>
							<li><a id="page-all-proposals"
								href="<?= $this->url('proposal', array('action'=>'all-proposals', 'page'=>1, 'sort'=>'status', 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Status')?></a></li>
							<li><a id="page-all-proposals"
								href="<?= $this->url('proposal', array('action'=>'all-proposals', 'page'=>1, 'sort'=>'user', 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Owner')?></a></li>
							<li><a id="page-all-proposals"
								href="<?= $this->url('proposal', array('action'=>'all-proposals', 'page'=>1, 'sort'=>'votes', 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Number of Votes')?></a></li>
							<li><a id="page-all-proposals"
								href="<?= $this->url('proposal', array('action'=>'all-proposals', 'page'=>1, 'sort'=>'vote-average', 'order'=>'desc', 'results'=>$limit));?>"><?= $this->translate('Vote average')?></a></li>
							<li class="divider"></li>
							<li><a id="page-all-proposals"
								href="<?= $this->url('proposal', array('action'=>'all-proposals', 'page'=>1, 'sort'=>'published', 'order'=>'desc'));?>"><?= $this->translate('Published date')?></a></li>
						</ul></li>
				</ul>
			</div>
			<div class="fltr">
				<ul class="nav">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-up"></i> </span>
							<!-- by <span class="caret"></span> -->
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-all-proposals"
								href="<?= $this->url('proposal', array('action'=>'all-proposals', 'page'=>1, 'sort'=>'category', 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Category')?></a></li>
							<li><a id="page-all-proposals"
								href="<?= $this->url('proposal', array('action'=>'all-proposals', 'page'=>1, 'sort'=>'name', 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Name')?></a></li>
							<li><a id="page-all-proposals"
								href="<?= $this->url('proposal', array('action'=>'all-proposals', 'page'=>1, 'sort'=>'status', 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Status')?></a></li>
							<li><a id="page-all-proposals"
								href="<?= $this->url('proposal', array('action'=>'all-proposals', 'page'=>1, 'sort'=>'user', 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Owner')?></a></li>
							<li><a id="page-all-proposals"
								href="<?= $this->url('proposal', array('action'=>'all-proposals', 'page'=>1, 'sort'=>'votes', 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Number of Votes')?></a></li>
							<li><a id="page-all-proposals"
								href="<?= $this->url('proposal', array('action'=>'all-proposals', 'page'=>1, 'sort'=>'vote-average', 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Vote average')?></a></li>
							<li class="divider"></li>
							<li><a id="page-all-proposals"
								href="<?= $this->url('proposal', array('action'=>'all-proposals', 'page'=>1, 'sort'=>'published', 'order'=>'asc', 'results'=>$limit));?>"><?= $this->translate('Published date')?></a></li>
						</ul></li>
				</ul>
			</div>
		</div>
		<!--/6-->
	</div>
	<!-- /row -->
	<hr>



            <?php if(count($pagedProposals)>0):?>

                <?php foreach($pagedProposals as $index => $proposal): ?>








<div class="row">

<div class="col-xs-12">
<div class="pull-left" style="min-width: 42px!important">
<img src="<?= $this->basePath()?>/files/<?= $proposal->getCat()->getCatImage() ?>" height="34" width="34" class="round5" title="<?= $proposal->getCat()->getCatCat()->getCatName() ?>"></div>

<div style="margin-left: 42px!important">
<?php $proposalDescription = preg_replace('/<[^>]*>/', ' ', $proposal->getPropDescription());

      $proposalDescription = (strlen($proposalDescription) > 200) ? substr($proposalDescription, 0, 200) . '...' : $proposalDescription;?>

<a href="<?= $this->url('proposal', array('action'=>'view', 'id'=>$proposal->getPropUUID()));?>" id="country-proposal-item" data-id="<?= $proposal->getPropUUID()?>"><span class="big"><?= $proposal->getPropSavedName() ?></span></a>
					<br />
					<!-- user -->

					<?= $this->translate('by')?> <a
						href="<?= $this->url('user/profile', array('action'=>'mini-profile', 'id'=>$proposal->getUsr()->getUsrUUID()));?>"
						data-title="<?= $proposal->getUsr()->getUsrName() ?>'s mini profile"
						data-id="<?=$proposal->getUsr()->getUsrUUID()?>"
						id="view-profile"> <span class="badge"><?= $proposal->getUsr()->getUsrName() ?></span></a>
	<i class="fa fa-clock-o"></i> <?= $proposal->getPropPublishedDate()->format('d/m/Y') ?><br>
</div>
	</div>
</div><!--/r-->


	<hr />



                        <?php endforeach; ?>





<div class="row">
		<div class="col-md-12">
				<?= $paging; ?>
			</div>
		<!--/12-->
	</div>
	<!-- /row -->

                    <?php else:?>

<div class="row">
		<div class="col-md-12">
				<?= sprintf($this->translate('There are no proposals for %s.'), $levelName)?> <?= $user->isAdministration()?'':$this->translate('Be the first to create and publish a proposal')?>.
			</div>
		<!--/12-->
	</div>
	<!-- /row -->





                    <?php endif;?>




        </div>
<!-- /jumbotron -->


        <script type="text/javascript">

            $(function () {

            	proposalAllProposalsHandlers();

            	$('#test').on('show.bs.dropdown', function(e) {
            	    console.log('dropdown opened');
                });
            });

        </script>
