<?php $paging = $this->sortingDivPaginationHelper($pagedProposals, $page, $this->url('proposal', array('action'=>'idea-imported-proposals', 'id'=> $idea->getIdeaUUID())), 'idea-prop', $limit, $sort, $order); ?>
<div id="proposal-idea-proposals"
	class="parent" 
	data-add-to-my-program="<?=$this->translate('Add to my Program')?>"
	data-add-favorite="<?=$this->translate('Add Favorite')?>"
	data-remove-favorite="<?=$this->translate('Remove Favorite')?>">
	
<div class="row">
		<div class="col-md-8">
		
		
<span class="big"><?= sprintf($this->translate('There are %s imported Proposals'), $noProposals)?></span>
		</div>
		<!-- /8 -->
		<div class="col-md-4">
			<div class="fltr">
				<ul class="nav top10">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-down"></i> </span>
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-idea-prop"
								href="<?= $this->url('proposal', array('action'=>'idea-imported-proposals', 'id'=> $idea->getIdeaUUID(), 'page'=>1, 'sort'=>'name', 'order'=>'desc'));?>"><?= $this->translate('Name')?></a></li>
							<li><a id="page-idea-prop"
								href="<?= $this->url('proposal', array('action'=>'idea-imported-proposals', 'id'=> $idea->getIdeaUUID(), 'page'=>1, 'sort'=>'level', 'order'=>'desc'));?>"><?= $this->translate('Level')?></a></li>
							<li><a id="page-idea-prop"
								href="<?= $this->url('proposal', array('action'=>'idea-imported-proposals', 'id'=> $idea->getIdeaUUID(), 'page'=>1, 'sort'=>'category', 'order'=>'desc'));?>"><?= $this->translate('Category')?></a></li>
							<li><a id="page-idea-prop"
								href="<?= $this->url('proposal', array('action'=>'idea-imported-proposals', 'id'=> $idea->getIdeaUUID(), 'page'=>1, 'sort'=>'status', 'order'=>'desc'));?>"><?= $this->translate('Status')?></a></li>
							<li><a id="page-idea-prop"
								href="<?= $this->url('proposal', array('action'=>'idea-imported-proposals', 'id'=> $idea->getIdeaUUID(), 'page'=>1, 'sort'=>'draft', 'order'=>'desc'));?>"><?= $this->translate('Published / Draft')?></a></li>
							<li><a id="page-idea-prop"
								href="<?= $this->url('proposal', array('action'=>'idea-imported-proposals', 'id'=> $idea->getIdeaUUID(), 'page'=>1, 'sort'=>'votes', 'order'=>'desc'));?>"><?= $this->translate('Votes')?></a></li>
							<li class="divider"></li>
							<li><a id="page-idea-prop"
								href="<?= $this->url('proposal', array('action'=>'idea-imported-proposals', 'id'=> $idea->getIdeaUUID(), 'page'=>1, 'sort'=>'created-date', 'order'=>'desc'));?>"><?= $this->translate('Creation	date')?></a></li>
						</ul></li>
				</ul>
			</div>
			<div class="fltr">
				<ul class="nav top10">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-up"></i> </span>
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-idea-prop"
								href="<?= $this->url('proposal', array('action'=>'idea-imported-proposals', 'id'=> $idea->getIdeaUUID(), 'page'=>1, 'sort'=>'name', 'order'=>'asc'));?>"><?= $this->translate('Name')?></a></li>
							<li><a id="page-idea-prop"
								href="<?= $this->url('proposal', array('action'=>'idea-imported-proposals', 'id'=> $idea->getIdeaUUID(), 'page'=>1, 'sort'=>'level', 'order'=>'asc'));?>"><?= $this->translate('Level')?></a></li>
							<li><a id="page-idea-prop"
								href="<?= $this->url('proposal', array('action'=>'idea-imported-proposals', 'id'=> $idea->getIdeaUUID(), 'page'=>1, 'sort'=>'category', 'order'=>'asc'));?>"><?= $this->translate('Category')?></a></li>
							<li><a id="page-idea-prop"
								href="<?= $this->url('proposal', array('action'=>'idea-imported-proposals', 'id'=> $idea->getIdeaUUID(), 'page'=>1, 'sort'=>'status', 'order'=>'asc'));?>"><?= $this->translate('Status')?></a></li>
							<li><a id="page-idea-prop"
								href="<?= $this->url('proposal', array('action'=>'idea-imported-proposals', 'id'=> $idea->getIdeaUUID(), 'page'=>1, 'sort'=>'draft', 'order'=>'asc'));?>"><?= $this->translate('Published / Draft')?></a></li>
							<li><a id="page-idea-prop"
								href="<?= $this->url('proposal', array('action'=>'idea-imported-proposals', 'id'=> $idea->getIdeaUUID(), 'page'=>1, 'sort'=>'votes', 'order'=>'asc'));?>"><?= $this->translate('Votes')?></a></li>
							<li class="divider"></li>
							<li><a id="page-idea-prop"
								href="<?= $this->url('proposal', array('action'=>'idea-imported-proposals', 'id'=> $idea->getIdeaUUID(), 'page'=>1, 'sort'=>'created-date', 'order'=>'asc'));?>"><?= $this->translate('Creation	date')?></a></li>
						</ul></li>
				</ul>
			</div>
			<div class="fltr top10 right10"> <?= $this->translate('Sorted by')?> <?php if ($sort=='created-date'):?><?= $this->translate('Creation date')?><?php elseif ($sort=='draft'):?><?= $this->translate('Published / Draft')?><?php else:?><?=ucfirst($sort)?><?php endif;?> 
                    <?=$order=='asc'?'<i class="fa fa-arrow-up"></i>':'<i class="fa fa-arrow-down"></i>'?> </div>
		</div>
		<!-- /6 -->
	</div>
	<!-- /row -->
	<hr />
<?php if(count($pagedProposals)>0):?>
  <?php foreach($pagedProposals as $index => $proposal): ?>
  <div class="table-layout">
		<div class="table-cell fixed-width-40">
			<img
				src="<?= $this->basePath()?>/files/<?= $proposal->getCat()->getCatImage() ?>"
				height="34" width="34"
				title="<?= $this->escapeHtml($proposal->getCat()->getCatCat()->getCatName()) ?>">
		</div>
		<div class="table-cell">
			<div class="row">
				<div class="col-md-5 col-xs-12">
<?php $proposalDescription = $this->escapeHtml(preg_replace('/(?:\r\n|\r|\n)/', '<br>', $proposal->getPropDescription())); 
      $proposalDescription = (strlen($proposalDescription) > 150) ? substr($proposalDescription, 0, 150) . '...' : $proposalDescription;?>
					<a
						href="<?= $this->url('proposal', array('action'=>'view', 'id'=>$proposal->getPropUUID()));?>"
						title="<?= $proposalDescription ?>" id="idea-proposals-list-item"
						data-id="<?= $proposal->getPropUUID()?>"> <span class="big"><?= $proposal->getPropSavedName() ?></span></a>
                        <br>
			<?= $this->translate('in')?> <?= $this->escapehtml($proposal->getCat()->getCatCat()->getCatName()) ?> - <?= $this->escapehtml($proposal->getCat()->getCatName())?>
			            <br>
					<!-- user -->
					<?= $this->translate('by')?> <a
						href="<?= $this->url('user/profile', array('action'=>'mini-profile', 'id'=>$proposal->getUsr()->getUsrUUID()));?>"
						data-title="<?= $proposal->getUsr()->getUsrName() ?>'s mini profile"
						data-id="<?=$proposal->getUsr()->getUsrUUID()?>"
						id="proposal-idea-proposals-view-profile"> <span class="badge"><?= $proposal->getUsr()->getUsrName() ?></span></a>
					<i class="fa fa-clock-o"></i> <?= $proposal->getPropPublishedDate()->format('d/m/Y')?>
			            <br>
			<?=$this->translate('for')?> 
			<?= $this->partial('partial/show-level.phtml', ['level' => $proposal->getPropLevel(), 'city'=>$proposal->getCity()]); ?>
			
				</div>
				<div class="col-md-4 col-xs-12">
					<?= $this->translate('Current Status')?>:<br />
                    <?= $this->partial('partial/proposal-status.phtml', ['proposal' => $proposal])?><br /> <?= $this->translate('Last updated')?> <i
						class="fa fa-clock-o"></i> <?= $proposal->getPropSavedDate()->format('d/m/Y')?> 
</div>
				<div class="col-md-3 col-xs-12">        
<?= $this->{"status-details-$index"}?>
</div>
			</div>
		</div>
		<div class="table-cell fixed-width-150 text-right">
	<?php if ($proposal->getPropPublished()):?>

<span class="right5">
<a href="<?= $this->url('proposal', array('action'=>'favorite', 'id'=>$proposal->getPropUUID()));?>" id="proposal-idea-proposals-favorite"	data-favorite="<?= $proposal->getPropUUID()?>"><?php if (in_array($user, $proposal->getUsers())):?><i	class="fa fa-heart size15em" title="<?= $this->translate('Remove Favorite')?>"></i><?php else:?><i
				class="fa fa-heart-o size15em" title="<?= $this->translate('Add Favorite')?>"></i><?php endif;?></a>
                </span>
<span class="right5">
    				<?= $this->partial('partial/add-proposal-to-program.phtml', ['proposal' => $proposal]); ?>
</span>
				
		<?php endif;?>

<a target="_parent"
				href="<?= $this->url('proposal', array('action'=>'view', 'id'=>$proposal->getPropUUID()));?>#comment-list"><i class="fa fa-comments size15em" title="<?= count($proposal->getComments())?> <?= $this->translate('Comments')?>"></i></a> <?= count($proposal->getComments())?>
	
		</div>
	</div>
	<hr />
<?php endforeach; ?>
		
	<?= $paging; ?>
		 
<?php else:?>
    <div class="row">
    	
			<?= $this->translate("There are no imported proposals.")?>
		
	</div>
	
<?php endif;?>
<div class="row">
		<div class="col-xs-12">
			<hr />
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 text-right">
			
			<button type="button" class="btn"
				data-dismiss="modal">
				<i class="fa fa-ban"></i> <?= $this->translate('Close')?></button>
		</div>
	</div>
</div>
<!-- /jumbotron -->
<script type="text/javascript">
$(function(){  
	proposalIdeaImportedProposalsHandlers();
	});
</script>
