<!-- proposal/my-favorites -->

<?php if ($pagedProposals) $paging = $this->sortingDivPaginationHelper($pagedProposals, $page, $this->url('proposal', array('action'=>'my-favorites')), 'fav', $limit, $sort, $order); ?>
<div class="parent" id="proposal-my-favorites" 
	data-url="<?= $this->url('proposal', array('action'=>'my-favorites', 'sort'=>$sort, 'page'=>$page, 'order'=>$order, 'results' => $limit));?>"
	data-add-to-my-program="<?=$this->translate('Add to my Program')?>"
	data-add-favorite="<?=$this->translate('Add Favorite')?>"
	data-remove-favorite="<?=$this->translate('Remove Favorite')?>">
	
	<div class="row">
		<div class="col-md-6 top10">
<span class="big"><?= $this->translate('You have')?> <?=$noFavorites?> <?= $this->translate('Favorite Proposals')?></span>
		</div>
		<div class="col-md-6 text-right">
			<div class="fltr">
				<ul class="nav top10">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-down"></i> </span>
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-fav"
								href="<?= $this->url('proposal', array('action'=>'my-favorites', 'page'=>1, 'sort'=>'category', 'order'=>'desc'));?>"><?= $this->translate('Category')?></a></li>
							<li><a id="page-fav"
								href="<?= $this->url('proposal', array('action'=>'my-favorites', 'page'=>1, 'sort'=>'name', 'order'=>'desc'));?>"><?= $this->translate('Name')?></a></li>
							<li><a id="page-fav"
								href="<?= $this->url('proposal', array('action'=>'my-favorites', 'page'=>1, 'sort'=>'status', 'order'=>'desc'));?>"><?= $this->translate('Status')?></a></li>
							<li><a id="page-fav"
								href="<?= $this->url('proposal', array('action'=>'my-favorites', 'page'=>1, 'sort'=>'user', 'order'=>'desc'));?>"><?= $this->translate('Owner')?></a></li>
							<li><a id="page-fav"
								href="<?= $this->url('proposal', array('action'=>'my-favorites', 'page'=>1, 'sort'=>'votes', 'order'=>'desc'));?>"><?= $this->translate('Votes')?></a></li>
							<li class="divider"></li>
							<li><a id="page-fav"
								href="<?= $this->url('proposal', array('action'=>'my-favorites', 'page'=>1, 'sort'=>'published', 'order'=>'desc'));?>"><?= $this->translate('Published')?></a></li>
						</ul></li>
				</ul>
			</div>
			<div class="fltr">
				<ul class="nav top10">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-up"></i> </span>
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-fav"
								href="<?= $this->url('proposal', array('action'=>'my-favorites', 'page'=>1, 'sort'=>'category', 'order'=>'asc'));?>"><?= $this->translate('Category')?></a></li>
							<li><a id="page-fav"
								href="<?= $this->url('proposal', array('action'=>'my-favorites', 'page'=>1, 'sort'=>'name', 'order'=>'asc'));?>"><?= $this->translate('Name')?></a></li>
							<li><a id="page-fav"
								href="<?= $this->url('proposal', array('action'=>'my-favorites', 'page'=>1, 'sort'=>'status', 'order'=>'asc'));?>"><?= $this->translate('Status')?></a></li>
							<li><a id="page-fav"
								href="<?= $this->url('proposal', array('action'=>'my-favorites', 'page'=>1, 'sort'=>'user', 'order'=>'asc'));?>"><?= $this->translate('Owner')?></a></li>
							<li><a id="page-fav"
								href="<?= $this->url('proposal', array('action'=>'my-favorites', 'page'=>1, 'sort'=>'votes', 'order'=>'asc'));?>"><?= $this->translate('Votes')?></a></li>
							<li class="divider"></li>
							<li><a id="page-fav"
								href="<?= $this->url('proposal', array('action'=>'my-favorites', 'page'=>1, 'sort'=>'published', 'order'=>'asc'));?>"><?= $this->translate('Published date')?></a></li>
						</ul></li>
				</ul>
			</div>
			<div class="fltr top10 right10"> <?= $this->translate('Sorted by')?> <?php if ($sort=='published'):?><?= $this->translate('Published date')?><?php else:?><?=ucfirst($sort)?><?php endif;?> 
                    <?=$order=='asc'?'<i class="fa fa-arrow-up"></i>':'<i class="fa fa-arrow-down"></i>'?> </div>
		</div>
	</div>
	<!-- row -->
	<hr />    
<?php foreach($pagedProposals as $index => $proposal): ?>
	<div class="table-layout">
		<div class="table-cell fixed-width-40">
			<img
				src="<?= $this->basePath()?>/files/<?= $proposal->getCat()->getCatImage() ?>"
				height="34" width="34"
				title="<?= $this->escapeHtml($proposal->getCat()->getCatCat()->getCatName()) ?>"><br>
			<?php if ($proposal->getMeasure()):?>
			<span style="line-height: 2em;"
				title="<?= $this->translate('Measure')?>"><i
				class="fa fa-university size15em"></i></span>
			<?php else:?>
			<span style="line-height: 2em;"
				title="<?= $this->translate('Proposal')?>"><i
				class="fa fa-bullhorn size15em"></i></span>
			<?php endif;?>
		</div>
		<div class="table-cell">
			<div class="row">
				<div class="col-md-5 col-xs-12">
				<?php $proposalDescription = $this->escapeHtml($proposal->getPropDescription()); 
      $proposalDescription = (strlen($proposalDescription) > 150) ? substr($proposalDescription, 0, 150) . '...' : $proposalDescription;?>
				<a
						href="<?= $this->url('proposal', array('action'=>'view', 'id'=>$proposal->getPropUUID()));?>"
						title="<?= $proposalDescription ?>"
						id="proposal-my-favorites-proposal-item"
						data-id="<?= $proposal->getPropUUID()?>"><span class="big"><?= $proposal->getPropSavedName() ?></span></a>
					<br />
					<?= $this->translate('in')?> <?= $proposal->getCat()->getCatCat()->getCatName() ?> - <?= $proposal->getCat()->getCatName()?>
                    <br>
					<!-- user -->
					<?= $this->translate('by')?> <a
						href="<?= $this->url('user/profile', array('action'=>'mini-profile', 'id'=>$proposal->getUsr()->getUsrUUID()));?>"
						data-title="<?= $proposal->getUsr()->getUsrName() ?>'s mini profile"
						data-id="<?=$proposal->getUsr()->getUsrUUID()?>"
						id="proposal-my-favorites-view-profile"> <span class="badge"><?= $proposal->getUsr()->getUsrName() ?></span></a>
					<i class="fa fa-clock-o"></i> <?= $proposal->getPropPublishedDate()->format('d/m/Y')?>
</div>
				<div class="col-md-4 col-xs-12">
					<?= $this->translate('Current Status')?>:<br /> 
					<?= $this->{"status-$index"}?><br /> 
					<?= $this->translate('Last updated')?> <i class="fa fa-clock-o"></i> <?= $proposal->getPropSavedDate()->format('d/m/Y')?> 
</div>
				<div class="col-md-3 col-xs-12">        
<?= $this->{"status-details-$index"}?>
</div>
			</div>
		</div>
		<div class="table-cell fixed-width-150 text-right">
			<a
				href="<?= $this->url('proposal', array('action'=>'favorite', 'id'=>$proposal->getPropUUID()));?>"
				id="proposal-my-favorites-remove-favorite"
				data-favorite="<?= $proposal->getPropUUID()?>"> <i
				class="fa fa-heart"></i> <?= $this->translate('Remove Favorite')?>
			</a> <br /> 
			
		<?= $this->partial('partial/add-proposal-to-program.phtml', ['proposal' => $proposal]); ?>
            				
				
		
			<a target="_parent"
				href="<?= $this->url('proposal', array('action'=>'view', 'id'=>$proposal->getPropUUID()));?>#comment-list"
				title="<?= $this->translate('Comments')?>"><i class="fa fa-comments"></i> <?= sprintf($this->translate('%d Comments'), count($proposal->getComments()))?></a>
    </div>
	</div>
	<hr />
<?php endforeach; ?>
<div class="row">
		<div class="col-md-12">
     <?php if (isset($paging)) echo $paging; ?>
</div>
		<!-- /12 -->
	</div>
	<!-- row -->
</div>
<script type="text/javascript">
	$(function(){  
		proposalMyFavoritesHandlers();
	});
</script>

<!-- /proposal/my-favorites -->

