<!-- proposal/user-proposals -->

<?php $paging = $this->sortingDivPaginationHelper($pagedProposals, $page, $this->url('proposal', array('action'=>'user-proposals', 'id'=>$user->getUsrUUID())), 'user-proposals', $limit, $sort, $order, $filter); ?>
<div id="proposal-user-proposals"
	class="parent" 
	data-add-to-my-program="<?=$this->translate('Add to my Program')?>"
	data-add-favorite="<?=$this->translate('Add Favorite')?>"
	data-remove-favorite="<?=$this->translate('Remove Favorite')?>">
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<h2 class="text-center">
				<i class="fa fa-bullhorn"></i> <?= sprintf($this->translate('%s\'s Proposals'), $user->getUsrName())?></h2>
		</div>
		<!-- /6 -->
		<div class="col-md-3"></div>
	</div>
	<hr />
	<div class="row">
		<div class="col-md-12">
			<span class="big"><strong>
			<?= sprintf($this->translate('%s has <span class="badge big">%d</span> Proposals'), $user->getUsrName(), $noProposals)?></strong></span>
		</div>
		
		<!--/12-->
	</div>
	<!-- /row -->
	<hr>
	<div class="row">
		<div class="col-md-8">

<div class="btn-group" role="group" aria-label="...">
			<a id="page-user-proposals"
				class="btn btn-sm <?= $filter=='none'?'btn-success':'btn-default'?>"
				href="<?= $this->url('proposal', array('action'=>'user-proposals', 'id'=>$user->getUsrUUID(), 'page'=>1, 'filter'=>'none'));?>">
				<?=$this->translate('All proposals')?> (<?=$noProposals?>)</a>
			<a id="page-user-proposals"
				class="btn btn-sm <?= $filter=='city'?'btn-success':'btn-default'?>"
				href="<?= $this->url('proposal', array('action'=>'user-proposals', 'id'=>$user->getUsrUUID(), 'page'=>1, 'sort' => $sort=='level'?'published':$sort, 'filter'=>'city'));?>">
				<?=$this->translate('City proposals')?> (<?=$cityProposals?>)</a>
			<a id="page-user-proposals"
				class="btn btn-sm <?= $filter=='region'?'btn-success':'btn-default'?>"
				href="<?= $this->url('proposal', array('action'=>'user-proposals', 'id'=>$user->getUsrUUID(), 'page'=>1, 'sort' => $sort=='level'?'published':$sort, 'filter'=>'region'));?>">
				<?=$this->translate('Region proposals')?> (<?=$regionProposals?>)</a>
			<a id="page-user-proposals"
				class="btn btn-sm <?= $filter=='country'?'btn-success':'btn-default'?>"
				href="<?= $this->url('proposal', array('action'=>'user-proposals', 'id'=>$user->getUsrUUID(), 'page'=>1, 'sort' => $sort=='level'?'published':$sort, 'filter'=>'country'));?>">
				<?=$this->translate('Country proposals')?> (<?=$countryProposals?>)</a>
</div>
		</div>
		<!-- /6 -->
		<div class="col-md-4">
			<div class="fltr">
				<ul class="nav">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-down"></i> </span>
							<!--  by <span class="caret"></span> -->
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-user-proposals"
								href="<?= $this->url('proposal', array('action'=>'user-proposals', 'id'=>$user->getUsrUUID(), 'sort'=>'name', 'page'=>1, 'order'=>'desc'));?>"><?= $this->translate('Name')?></a></li>
							<?php if ($filter=='none'):?>
							<li><a id="page-user-proposals"
								href="<?= $this->url('proposal', array('action'=>'user-proposals', 'id'=>$user->getUsrUUID(), 'page'=>1, 'sort'=>'level', 'order'=>'desc'));?>"><?= $this->translate('Level')?></a></li>
							<?php endif;?>
							<li><a id="page-user-proposals"
								href="<?= $this->url('proposal', array('action'=>'user-proposals', 'id'=>$user->getUsrUUID(), 'sort'=>'category', 'page'=>1, 'order'=>'desc'));?>"><?= $this->translate('Category')?></a></li>
							<li><a id="page-user-proposals"
								href="<?= $this->url('proposal', array('action'=>'user-proposals', 'id'=>$user->getUsrUUID(), 'sort'=>'status', 'page'=>1, 'order'=>'desc'));?>"><?= $this->translate('Status')?></a></li>
							<li class="divider"></li>
							<li><a id="page-user-proposals"
								href="<?= $this->url('proposal', array('action'=>'user-proposals', 'id'=>$user->getUsrUUID(), 'sort'=>'published', 'page'=>1, 'order'=>'desc'));?>"><?= $this->translate('Published date')?></a></li>
						</ul></li>
				</ul>
			</div>
			<div class="fltr">
				<ul class="nav">
					<li class="dropdown"><a class="dropdown-toggle"
						data-toggle="dropdown" href="#" aria-expanded="false"> <span
							class="label label-default"><i class="fa fa-caret-up"></i> </span>
							<!-- by <span class="caret"></span> -->
					</a>
						<ul class="dropdown-menu dropdown-menu-right">
							<li><a id="page-user-proposals"
								href="<?= $this->url('proposal', array('action'=>'user-proposals', 'id'=>$user->getUsrUUID(), 'sort'=>'name', 'page'=>1, 'order'=>'asc'));?>"><?= $this->translate('Name')?></a></li>
							<?php if ($filter=='none'):?>
							<li><a id="page-user-proposals"
								href="<?= $this->url('proposal', array('action'=>'user-proposals', 'id'=>$user->getUsrUUID(), 'page'=>1, 'sort'=>'level', 'order'=>'desc'));?>"><?= $this->translate('Level')?></a></li>
							<?php endif;?>
							<li><a id="page-user-proposals"
								href="<?= $this->url('proposal', array('action'=>'user-proposals', 'id'=>$user->getUsrUUID(), 'sort'=>'category', 'page'=>1, 'order'=>'asc'));?>"><?= $this->translate('Category')?></a></li>
							<li><a id="page-user-proposals"
								href="<?= $this->url('proposal', array('action'=>'user-proposals', 'id'=>$user->getUsrUUID(), 'sort'=>'status', 'page'=>1, 'order'=>'asc'));?>"><?= $this->translate('Status')?></a></li>
							<li class="divider"></li>
							<li><a id="page-user-proposals"
								href="<?= $this->url('proposal', array('action'=>'user-proposals', 'id'=>$user->getUsrUUID(), 'sort'=>'published', 'page'=>1, 'order'=>'asc'));?>"><?= $this->translate('Published date')?></a></li>
						</ul></li>
				</ul>
			</div>
			<div class="fltr right10 top5"><?= $this->translate('Sorted by')?> <?php if ($sort=='published'):?><?= $this->translate('Published date')?><?php else:?><?=ucfirst($sort)?><?php endif;?> 
                    <?=$order=='asc'?'<i class="fa fa-arrow-up"></i>':'<i class="fa fa-arrow-down"></i>'?></div>
		</div>
		<!-- /6 -->
	</div>
	<!-- /row -->
	<hr />
            <?php if(count($pagedProposals)>0):?>
                <?php foreach($pagedProposals as $index => $proposal): ?>
                        <div class="row">
		<div class="col-md-1" style="max-width: 60px;">
			<img
				src="<?= $this->basePath()?>/files/<?= $proposal->getCat()->getCatImage() ?>"
				height="42" width="42"
				title="<?= $proposal->getCat()->getCatCat()->getCatName() ?>">
		</div>
		<!-- /1 -->
		<?php $proposalDescription = preg_replace('/<[^>]*>/', ' ', $proposal->getPropDescription()); 

      $proposalDescription = (strlen($proposalDescription) > 200) ? substr($proposalDescription, 0, 200) . '...' : $proposalDescription;?>
      
		<div class="col-md-4">
                                <?= $proposal->getCat()->getCatCat()->getCatName() ?> - <?= $proposal->getCat()->getCatName()?>
                                        <br /> <a
				href="<?= $this->url('proposal', array('action'=>'view', 'id'=>$proposal->getPropUUID()));?>"
				title="<?=$proposalDescription?>"
				id="city-proposal-item" data-id="<?= $proposal->getPropUUID()?>"> <span
				class="big"><?= $proposal->getPropSavedName() ?></span>
			</a> <br />
			<?= $this->translate('Created')?> <i class="fa fa-clock-o"></i> <?= $proposal->getPropPublishedDate()->format('d/m/Y') ?>
                            </div>
		<!-- /4 -->
		<div class="col-md-3">
			<?= $this->translate('Current Status')?>:<br /> 
                                <?= $this->{"status-$index"}?><br />
			<?= $this->translate('Last updated')?> <i class="fa fa-clock-o"></i> <?= $proposal->getPropSavedDate()->format('d/m/Y')?> 
                    		</div>
		<div class="col-md-2">        
                            	<?= $this->{"status-details-$index"}?>
                            </div>
		<!-- /2 -->
		<div class="col-md-2">
			<a
				href="<?= $this->url('proposal', array('action'=>'favorite', 'id'=>$proposal->getPropUUID()));?>"
				alt="Favorite Proposal" id="proposal-user-proposals-favorite"
				data-favorite="<?= $proposal->getPropUUID()?>"><?php if (in_array($user, $proposal->getUsers())):?><i class="fa fa-heart"></i> <span
				class="small"><?= $this->translate('Remove Favorite')?></span><?php else:?><i class="fa fa-heart-o"></i> 
				<span class="small"><?= $this->translate('Add Favorite')?></span><?php endif;?></a> <br /> 
				
			<?= $this->partial('partial/add-proposal-to-program.phtml', ['proposal' => $proposal]); ?>
            	
	
			<span class="small"><a target="_parent"
				href="<?= $this->url('proposal', array('action'=>'view', 'id'=>$proposal->getPropUUID()));?>"><span
					class="big"><i class="fa fa-comments"></i></span>
                                <?= count($proposal->getComments()) ?> <?= $this->translate('Comments')?></a>
			</span>
		</div>
		<!-- /2 -->
	</div>
	<!-- /row -->
	<hr />
                        <?php endforeach; ?>
                    <?php else:?>
                        <div class="row">
                       	 <div class="col-md-12">
                        	<?php if ($filter=='none'):?>
                    			<?= sprintf($this->translate("User %s don't have any proposals."),$user->getUsrName())?>
                    		<?php else:?>
                    			<?= sprintf($this->translate("User %s doesn't have any proposals for his/her %s."), $user->getUsrName(), ucfirst($this->translate($filter)))?>
                    		<?php endif;?>
                    		</div>
                    	</div>

                    <?php endif;?>
<?= $paging; ?>
        </div>
<!-- /jumbotron -->
<script type="text/javascript">
	$(function () {
		proposalUserProposalsHandlers();
    });
</script>

<!-- /proposal/user-proposals -->
