<!-- comment/add-comment -->

<div id="comment-add-comment">
    <?php if ($user):?>
        <div class="row">
            <div class="col-md-12">
                <?php $commentForm->prepare();?>
                <?php $commentForm->setAttribute('action', $this->url('comment', array('action'=>'add-comment', 'type' => $type, 'id' => $id))); ?>
                <?php $commentForm->setAttribute('method', 'post');?>
                <?php $commentForm->setAttribute('id', 'comment-form');?>

                <?= $this->form()->openTag($commentForm);?>

                <div class="form-group" id="edit-description-comment">
                    <i class="fa fa-plus-circle"></i>&nbsp;<?= $this->translate('Add new comment')?>:
                    <div class="bot5 top10">
                        <button class="btn btn-mini btn-default" type="button"
                                id="textbox-format-button"
                                data-contenteditable-id="comment-add-comment-textbox"
                                data-format="bold">
                            <strong><i class="fa fa-times"></i> <?=$this->translate('Bold')?></strong>
                        </button>
                        <button class="btn btn-mini btn-default" type="button"
                                id="textbox-format-button"
                                data-contenteditable-id="comment-add-comment-textbox"
                                data-format="italic">
                            <i><i class="fa fa-times"></i> <?=$this->translate('Italic')?></i>
                        </button>
                        <button class="btn btn-mini btn-default" type="button"
                                id="textbox-format-button"
                                data-contenteditable-id="comment-add-comment-textbox"
                                data-format="underline">
                            <u><i class="fa fa-times"></i> <?=$this->translate('Underline')?></u>
                        </button>
                    </div>
                    <div class="form-control" contenteditable="true"  data-placeholder="<?=$this->translate('Enter your comment')?>"
                         maxlength="1000" over-text="<?=$this->translate('<span>0</span> characters in excess')?>" below-text="<?=$this->translate('<span>0</span> characters remaining')?>"
                         id="comment-add-comment-textbox"
                         style="width: 100%; min-height: 100px; height: 100%; max-height: 200px; overflow: auto"><?=$comText?$comText:''?></div>
                    <div id="comment-add-comment-textbox-count"></div>
                    <?= $this->formElement($commentForm->get('comText'));?> <br />
                    <span class="text-danger"><?= $this->formElementErrors($commentForm->get('comText'));?></span>
                </div>

                <div class="form-group bot20">
                    <button type="submit" class="btn btn-orange" id="comment-add-comment-submit" disabled="disabled"><i class="fa fa-comment-o" id="addCommentIcon"></i> <?= $this->translate('Submit Comment')?></button>
                </div>

                <?=$this->form()->closeTag();?>



            </div><!-- /12 -->
        </div><!-- /r -->
    <?php else:?>
        <div class="row bot20">
            <div class="col-md-12 text-center">
                <?php if ($type=='proposal' && $proposal->isMeasure()):?>
                    <?= $this->translate('Please register to comment this measure.')?>
                <?php elseif ($type=='proposal' && !$proposal->isMeasure()):?>
                    <?= $this->translate('Please register to comment this proposal.')?>
                <?php elseif ($type=='program'):?>
                    <?= $this->translate('Please register to comment this program.')?>
                <?php elseif ($type=='article'):?>
                    <?= $this->translate('Please register to comment this article.')?>
                <?php endif;?>
                <button type="button" class="btn btn-sm btn-orange"
                        data-url="<?=$this->url('home/user-register', array('action'=>'please-register'))?>"
                        data-dialog-title="<?=$this->translate('Please register')?>"
                        id="please-register-button">
                    <i class="fa fa-pencil-square-o" id="add-change-vote-div-icon"></i> <?= $this->translate('Register')?></button>

            </div>
        </div>
    <?php endif;?>
    <div id="allcom">
        <?= $this->commentListSection;?>
    </div>

</div>

<style>
    [contenteditable=true] {
        /*     border: solid 1px; /* Just to show what the area is. */ */
        /*     min-height: 1.2em; */
    }
    [contenteditable=true]:empty:before {
        content: attr(data-placeholder);
        color: darkgrey;
    }
</style>
<?php if ($user):?>
    <script type="text/javascript">
        $(function(){
            commentAddCommentHandlers();
        });
    </script>

    <script type="text/javascript">

        $(function() {

            if (location.hash=='#reply') {
                var div = document.getElementById("comment-add-comment-textbox");

                div.onfocus = function () {
                    window.setTimeout(function () {
                        var sel, range;
                        if (window.getSelection && document.createRange) {
                            range = document.createRange();
                            range.selectNodeContents(div);
                            range.collapse(true);
                            sel = window.getSelection();
                            sel.removeAllRanges();
                            sel.addRange(range);
                        } else if (document.body.createTextRange) {
                            range = document.body.createTextRange();
                            range.moveToElementText(div);
                            range.collapse(true);
                            range.select();
                        }
                    }, 1);
                };

                div.focus();
//        $("#comment-add-comment-textbox")[0].focus();
            }
        });



    </script>

<?php endif;?>

<!-- /comment/add-comment -->
