

<div id="inbox-delete-selected">

		<?php if (count($errors)==0):?>

	<form

		action="<?= $this->url('user/inbox', array('action'=>'delete-selected', 'type' => $type))?>"

		id="inbox-list-delete-selected-form" method="post">

		

		<?php foreach ($mails as $mail):?>

			<input type="hidden" name="mail[]" value="<?=$mail ?>">

		<?php endforeach;?>

		<div class="row">

			<div class="col-md-12">



				<?= $this->translate('Your realy want to delete')?> <?= count($mails)?> <?= $this->translate('mails')?>?<br>







			</div>

			<!-- /12 -->



		</div>

		<!-- end row -->



		<div class="row">

			<div class="col-xs-12">

				<hr />

			</div>

		</div>



		<div class="row">

			<div class="col-xs-12 text-right">

				<button type="submit"

					class="btn btn-orange" id="inbox-delete-selected-yes-button">

					<i class="fa fa-trash" id="inbox-delete-selected-yes-button-icon">

					</i> <?= $this->translate('Yes')?></button>

					<button type="button" class="btn"

						data-dismiss="modal">

						<i class="fa fa-ban"></i> <?= $this->translate('No')?>

					</button>

			</div>

		</div>

		<!-- /r -->

	</form>

</div>

<?php else:?>



<div class="row">

		<div class="col-md-12">

		

           <?= $this->translate('You cannot delete the selected emails')?>: <br>

           

           <ul>

           <?php foreach ($errors as $error):?>

           	

           <li> <?= $error?>

           <?php endforeach;?>

           </ul>

			</div>

			<!-- /12 -->

			

	</div>

		<!-- end row -->



    <div class="row">

    	<div class="col-xs-12">

    		<hr />

		</div>

	</div>

    

    <div class="row">

    	<div class="col-xs-12 text-right">

           <button type="button" class="btn" id="delete-proposal-cancel-button" data-dismiss="modal"><i class="fa fa-ban"></i> <?= $this->translate('Cancel')?></button>

		</div>

    </div><!-- /r -->



</div>

<?php endif;?>

			

	<script type="text/javascript">

		$(function () {



			inboxDeleteSelectedHandlers();

			

		});

	</script>

