<!-- inbox/view -->

<div class="panel panel-default" id="inbox-view-message"
	data-message-id="<?=$message->getIbxUUID()?>">
<?php if (($type=='received' && $message->getIbxToTrashDate()) || ($type=='sent' && $message->getIbxFromTrashDate()) || 
            ($type=='trash' && ($user==$message->getToUsr() && $message->getIbxToDeletedDate() || $user==$message->getFromUsr() && $message->getIbxFromDeletedDate() ))):?>
		<div class="panel-body" style="min-height:450px !important;text-align: center;vertical-align: middle;line-height: 450px; ">
					<div class="row">
						<div class="col-md-12 col-xs-12"><?= $this->translate('Please select a message to view.')?>
						</div>
					</div>
				</div>
				<!--/panel-body-->

		<?php else:?>
		
	<div class="panel-body" style="min-height: 450px !important;">
		
<?php $messageType = $this->configItem('demodyne.inbox.type'); ?>



	<div class="row text-right">
			<div class="col-md-12 col-xs-12">

        <?php if ($user!=$message->getFromUsr() || $message->getIbxType()==$messageType['new_comment']):?>

				<button type="button"
					data-url="<?= $this->url('user/inbox', array('action'=>'reply', 'id' => $message->getIbxUUID()));?>"
					class="btn btn-default" id="inbox-view-message-reply"
					title="<?= $this->translate('Reply')?>"
					data-dialog-title="<?=$this->translate('Reply to')?>"
					data-type="<?= $message->getIbxType()==1?$this->translate('comment'):$this->translate('message')?>"><i
					class="fa fa-reply"></i> </button>

        <?php endif;?>

        <?php if ($message->getIbxType()!=$messageType['new_comment']):?>

        	<button type="button"
					data-url="<?= $this->url('user/inbox', array('action'=>'reply-all', 'id' => $message->getIbxUUID()));?>"
					class="btn btn-default" id="inbox-view-message-reply-all"
					title="<?= $this->translate('Reply All')?>"
					data-dialog-title="<?=$this->translate('Reply to All')?>"
					> <i
					class="fa fa-reply-all"></i></button>

        <?php endif;?>

       		<button type="button"
					data-url="<?= $this->url('user/inbox', array('action'=>'forward', 'id' => $message->getIbxUUID()));?>"
					class="btn btn-default" id="inbox-view-message-forward"
					title="<?= $this->translate('Forward')?>"
					data-dialog-title="<?=$this->translate('Forward message')?>"><i class="fa fa-forward"></i></button>
				<button type="button" class="btn btn-default"
					id="inbox-view-message-print"
					title="<?= $this->translate('Print')?>">
					<i class="fa fa-print"></i>
				</button>
				<button type="button" class="btn btn-default"
					id="inbox-view-message-report"
					data-url="<?= $this->url('home/report', array('action'=>'add-report', 'type'=>'inbox', 'id' => $message->getIbxUUID()));?>"
					title="<?= $this->translate('Report as innapropiate')?>"
					data-dialog-title="<?=$this->translate('Report message as innapropriate')?>">
					<i class="fa fa-exclamation-triangle"></i>
				</button>
				<button
					data-url="<?= $this->url('user/inbox', array('action'=>'delete-one', 'id' => $message->getIbxUUID(), 'type' => $type));?>"
					class="btn btn-default" id="inbox-view-message-delete-one"
					data-message="<?=$this->translate('Please select a message to view.')?>"
					title="<?= $this->translate('Delete')?>"><i class="fa fa-trash-o"></i></button>
			</div>
		</div>
		
		<hr />
		<div class="row" id="inbox-view-message-print-zone">
			<div class="col-md-12 col-xs-12">

		

		 <?php if ($message->getIbxType()==$messageType['new_comment']): // 1 ?>
                            
        	<i class="fa fa-comments-o size15em violet"></i> <?= $this->translate('Comment by'); ?> 
        
        <?php elseif ($message->getIbxType()==$messageType['new_step']): // 2 ?>
        
        	<i class="fa fa-gears size15em violet"></i> <?= $this->translate('Implementation step for Proposal:'); ?>
        
         <?php elseif ($message->getIbxType()==$messageType['champion_news']): // 3 ?>
        
            <i class="fa fa-trophy size15em gold"></i> <?= $this->translate('Champion News for Proposal:'); ?>
        
        <?php elseif ($message->getIbxType()==$messageType['private_message']): // 4 ?>
        
        	<i class="fa fa-envelope-o size15em orange"></i> <?= $this->translate('Private message by'); ?> 
        	
		<?php elseif ($message->getIbxType()==$messageType['newsletter']): // 5 ?>
        
        	<i class="fa fa-newspaper-o size15em blue"></i> <?= $this->translate('Newsletter by'); ?> 
        
        <?php endif;?>

    		<a
					href="<?= $this->url('user/profile', array('action'=>'mini-profile', 'id'=>$message->getFromUsr()->getUsrUUID()));?>"
					data-title="<?= $message->getFromUsr()->getUsrName() ?>'s mini profile"
					data-id="<?=$message->getFromUsr()->getUsrUUID()?>"
					id="inbox-view-message-view-profile"> <span class="badge"><?= $message->getFromUsr()->getUsrName() ?></span></a>&nbsp;<i
					class="fa fa-clock-o"></i>

    		<?= $message->getIbxCreatedDate()->format("d/m/Y H:i")?>
	
			<?php if ($message->getIbxType()!=$messageType['newsletter']):?>

    		<br>

    		<?php if ($message->getIbxType()!=$messageType['new_comment']):?>

    			<?= $this->translate('Subject:'); ?> <?= $message->getIbxTitle()?>

    		<?php else:?>

        		<?php if ($message->getCom()->getProp()):?>

        		<span class="big"><?= $this->translate('Proposal')?>: <a
					href="<?= $this->url('proposal', array('action'=>'view', 'id'=>$message->getCom()->getProp()->getPropUUID()));?>"><?= $message->getCom()->getProp()->getPropName()?></a></span>

        		<?php else:?>

        		<span class="big"><?= $this->translate('Program')?>: <a
					href="<?= $this->url('program', array('action'=>'view-program', 'id'=>$message->getCom()->getProgram()->getProgUUID()));?>"><?= $message->getCom()->getProgram()->getProgName()?></a></span>

    			<?php endif;?>

    		<?php endif;?>
    		<?php endif;?>

    		<br>

    		<?php if ($message->getIbxType()!=$messageType['newsletter']):?>
        		<?= $this->translate('To:'); ?> 
    
    			<?php foreach ($toUsers as $toUser):?>
    
    				<a
					href="<?= $this->url('user/profile', array('action'=>'mini-profile', 'id'=>$toUser->getUsrUUID()));?>"
					data-title="<?= $toUser->getUsrName() ?>'s mini profile"
					data-id="<?=$toUser->getUsrUUID()?>"
					id="inbox-view-message-view-profile"> <span class="badge"><?= $toUser->getUsrName() ?></span></a>
    
				<?php endforeach;?>
			<?php endif;?>

    		<hr />
				<div class="bw">
			<?php if ($message->getIbxType()!=$messageType['newsletter']):?>
				<?= $message->getIbxText()?>
			<?php else:?>
				<?= $this->partial('dgi-module/newsletter/view-newsletter.phtml', ['newsletter'=>$message->getNewsletter()]); ?>
			<?php endif;?>
		</div>
			</div>
		</div>



        <script type="text/javascript">
            $(function () {
            	inboxViewHandlers(<?=$unreadMessage?>);
            });
        </script>


	</div>
	<!--/panel-body-->

<?php endif;?>
</div>
<!-- end panel -->

<!-- inbox/view -->
