<!-- report/submit-bug-success -->

<div id="report-submit-bug-success">


	<div class="row">
		<div class="col-md-12">
		
		<?=$this->translate('Thank you for submitting the bug. We will do our best to solve it quickly.')?> 
		
         
           
			</div>
			<!-- /12 -->
			
	</div>
		<!-- end row -->

    <div class="row">
    	<div class="col-xs-12">
    		<hr />
		</div>
	</div>
    
    <div class="row">
    	<div class="col-xs-12 text-right">
            <button type="button" class="btn" data-dismiss="modal"><i class="fa fa-ban"></i> <?= $this->translate('Close')?></button>
		</div>
    </div><!-- /r -->


</div>

<!-- /report/submit-bug-success -->
