<?= $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-type" content="text/html; charset=UTF-8">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans'
          rel='stylesheet' type='text/css'>
    <?= $this->headTitle($this->translate('Demodyne'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <!-- Le styles -->
    <?=
    isset($_SESSION['mobile']) && $_SESSION['mobile']?
    $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->appendStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css')
//        ->appendStylesheet('https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css')
        ->appendStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css')
        ->appendStylesheet($this->basePath() . '/css/jquery.mmenu.all.css')
        ->appendStylesheet($this->basePath() . '/css/demodyne.m.css')
        :
    $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->appendStylesheet($this->basePath() . 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css')
        ->appendStylesheet($this->basePath() . '/css/demodyne.bootstrap.css')
        ->appendStylesheet('https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.css')
        ->appendStylesheet($this->basePath() . '/css/style.css')
        ->appendStylesheet($this->basePath() . '/css/bootstrap-datepicker3.min.css');
    ?>
    <!-- Scripts -->
    <?= $this->headScript() ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js')?>
    <? if (isset($_SESSION['mobile']) && $_SESSION['mobile']) {
        $this->inlineScript()

//        ->appendFile('/js/bootstrap.js')
            ->appendFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js')
            ->appendFile('https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js')
//            ->appendFile('https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js')
            ->appendFile($this->basePath() . '/js/jquery.mmenu.all.min.js')
            ->appendFile($this->basePath() . '/js/moment.min.js')
            ->appendFile($this->basePath() . '/js/bootstrap-datetimepicker.min.js')
            ->appendFile($this->basePath() . '/js/bootstrap-datepicker.min.js')
            ->appendFile($this->basePath() . '/js/jquery.matchHeight-min.js')
            ->appendFile($this->basePath() . '/js/jquery.blockUI.js')
            ->appendFile($this->basePath() . '/js/jquery.print.js')
            ->appendFile($this->basePath() . '/js/demodyne.common.js')
            ->appendFile($this->basePath() . '/js/demodyne.js');
        }
        else {
            $this->inlineScript()
//                ->prependFile('https://code.jquery.com/jquery-2.2.4.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->appendFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js')
//        ->appendFile('/js/bootstrap.js')
                ->appendFile('https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js')
//                ->appendFile($this->basePath() . '/js/bootstrap-datepicker.min.js')
                ->appendFile($this->basePath() . '/js/moment.min.js')
                ->appendFile($this->basePath() . '/js/bootstrap-datetimepicker.min.js')
                ->appendFile($this->basePath() . '/js/bootstrap-datepicker.min.js')
                ->appendFile($this->basePath() . '/js/jquery.matchHeight-min.js')
                ->appendFile($this->basePath() . '/js/jquery.blockUI.js')
                ->appendFile($this->basePath() . '/js/jquery.print.js')
                ->appendFile($this->basePath() . '/js/demodyne.common.js')
                ->appendFile($this->basePath() . '/js/demodyne.js')
                ->appendFile($this->basePath() . '/js/demodyne.work.js');
            }
    ?>
    <?php $lang = $this->plugin('translate')->getTranslator()->getLocale()?>




    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
    <script>
        window.addEventListener("load", function(){
            window.cookieconsent.initialise({
                "palette": {
                    "popup": {
                        "background": "#423a33"
                    },
                    "button": {
                        "background": "#ffb800"
                    }
                },
                "theme": "classic",
                "position": "top",
                "content": {
                    "href": "https://www.demodyne.org/page/terms"
                }
            })});
    </script>



</head>
<body>
<? $mobile = isset($_SESSION['mobile']) && $_SESSION['mobile'];?>
<?php if ($mobile): ?>
    <?= $this->partial('layout/layout-mobile.phtml')?>
<?php else:?>
    <?= $this->partial('layout/layout-user.phtml')?>
<?php endif;?>

<div class="container" id="pageContent">
    <?= $this->content; ?>
</div>
<div class="container">
    <footer>
        <div class="row graylight">
            <div class="col-md-5 col-xs-12 text-xs-center bot5">&copy; 2015 - <?= date('Y') ?>
                <?= $this->translate('by') ?>
                <a href="<?= $this->url('home')?>"><span class="orange">DEMODYNE</span></a>. <?= $this->translate('All rights reserved.') ?>
            </div>
            <div class="col-md-2 col-xs-12 text-center bot5">
                <a href="https://www.facebook.com/demodyne" target="_blank"><i
                            class="fa fa-facebook size15em orange"></i></a>&nbsp;&nbsp; <a
                        href="https://www.linkedin.com/company/demodyne" target="_blank"><i
                            class="fa fa-linkedin size15em orange"></i></a>&nbsp;&nbsp; <a
                        href="https://twitter.com/demodyne" target="_blank"><i
                            class="fa fa-twitter size15em orange"></i></a>
            </div>
            <div class="col-md-5 col-xs-12 text-xs-center text-right">
                <? if (!$mobile):?>
                <span class="right20"> </span> <span class="right20"><a
                            href="<?= $this->url('home/pages', array('page'=>'legal'))?>" target="_blank"><span
                                class="orange"><?= $this->translate('Legal') ?></span></a></span>

                <a href="<?= $this->url('home/pages', array('page'=>'terms'))?>"
                    target="_blank"><span class="orange"><?= $this->translate('Terms & Conditions') ?></span></a>
                <?endif;?>
            </div>
        </div>
    </footer>
</div>




<!-- /container -->
<?= $this->inlineScript() ?>
<?php if ($lang != 'en' && (!isset($_SESSION['mobile']) || !$_SESSION['mobile'])):?>
    <script
            src="<?= $this->basePath('/js/datepicker-locales/bootstrap-datepicker.'.$lang.'.min.js')?> "
            charset="UTF-8"></script>
<?php endif;?>
<!-- Go to www.addthis.com/dashboard to customize your tools
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-553755353bc6bf82" async></script>-->
</body>
</html>
