<!-- dashboard/city-dashboard -->

<div id="city-dashboard-index">
  <ul class="nav nav-tabsj" style="padding-left:20px;">
    <li class="active"><a href="#news" data-toggle="tab">
      <?=$this->translate('News')?>
      </a></li>
    <li><a href="#myspace" data-toggle="tab" data-tabs="nav-tabs">
      <?=$this->translate('My Workspace')?>
      </a></li>
    <li><a href="#allprop" data-toggle="tab">
      <?=$this->translate('Citizen Proposals')?>
      </a></li>
    <li><a href="#allscn" data-toggle="tab">
      <?=$this->translate('Citizen Programs')?>
      </a></li>
    <li><a href="#officialp" data-toggle="tab">
      <?=$this->translate('Official Measures')?>
      </a></li>
    <li><a href="#all-events" data-toggle="tab">
      <?=$this->translate('Events')?>
      </a></li>
  </ul>
  <div id="myTabContent" class="tab-content panelforblack"> 
    
    <!-- tab news -->
    
    <div class="tab-pane fade active in" id="news">
      <div class="jumbotron">
        <div class="row">
          <div class="col-md-7 col-xs-12">
             <div class="row">
              <div class="col-md-12 col-xs-12">
            	<?=$this->carouselBannersSection?>
            	</div>
            </div>
            <div class="row">
              <div class="col-md-12 col-xs-12">
                <?= $this->newsSection ?>
              </div>
              <!-- end col6 --> 
            </div>
          </div>
          <div class="col-md-5 col-xs-12"> 
            
            <!-- UPCOMOING EVENTS -->
            <div>
            <?= $this->upcomingEventsSection ?>
            </div>
            <div>
            <?= $this->topProposalsSection ?>
            </div>
          </div>
          <!--/6--> 
        </div>
      </div>
    </div>
    <!-- endtab --> 
    
    <!-- tab content myspace -->
    
    <div class="tab-pane fade" id="myspace">
      
      <?=$this->workspaceSection?>
      
    </div>
    
    <!-- end tab content myspace --> 
    
    <!-- tab content allscn -->
    
    <div class="tab-pane fade" id="allscn">
      <?= $this->allProgramsSection ?>
    </div>
    
    <!-- end tab content allscn --> 
    
    <!-- tab content allprop -->
    
    <div class="tab-pane fade" id="allprop">
      <?= $this->allProposalsSection ?>
    </div>
    
    <!-- end tab content allprop --> 
    
    <!-- tab content OFFICIAL MEASURES -->
    
    <div class="tab-pane fade" id="officialp">
      <?= $this->allMesuresSection?>
    </div>
    
    <!-- end tab content officialp --> 
    
    <!-- tab content City Events -->
    
    <div class="tab-pane fade" id="all-events">
      <?= $this->allEventsSection?>
    </div>
    
    <!-- end tab content all-events --> 
    
  </div>
  
  <!-- end tab section --> 
  
</div>

<!-- end user-dashboard-div section -->


<script>
updateContextualHelp('#news');
    </script> 

<!-- /dashboard/city-dashboard -->
    