
<div id="city-dashboard-index">
    <div class="tab-disappear">
        <ul class="nav nav-tabsj" style="padding-left:20px;">
            <li class="active"><a href="#news" data-toggle="tab">
                    <?=$this->translate('News')?>
                </a></li>
            <?php if ($user):?>
            <li><a href="#myspace" data-toggle="tab" data-tabs="nav-tabs">
                    <?=$this->translate('My Workspace')?>
                </a></li>
            <?php endif;?>
            <li><a href="#allprop" data-toggle="tab">
                    <?=$this->translate('Citizen Proposals')?>
                </a></li>
            <li><a href="#citizenp" data-toggle="tab">
                    <?=$this->translate('Citizen Programs')?>
                </a></li>
            <li><a href="#officialm" data-toggle="tab">
                    <?=$this->translate('Official Measures')?>
                </a></li>
            <li><a href="#all-events" data-toggle="tab">
                    <?=$this->translate('Events & Live Sessions')?>
                </a></li>
        </ul>
    </div>
    <div id="myTabContent" class="tab-content panelforblack">

        <!-- tab news -->

        <div class="tab-pane fade active in" id="news">
            <?= $this->newsSection ?>
        </div>
        <!-- endtab -->

        <?php if ($user):?>
        <!-- tab content myspace -->
        <div class="tab-pane fade" id="myspace">

            <?=$this->workspaceSection?>

        </div>
        <!-- end tab content myspace -->
        <?endif;?>

        <!-- tab content allscn -->

        <div class="tab-pane fade" id="citizenp">
            <?= $this->allProgramsSection ?>
        </div>

        <!-- end tab content allscn -->

        <!-- tab content allprop -->

        <div class="tab-pane fade" id="allprop">
            <?= $this->allProposalsSection ?>
        </div>

        <!-- end tab content allprop -->

        <!-- tab content OFFICIAL MEASURES -->

        <div class="tab-pane fade" id="officialm">
            <?= $this->allMeasuresSection?>
        </div>

        <!-- end tab content officialm -->

        <!-- tab content City Events -->

        <div class="tab-pane fade" id="all-events">
            <?= $this->allEventsSection?>
        </div>

        <!-- end tab content all-events -->

    </div>

    <!-- end tab section -->

</div>

<!-- end user-dashboard-div section -->

